### ISSUE TITLE
Could not install ts-node globally

### ISSUE THREAD

**Issue by kukaki** [volta-cli/volta#1009]
I am able to install **ts-node** locally, but not globally. I have successfully installed **typescript** globally.

I am using..
Volta 1.0.4
Node 16.4.2
Npm 7.18.1
Ubuntu 21.04

```
$ npm i -g ts-node

added 15 packages, and audited 16 packages in 882ms

found 0 vulnerabilities
Volta error: Could not determine the name of the package that was just installed.

Please rerun the command that triggered this error with the environment
variable `VOLTA_LOGLEVEL` set to `debug` and open an issue at
https://github.com/volta-cli/volta/issues with the details!
```
and
```
$ VOLTA_LOGLEVEL=debug npm i -g ts-node
[verbose] Found default configuration at '/home/yvbr/.volta/tools/user/platform.json'
[verbose] Acquiring lock on Volta directory: /home/yvbr/.volta/volta.lock
[verbose] node@16.4.2 has already been fetched, skipping download

added 15 packages, and audited 16 packages in 724ms

found 0 vulnerabilities
[verbose] Unlocking Volta Directory
Volta error: Could not determine the name of the package that was just installed.

Please rerun the command that triggered this error with the environment
variable `VOLTA_LOGLEVEL` set to `debug` and open an issue at
https://github.com/volta-cli/volta/issues with the details!
[verbose] No custom hooks found
```

Please help.

**Comment by charlespierce** [comment]
Hi @kukaki, thanks for the report! I believe this is the same issue as #996, related to the fact that npm 7 installs peer dependencies by default, which breaks Volta's model for isolating dependencies. See that issue for a more thorough discussion.

You can work around this by using `npm i -g --legacy-peer-dependencies ts-node` (which Volta will likely do in the future automatically, to maintain the isolation that we use for global packages).

**Comment by alekslario** [comment]
> npm i -g --legacy-peer-dependencies ts-node

Didn't work for me. Node v14.16.1

**Comment by kukaki** [comment]
> npm i -g --legacy-peer-dependencies ts-node

@charlespierce Did not work for me as well. The same error persists.
