### ISSUE TITLE
[feature request]update volta by command 

### ISSUE THREAD

**Issue by Sepush** [volta-cli/volta#1014]
I expect a command to update the volta version like `volta upgrade self` or some other command to do this for mac  Linux and windows

**Comment by charlespierce** [comment]
Hi @Sepush, thanks for the suggestion! This is definitely something we'd like to do at some point, though there's a bit of work that's needed to make sure we have permissions. This is tracked under two different issues: #269 and #567 (Automatic updating), though admittedly there hasn't been much movement on either in some time.
