### ISSUE TITLE
Volta doesn't recognize typescript installed with yarn@3.0.0

### ISSUE THREAD

**Issue by mmykhaylov** [volta-cli/volta#1015]
# Problem
When trying to use tsc inside a typescript project with Yarn 3, Volta gives error: 

```
Volta error: Could not locate executable `tsc` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
```

## Steps to reproduce
1. 
```bash
mkdir new-folder
cd new-folder
yarn set version berry
yarn init
yarn add -D typescript
yarn dlx @yarnpkg/sdks vscode
```
2. Select workspace TypeScript
3.
```
tsc --init
```
4. Get error

## Versions
Volta: 1.0.4
Node: 16.6.2
Yarn: 3.0.0

**Comment by charlespierce** [comment]
Hi @mmykhaylov, thanks for reporting! I believe this is a result of Yarn Berry using Plug n Play by default. See #158 for tracking the support of PnP for global tool delegation. There is also more context about the recent versions of Yarn in #651
