### ISSUE TITLE
Does not work with sudo

### ISSUE THREAD

**Issue by UndiedGamer** [volta-cli/volta#1028]
So hey I have installed node and yarn with volta and when I use sudo npm I get:
```
sudo: npm: command not found
```
but when I do npm normally it works, same happens with yarn 

I installed node using
volta install node@latest

**Comment by UndiedGamer** [comment]
just realised sudo volta also does not work it returns command not found

**Comment by UndiedGamer** [comment]
Fixed this issue with running
```
sudo su
curl https://get.volta.sh | bash
volta install node
```

**Comment by ljharb** [comment]
You’re not supposed to be using sudo with node or npm - unless npm is in a global location and you’re trying to do a global install, which isn’t the case with volta. With node, you’d use authbind to access privileged ports.

**Comment by UndiedGamer** [comment]
so you mean authbind is like sudo?
but better as sudo works for stuff installed with apt

**Comment by ljharb** [comment]
authbind means you don't need sudo for anything. most things shouldn't be installed with apt anyways, since most things aren't officially distributed that way.

**Comment by UndiedGamer** [comment]
alright thanks
