### ISSUE TITLE
Document a list of projects who currently use Volta?

### ISSUE THREAD

**Issue by bodazhao** [volta-cli/volta#1029]
We can find list of projects who uses Volta (example through Sourcegraph: https://sourcegraph.com/search?q=context:global+volta+file:package.json&patternType=literal), and if it's documented on website or readme, it would help with growing Volta users.

What do you think? I'm happy to help and submit a PR for it.

**Comment by charlespierce** [comment]
@bodazhao Thanks for the suggestion! That would be really cool to see, so we'd definitely be open to a PR 👍🏻
