### ISSUE TITLE
Doucmentation for maunal installation procedure 

### ISSUE THREAD

**Issue by BasixKOR** [volta-cli/volta#1041]
In some non-typical workflows ([Nix](https://nixos.org/), dotfiles setup, etc.) users might want to control how Volta gets installed. It would be nice if there is some documentation explaining what changes does `curl get.volta.sh | bash` make to the system and how to do it for yourself.

**Comment by charlespierce** [comment]
Hi @BasixKOR, thanks for the question! We do have a description of the steps necessary (which is what the install script does) in the "Custom Installers" section towards the bottom of the [Advanced > Installers](https://docs.volta.sh/advanced/installers) docs.

Let me know if that covers what you need or if there are still areas that could use clarification.

**Comment by BasixKOR** [comment]
Thank you for referencing the documentation! I must've missed it.
