### ISSUE TITLE
How to install Node and NPM based on version pinned in `package.json`?

### ISSUE THREAD

**Issue by jensmeindertsma** [volta-cli/volta#1043]
I'm trying to run Volta in GitHub Actions to set up Node.js, and I'd love to install the Node version listed in my `package.json`.`volta`.`node` and the NPM version listed in `package.json`.`volta`.`npm`.

Is this possible?

**Comment by charlespierce** [comment]
Hi @jensmeindertsma, great question! We actually have an existing GitHub action for installing Volta (and the associated Node / npm / yarn versions) here: https://github.com/volta-cli/action

**Comment by jensmeindertsma** [comment]
That's exactly what I'm looking for 😊. Thanks for the quick response @charlespierce.
