### ISSUE TITLE
What's the recommended way of installing Node.js and NPM in Docker?

### ISSUE THREAD

**Issue by jensmeindertsma** [volta-cli/volta#1051]
I'm running into the issue where I want to install Node.js and NPM in Docker ( Alpine ) using Volta. I tried to run `volta install node`, but that installs the LTS version of Node.js, not the version that is specified in the `package.json` file. Anything I can do to fix this?

**Comment by charlespierce** [comment]
Hi @jensmeindertsma, great question! Volta will automatically download the versions that are set in `package.json` when you run a command that uses `node`, `npm`, `yarn`, etc. So in a sense, the recommended way to install them is _not_ to install them! Instead, run the command you need from the project directory and Volta will make sure the appropriate versions are used.

We have a blog post that describes a little more about the philosophy behind Volta's behavior: https://blog.volta.sh/2020/07/23/declare-your-tools/

Also, if there's a need to have a separate command that fetches the versions into the local cache, I'd love to hear more about the use-case.

**Comment by jensmeindertsma** [comment]
Awesome, that answers my question! Thanks
