### ISSUE TITLE
deploy Windows installer via appveyor

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#11]
We should generate the msi and deploy it via GitHub releases in the appveyor automation.

**Comment by chriskrycho** [comment]
I *think* this issue is now defunct, given our use of wix and the degree of work we've done there (which I don't *think* is automatable)? cc. @charlespierce

**Comment by charlespierce** [comment]
Yeah, this one can be closed. There's still the possibility for automating releases, but I think that would fall under a larger "automated releases" issue, as opposed to something Windows-specific.

We also aren't using AppVeyor anymore anyway, having moved to Azure Pipelines.
