### ISSUE TITLE
Add ls subcommand

### ISSUE THREAD

**Issue by equiman** [volta-cli/volta#1123]
I'm actually using `ls` command to see those versions:

![image](https://user-images.githubusercontent.com/933393/146605536-36b1cb3b-2e27-46b4-bbea-4e399ebb3c0e.png)

But it will be cool to have an option to see it directly as `volta ls` like `nvm ls` does

![image](https://user-images.githubusercontent.com/933393/146605786-a9ecc02d-3dfc-462c-8722-b2fe5b354450.png)

Showing all installed versions and the current version in use.

**Comment by charlespierce** [comment]
Hi @equiman, thanks for reaching out! Check out the [`volta list`](https://docs.volta.sh/reference/list) command, I think that should cover most of the listing use-cases! `volta list node` will show all of the versions of Node available locally, indicating which one is active for your current directory. `volta list all` will show the versions of all tools Volta is managing, including `node`, `yarn`, `npm`, and global binaries.

Let us know if there's some info missing there!

**Comment by equiman** [comment]
Oh, my mistake. 

I see the [volta list](https://docs.volta.sh/reference/list) command but not the args at the end😳
Those commands `volta list all` and `volta list node` solve the problem.

Thanks!
