### ISSUE TITLE
Can't update yarn

### ISSUE THREAD

**Issue by existe-deja** [volta-cli/volta#1147]
See the results of the following commands. What am I doing wrong?

```zsh
➜  ~ yarn -v
1.22.10
➜  ~ npm install --global yarn
   note: using Volta to install Yarn
success: installed and set yarn@1.22.17 as default
➜  ~ yarn -v
1.22.10
```

**Comment by existe-deja** [comment]
Waiting for v3 so.
just to say after an install yarn warns me:
`warning Your current version of Yarn is out of date. The latest version is "1.22.17", while you're on "1.22.10".`

**Comment by chriskrycho** [comment]
@existe-deja that's expected: if you `volta pin yarn@latest` or `volta install yarn@latest` (or use the actual specific version) it'll update to `1.22.17` and you'll see that go away. 😄

**Comment by charlespierce** [comment]
@existe-deja My apologies, I completely misunderstood the issue you're seeing! It looks like Volta is properly installing `1.22.17`, but then when you run `yarn -v` you're still seeing `1.22.10`. Is it possible you're working in a project that has a local pinned version? Volta should give a message on global install letting you know that the project is different, but just wanted to confirm.

More likely, is there another `yarn` installed on your system that is ahead of Volta's? What is the output of `which -a yarn`?

**Comment by existe-deja** [comment]
Thanks for reopening this!
To avoid any conflict I deleted all my previous installations and everything related to node including volta to strat with a fresh volta setup.

```
$ volta pin yarn@latest
success: pinned yarn@1.22.17 in package.json
$ yarn -v 
1.22.10
$ which yarn
/home/existe-deja/.volta/bin/yarn
```

**Comment by charlespierce** [comment]
Wow, that's super odd. To check a couple extra details, can you do `which -a yarn` to get the full list of possible resolutions? Also, can you run:
```
VOLTA_LOGLEVEL=debug yarn -v
```
Assuming things are going through Volta, the latter should print out some extra messages about from where Volta is pulling the version.

One other thing worth trying would be to completely restart your terminal session / shell. One guess I have is that the shell has a cached lookup for `yarn` pointing somewhere else, so even though the Volta version is first on the `PATH`, it's not actually being run (we've seen similar issues in the past where the shell likes to not react to changes).

**Comment by existe-deja** [comment]
The results of the commands you asked. Pretty weird.
```
$ which -a yarn
/home/existe-deja/.volta/bin/yarn
$ VOLTA_LOGLEVEL=debug yarn -v
[verbose] node@16.13.2 has already been fetched, skipping download
[verbose] yarn@1.22.17 has already been fetched, skipping download
[verbose] Active Image:
    Node: 16.13.2 from project configuration
    npm: 8.1.2 from project configuration
    Yarn: 1.22.17 from project configuration
1.22.10
[verbose] No custom hooks found
```
I checked carefully and I found I had remaining old files. a `~/.yarnrc` file with a  reference of `~/.yarn` folder with yarn 1.22.10 inside. After deleting all of them I get the latest yarn version :tada: 

Thanks for the time spent and the ideas on this. Congrats for the excellent job on this software.
