### ISSUE TITLE
List available versions

### ISSUE THREAD

**Issue by jsejcksn** [volta-cli/volta#1156]
> Sorry if this a duplicate (I searched, but didn't find a relevant issue title)

It doesn't seem that I can use Volta to discover available versions of a tool to install. For example: if I want to install the version of Node that is the last patch release before the current LTS (at this moment `16.13.2` instead of `16.14.0`), how do I see what the version number is so I can know what version to use when running the install?

I'd like a command like one of these (syntax suggestions welcome):
```
# volta list available <tool[@semver]>
# volta list --available <tool[@semver]>
# volta list --available <tool> [<semver>]
# etc.

volta list available node@16
```

which would show a sorted [list of versions](https://nodejs.org/dist/) like:

```
16.0.0
16.1.0
16.2.0
16.3.0
16.4.0
16.4.1
16.4.2
16.5.0
16.6.0
16.6.1
16.6.2
16.7.0
16.8.0
16.9.0
16.9.1
16.10.0
16.11.0
16.11.1
16.12.0
16.13.0
16.13.1
16.13.2
16.14.0
```

Then I can use the information to install the desired version:
```
volta install node@16.13.2
```

**Comment by charlespierce** [comment]
Hi @jsejcksn, thanks for the suggestion! I believe we have this tracked in #573 (it may not have shown up in search since the suggestion there was based on `n ls-remote`)
