### ISSUE TITLE
Npm link seems broken

### ISSUE THREAD

**Issue by ThumusLive** [volta-cli/volta#1168]
Hi, I don't know why but volta seems to not parsed arguments when we use the sys of `npm link`
I'll explain, there is my code :

```js
const [,, args] = process.argv
console.log(args)
```
It returns : 
![image](https://user-images.githubusercontent.com/42680097/155628538-369dcaaa-b85d-40ec-8bc6-2a1b29170d07.png)

But when I link it with `npm link`, 0 arguments are parsed :

![image](https://user-images.githubusercontent.com/42680097/155628680-122a536d-7e11-4048-9805-1bf41631738a.png)
(tools is the name of the package) 

and I've tried `volta run`

![image](https://user-images.githubusercontent.com/42680097/155628779-04e6833f-23ba-4c6b-8077-acc2dbba249b.png)

Is there something I don't know about or it's a bug ?

Volta version : 1.0.5
OS: Windows 10

**Comment by charlespierce** [comment]
Hi @ThumusLive, thanks for reporting! I can't seem to replicate that behavior. Can you share the full `cli.js` source and the `package.json`?

**Comment by ThumusLive** [comment]
Sure, `cli.js` contains only that : 
![image](https://user-images.githubusercontent.com/42680097/155710324-995a2f4f-0250-4555-9e3c-6ce54131ab45.png)
And `package.json` contains : 
```json
{
  "name": "tools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bin": {
    "tools" : "./cli.js"
  }
}

```

**Comment by charlespierce** [comment]
Hmm, that's surprising! With that setup, if I have `cli.js` without a `#!` line at the top, trying to run `tools` as a command results in shell errors about `const` not being a command. If I _do_ have `#!/usr/bin/env node` at the top of the file, then it works as expected.

Is it possible you have a shell extension or something else that sets up an alternative approach to executing a JS command? What OS / shell is this?

I'd be interested to see what the whole of `process.argv` looks like when you call it this way.

**Comment by ThumusLive** [comment]
I'm on windows 10 x)
I'll try with that

**Comment by charlespierce** [comment]
@ThumusLive Ahh, okay that's strange! I'll see if I can reproduce on my Windows machine and track down what it's doing wrong, thanks!
