### ISSUE TITLE
Stdout/Stderr issue in VSCode

### ISSUE THREAD

**Issue by misozask** [volta-cli/volta#1184]
Hi,
I'm having an issue when running the code inside VSCode - I'm not seeing stuff printed to stdout/stderr in debug console.
```js
// test.js
console.log('log')
console.error('error')
process.stdout.write('stdout\n')
process.stderr.write('stderr\n')
```

```js
// launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"skipFiles": ["<node_internals>/**"],
			"program": "${file}",
		}
	]
}
```
When starting debug F5, or Ctrl + F5, I'm seeing just
```js
C:\Program Files\Volta\node.exe ./test.js
log
error
```

When running in terminal it is OK
```js
$ C:\Program Files\Volta\node.exe ./test.js
log
error
stdout
stderr
```

Is there any switch in Volta, or VSCode which turns on stdout/stderror?
Or any other workaround?

Thanks!

**Comment by charlespierce** [comment]
Hi @misozask, there isn't anything in Volta that messes with the `stdout` or `stderr` output. Once the underlying `node` command is executed, Volta is hands-off and both streams are forwarded directly. You can see that in the terminal case, as well as through `log` and `error` coming through in the debug case.

My first guess would be that this is related to VS Code debugging somehow intercepting or affecting `process.stdout` and `process.stderr`. From the [VS Code docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes), it looks like that is the case, and you can use an attribute `outputCapture` to change the behavior if you want / need to write to `stdout` and `stderr` directly.

**Comment by misozask** [comment]
Thanks @charlespierce for pointing me to `outputCapture`, it has solved the issue!
