### ISSUE TITLE
Installation on ARMx64 emulated Linux 

### ISSUE THREAD

**Issue by ssukienn** [volta-cli/volta#1190]
Hi. How to install volta on emulated arm64 Ubuntu Linux using Mac M1 UTM?

```
user@ubuntu-20-live-server:~/development$ curl https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12319  100 12319    0     0  23464      0 --:--:-- --:--:-- --:--:-- 23420
^[[AError: Sorry! Volta currently only provides pre-built binaries for x86_64 architectures.

user@ubuntu-20-live-server:~/development$ uname -a
Linux ubuntu-20-live-server 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:50:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

So basically it's Linux arm64 but `uname -m` etc. (whatever volta use, checked the script a bit) returns `aarch64`.

**Comment by charlespierce** [comment]
Hi @ssukienn, thanks for reporting! I believe this is the same root issue as #1049: We don't currently provide a prebuilt binary for Linux on ARM architectures. There was some work done to address that, however there are a lot of constraints that are blocking (if you're interested, see #1161, #1163, #1165 for some of the intermediate work and discussions)
