### ISSUE TITLE
How to install global package

### ISSUE THREAD

**Issue by myNameIsDu** [volta-cli/volta#1191]
When i run this command 
```
npm install sever -g
```
And then it failed
```
➜  ~ serve -v
zsh: command not found: serve
```
And i use the example of the docs
```
yarn global add vuepress
```
It worked
```
➜  ~ vuepress -v
vuepress/1.9.7 darwin-x64 node-v16.14.2
```

I found this [blog](https://blog.volta.sh/2019/06/18/global-installs-done-right/)
So,I thought i might to use `volt install serve`
Finally,I made it.
But why does the `yarn global add vuepress` work? I didn't find the answer : (

**Comment by nemonemi** [comment]
I'm guessing you still have yarn 1 installed globally, and yarn 1 supports global packages.
