### ISSUE TITLE
progress spinner for Windows

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#12]
We can't currently do streaming reads from Zip files -- there's an [open PR on this for zip-rs](https://github.com/mvdnes/zip-rs/pull/37) but it's been stalled for quite some time.

Until we have a solution to this, we should show a progress spinner in the UI.

**Comment by charlespierce** [comment]
I did a test using the `read_zipfile_from_stream` method that came from that PR, and unfortunately it seems like it's not performant. On my windows machine with the current master, it takes ~1.5 minutes to download and unpack the most recent Node (which itself is a little too long). Unpacking directly from the stream took ~6.5 minutes, so more than 4 times as long.
