### ISSUE TITLE
Can't install node on Macbook M1

### ISSUE THREAD

**Issue by GeoffreyPlitt** [volta-cli/volta#1201]
Volta doesn't seem to install node correctly on my system:

gplitt@geoffpl04tl2prg ~ % volta --version
1.0.6
gplitt@geoffpl04tl2prg ~ % volta install node
success: installed and set node@16.14.2 (with npm@8.5.0) as default
gplitt@geoffpl04tl2prg ~ % node
zsh: command not found: node

Even if I close the terminal and open a new one, it can't find Node.

System info:
gplitt@geoffpl04tl2prg ~ % uname -a
Darwin geoffpl04tl2prg.lan 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

Please advise, thank you.

**Comment by charlespierce** [comment]
Hi @GeoffreyPlitt, that's very odd! It seems like `volta` itself is on your PATH, but the shims (e.g. `node`, `npm`, etc.) aren't found. On MacOS, by default, the `volta` binary should be in the same location as `node` (`~/.volta/bin`), so if one is accessible the others should be as well.

How did you install Volta? Can you share the output of `echo $PATH` and `ls -la ~/.volta/bin`?

**Comment by GeoffreyPlitt** [comment]
Yes it looks like my path got corrupted somehow. I eventually got things working by starting over. I don't think my issue is going to happen for anyone else. Closing for now-- thanks for the reply!

**Comment by AfrazHussain** [comment]
I actually have the exact same issue. My path is not corrupted, and I have even tried reinstalling volta. I would really appreciate if you could let me know what ended up helping you. 

I have the M1 Max Macbook.

`echo $PATH`:
```
/Users/afraz/.volta/bin:/Users/afraz/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin
```

`ls -la ~/.volta/bin`
```
drwxr-xr-x  11 username  staff      352 28 Jun 21:56 .
drwxr-xr-x   9 username  staff      288  4 Mar 18:16 ..
lrwxr-xr-x   1 username  staff       34 28 Jun 21:56 ignite -> /Users/username/.volta/bin/volta-shim
lrwxr-xr-x   1 username  staff       34 28 Jun 21:56 ignite-cli -> /Users/username/.volta/bin/volta-shim
lrwxr-xr-x   1 username  staff       34 28 Jun 21:56 node -> /Users/username/.volta/bin/volta-shim
lrwxr-xr-x   1 username  staff       34 28 Jun 21:56 npm -> /Users/username/.volta/bin/volta-shim
lrwxr-xr-x   1 username  staff       34 28 Jun 21:56 npx -> /Users/username/.volta/bin/volta-shim
-rwxr-xr-x   1 username  staff  5855187  2 Jun 04:15 volta
-rwxr-xr-x   1 username  staff  4291035  2 Jun 04:15 volta-migrate
-rwxr-xr-x   1 username  staff  4981400  2 Jun 04:15 volta-shim
lrwxr-xr-x   1 username  staff       34 28 Jun 21:56 yarn -> /Users/username/.volta/bin/volta-shim
```

**Comment by ltomes** [comment]
The 'issue' in my case is volta is placing:
```
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
```
in .bash_profile after install, but most users are using zsh and need those lines in .zshrc or .zprofile.
Moving to the appropreate shell resulted in npm and node linking on path as expected.
