### ISSUE TITLE
curl https://get.volta.sh | bash doesn't work on ubuntu 22.04

### ISSUE THREAD

**Issue by kimhongsu** [volta-cli/volta#1209]
Hello. 

The installation command gives me an error on ubuntu 22.04
`curl https://get.volta.sh | bash`

>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 12319  100 12319    0     0  21955      0 --:--:-- --:--:-- --:--:-- 21959
>   Installing latest version of Volta (1.0.6)
>     Checking for existing Volta installation
>     Fetching archive for Linux, version 1.0.6
> curl: (22) The requested URL returned error: 404                              
> 
> Error: Could not download Volta version '1.0.6'. See https://github.com/volta-cli/volta/releases for a list of available releases

**Comment by pkleanthous** [comment]
Also, if you manually download and extract the binaries, then the following error occurs:
```bash
./volta
./volta: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

```

**Comment by pwespi** [comment]
Related to #1150

**Comment by charlespierce** [comment]
Volta 1.0.7 was just published, which includes support for OpenSSL 3.0, so this should be resolved!

**Comment by nansouille** [comment]
hello, for thoes who have a curl error 23 
try this
After a very long research I found a useful hint.

[Can't write to a hidden path using Curl](https://askubuntu.com/questions/1356327/cant-write-to-a-hidden-path-using-curl)

Basically snap curl is useless. Uninstall it properly. Get the proper apt curl, and everything works like a charm.

```
$ sudo snap remove curl
$ sudo apt install curl
```

https://askubuntu.com/questions/1387141/curl-23-failure-writing-output-to-destination


ERROR```

sudo curl https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10930  100 10930    0     0  39708      0 --:--:-- --:--:-- --:--:-- 39601
  Installing latest version of Volta (1.1.0)
    Checking for existing Volta installation
    Fetching archive for Linux, version 1.1.0
Warning: Failed to open the file /tmp/tmp.qEoW34dDCK/volta-1.1.0-linux.tar.gz: 
Warning: No such file or directory
                                                                           0.0%curl: (23) Failure writing output to destination

Error: Could not download Volta version '1.1.0'. See https://github.com/volta-cli/volta/releases for a list of available releases
```

**Comment by rohyadav** [comment]
Anyone have an idea ? how to remove this package after installation  ?
I have used this url **curl https://get.volta.sh | bash**
Now I want to remove this package volta - how do i remove this. I am using Mac book m1

**Comment by xqrizz-kii** [comment]
Ddd

**Comment by Bryanlicuy17** [comment]
curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
