### ISSUE TITLE
Latest Yarn is 1.22.19 but Volta only finds 1.22.18

### ISSUE THREAD

**Issue by felipecrs** [volta-cli/volta#1233]
https://github.com/yarnpkg/yarn/releases/tag/v1.22.19

```console
❯ volta install yarn
success: installed and set yarn@1.22.18 as default
```

**Comment by ljharb** [comment]
That’s because .18 is the one set as “latest”. This is how npm works also.

**Comment by felipecrs** [comment]
Ok ok, got it. Thank you for explaining!

It's unfortunate that yarn keeps complaining about it being outdated, but I guess this is their fault then.
