### ISSUE TITLE
🤔 Windows 11 Git Bash...

### ISSUE THREAD

**Issue by oneezy** [volta-cli/volta#1236]
😢 

![image](https://user-images.githubusercontent.com/7369575/169752413-d449db86-ac18-4fb9-914f-d5650cae47b0.png)

_**\* A hem \***_
![image](https://user-images.githubusercontent.com/7369575/169757372-70add434-9a69-4b47-a0c3-86d70652219d.png)

**Comment by Lemmingh** [comment]
Your description is a puzzle. I'm afraid it's too hard to understand a lone mysterious screenshot.

---

Still, guessing from the picture, I believe **you took a wrong installer**. The Windows installer should be a MSI file from the [GitHub Releases](<https://github.com/volta-cli/volta/releases/latest>).

Make sure to fully understand the instructions before taking action:

<https://docs.volta.sh/guide/getting-started/#windows-installation>

**Comment by oneezy** [comment]
guessing you don't have windows?

haven't tried again, but enabling symlinks is probably the issue

![image](https://user-images.githubusercontent.com/7369575/172768910-e9fa9c9f-448f-4cc2-9231-bc78bfe1cc98.png)

**Comment by charlespierce** [comment]
Hi all, please remember to be respectful to other commenters.

@oneezy The `curl https://get.volta.sh | bash` command is the installer for MacOS / Linux. While Git Bash on Windows simulates a Unix environment, it is still ultimately Windows and the `curl` installer won't work for that environment. As @Lemmingh mentioned, on Windows you should use the MSI installer to install Volta—this will enable it for Git Bash as well.

**Comment by oneezy** [comment]
thank you @charlespierce for the kind* instructions. it's not immediately obvious what to do for Windows users when visiting the homepage..It might be worth linking to a Windows guide there or even doing some smart OS detection to display proper setup per environment.

I almost gave up on this..glad i asked and found out about the MSI installer 😄

**Comment by bmrejen** [comment]
> Hi all, please remember to be respectful to other commenters.
> 
> @oneezy The `curl https://get.volta.sh | bash` command is the installer for MacOS / Linux. While Git Bash on Windows simulates a Unix environment, it is still ultimately Windows and the `curl` installer won't work for that environment. As @Lemmingh mentioned, on Windows you should use the MSI installer to install Volta—this will enable it for Git Bash as well.

No, it only works in the Window Command Prompt, not Git Bash. Any ideas? 
![image](https://github.com/volta-cli/volta/assets/20118433/9ed72ab3-f133-4e94-9bff-77bc53da2a66)

**Comment by Ashu-r** [comment]
@bmrejen in my case, I had to restart the git bash and then it worked.

**Comment by biswaketu** [comment]
curl -sSf https://naveenrajm7.github.io/utm-gallery/getbox.sh | sh -s windows-11
