### ISSUE TITLE
volta use to switch versions

### ISSUE THREAD

**Issue by yosiasz** [volta-cli/volta#1260]
Greetings,

Is there a way to switch versions of node without using

```
volta install node@12
```

instead doing

```
volta use node@12
```

Thanks for lovely node v manager!

**Comment by govindg312** [comment]
You can use the volta pin for a project. For example  if you run `volta pin node@16.15` within your project root, your `package.json` would have a new property which should look like this

```
{
  ...,
  "volta": {
    "node": "16.15.1"
  }
}
```
This replaces the need for  `nvm use` when we have a `.nvmrc`  file. To update the  global context for node, the only option is `volta install node@<version simver>`.

**Comment by charlespierce** [comment]
@yosiasz For selecting the default Node version (used globally and outside of pinned projects), `volta install node@version` is currently the only way. We have a rough idea, but still need an RFC for what verb we would use in place of `install`. See https://github.com/volta-cli/volta/issues/994 for more issues and to track any updates!

**Comment by Drjacky** [comment]
@charlespierce How do I check the node version?
Something like this `volta node --version` didn't work.
Thanks!

**Comment by chriskrycho** [comment]
You just do `node —version`; that will run with the current version. You can also use [the `volta list` command](https://docs.volta.sh/reference/list), like `volta list node`.
