### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by suryashekhawat** [volta-cli/volta#1266]
% curl --insecure https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12319  100 12319    0     0   4246      0  0:00:02  0:00:02 --:--:--  4245
  Installing latest version of Volta ()
    Checking for existing Volta installation
    Fetching archive for Linux, version 

curl: (22) The requested URL returned error: 404 Not Found
Error: Could not download Volta version ''. See https://github.com/volta-cli/volta/releases for a list of available releases

**Comment by charlespierce** [comment]
Hi @suryashekhawat, thanks for reporting! That's very odd, it looks like the installer wasn't able to locate the latest version of Volta (based on the line `Installing latest version of Volta ()`). From there that cascaded into other errors trying to download a file that doesn't exist.

Are you possibly behind a firewall that doesn't have direct access to https://volta.sh/latest-version ? That's the URL we connect to for determining the latest available version. We also then download that version from GitHub, so if that is also blocked / not working that could be a blocker. There are a couple of possible workarounds I can think of:

1. If you have access to github but not `volta.sh/latest-version`, then you could run the installer and provide the version directly via (Version `1.0.8` is the latest as of this writing):
```
curl https://get.volta.sh | bash -s -- --version 1.0.8
```
2. You could download the release tarball directly from the releases page here on GitHub, and then follow the steps under "Custom Installers" here: https://docs.volta.sh/advanced/installers to install it manually.

Let us know if neither of those works!

**Comment by Ventzy** [comment]
I had the same issue and `curl https://get.volta.sh | bash -s -- --version 1.0.8` did the trick. Thanks.

**Comment by suryashekhawat** [comment]
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
`

curl https://get.volta.sh -k | bash -s -- --version 1.0.8

This worked for me, Thanks @Ventzy
