### ISSUE TITLE
[question] Can volta set node arch to 32 bit?

### ISSUE THREAD

**Issue by radiorz** [volta-cli/volta#1272]
when we use nvm we could set node 32 bit like this:
```
nvm install 12.22.10 32

nvm use 12.22.10 32
```
How to set node arch using volta

**Comment by charlespierce** [comment]
Hi @radiorz, thanks for the question! We don't currently have the ability to install 32-bit versions on a 64-bit machine, that's tracked in #967 (which it looks like you already found :smile:). Please follow that issue for updates.
