### ISSUE TITLE
Latest version of volta seems to always use/install yarn 3.x.x even when specifying 1.x.x

### ISSUE THREAD

**Issue by ryanwh-dw** [volta-cli/volta#1291]
Latest version of volta seems to always use/install yarn 3.x.x even when specifying 1.x.x.

See commands below + the yarn behavior is definitely version 3.

```
volta ls
⚡️ Currently active tools:

    Node: v16.16.0 (current @ /path/to/package.json)
    npm: v8.5.0 (current @ /path/to/package.json)
    Yarn: v1.22.17 (current @ /path/to/package.json)
    Tool binaries available: NONE
```

```
which yarn
/path/to/.volta/bin/yarn
```

```
yarn --version
3.2.2
```

**Comment by ryanwh-dw** [comment]
`yarn set version 1.22.17` fixed the issue, but shouldn't be needed, right?

**Comment by charlespierce** [comment]
@ryanwh-dw Yarn has its own delegation / version management via `yarn set version`, that installs a file in the local repo and even the "global" Yarn will delegate to that version. Is it possible the repo you were working in had previously set that via `yarn set version berry` or similar? In that case Volta would launch the global 1.22.17, but then that global would delegate based on Yarn's own handling.

**Comment by ryanwh-dw** [comment]
I don't _think_ that happened but it is possible. Thanks! We're up and working now so we can close this issue as needed.
