### ISSUE TITLE
Volta error: Could not locate executable `pnpm` in your project

### ISSUE THREAD

**Issue by Mr-xzq** [volta-cli/volta#1293]
Even if you have pnpm installed globally.

When you set packageManager and pnpm as devDependencies in package.json:

```json
{
  "packageManager": "pnpm@7.9.0",
  "devDependencies": {
    "pnpm": "7.9.0",
   }
}
```

Then you run command in project:

```shell
pnpm install
```

Error Info:
```
Volta error: Could not locate executable `pnpm` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
```

Is it related to this?
https://docs.volta.sh/guide/understanding#managing-your-project

**Comment by charlespierce** [comment]
Hi @Mr-xzq, thanks for the question! There are a couple of connected issues here:

1. Volta doesn't currently support `pnpm` special-cased as a package manager like `yarn` and `npm`. There's a PR open to add that, however even when it does, Volta also doesn't use the `packageManager` key, rather it uses the `volta` key as described in the "Managing Your Project" section you linked.
2. For global packages (which is how Volta currently treats `pnpm`, given the first issue), if a project has a dependency on a binary (like you have with `pnpm` in `devDependencies`, then Volta will attempt to delegate to the local version. However, in this case, the package manager itself is what is listed as a dependency, so it's a bit of a dependency loop.

For the time being, I believe it should work to use the global default version of `pnpm` if you remove the `devDependencies` entry for `pnpm`. Longer-term, once #1273 lands then we'll directly support pinning `pnpm` via `volta pin pnpm`. We also can separately investigate using `packageManager` as a source of truth, but there's still some outstanding design that needs to be done on using separate sources of truth (see #282 for that tracking issue).

**Comment by Mr-xzq** [comment]
Hi @charlespierce, thank you very much for your answer!

Your answer solved my question very well!

I just need to remove pnpm in devDependencies:
```diff
{
  "devDependencies": {
--    "pnpm": "7.9.0",
   }
}
```

Looking forward to the follow-up progress of Volta's support for pnpm. https://github.com/volta-cli/volta/pull/1273

**Comment by FiringJ** [comment]
tks. after i delete 'pnpm' in devDependencies, `pnpm install` works.

**Comment by jxxl998** [comment]
thx, same problem here but works fine after deleting `devDependencies`, still, i don't fully understand why it will result in dependency loop 🤔

**Comment by ronny1020** [comment]
I know this is closed, but I am working on a forked project that has the pnpm in the devDependencies and facing this issue. I can't remove it. Is there another way to solve this issue?

**Comment by iiiiicecream** [comment]
> I know this is closed, but I am working on a forked project that has the pnpm in the devDependencies and facing this issue. I can't remove it. Is there another way to solve this issue?

me toooo

**Comment by Excalibur0w0** [comment]
me toooooooo
