### ISSUE TITLE
Question: will a volta installation or pinning kill running processes 

### ISSUE THREAD

**Issue by gregpalaci** [volta-cli/volta#1327]
I've read https://docs.volta.sh/guide/understanding
but say there is an old server and there's a bunch of random nodemon and long running processes started in the context of node 12, form /usr/bin/node

I'm I able to use volta elsewhere on the server without interrupting these for the time being?

**Comment by charlespierce** [comment]
Hi @gregpalaci, thanks for reaching out! Running `volta install` or `volta pin` shouldn't affect any running processes (unless those process are themselves spawning other processes). The primary thing those command do is write a version into a configuration file (either internal to Volta for `install` or in `package.json` for `pin`). They can also fetch a new version into the cache, but neither of those should have any impact on running processes.

**Comment by gregpalaci** [comment]
Thanks!
