### ISSUE TITLE
Volta Error: Could not download node@x.x.x

### ISSUE THREAD

**Issue by kevinreber** [volta-cli/volta#1339]
I tried install various versions of `node` using volta, but kept running into the `Error Message` I have below. Verified that my internet is working fine.

`package.json`
```
  "volta": {
    "node": "14.17.0",
    "yarn": "1.22.4",
  }
```

`volta list`
```
> volta list
⚡️ Currently active tools:

    Node: v14.17.0 (current @ /Users/kreber/Documents/code/common/
    package.json)
    Yarn: v1.22.4 (current @ /Users/kreber/Documents/code/common/
    package.json)
    Tool binaries available: NONE
```

`Error Message`
```
> volta install node@14.17.0                  
volta error: Could not download node@14.17.0
from http://volta-artifactory.corp.linkedin.com/node/distro/darwin/x64/14.17.0

Please verify your internet connection and ensure the correct version is specified.
Error details written to /Users/kreber/.volta/log/volta-error-2022-10-02_21_12_54.796.log
```

The volta log file shows that there is a `500` error
```
"volta" "install" "node@14.17.0"
Volta v1.0.8

Could not download node@14.17.0
from http://volta-artifactory.corp.linkedin.com/node/distro/darwin/x64/14.17.0

Please verify your internet connection and ensure the correct version is specified.

Error cause: HTTP failure (500 Internal Server Error)
```

When I visit the link in the Error Message(`http://volta-artifactory.corp.linkedin.com/node/distro/darwin/x64/14.17.0`) it directs me to a page that only shows `Could not determine Node Download URL`.

Is there something I'm possibly missing?

**Comment by charlespierce** [comment]
Hi @kevinreber, thanks for the question! `volta-artifactory` is an internal proxy for Node / npm / Yarn versions, so you likely will need to reach out to the internal tools team within LinkedIn that maintains that to figure out what is going wrong with the download URLs.
