### ISSUE TITLE
I have created a Linux arm64 prebuilt binary

### ISSUE THREAD

**Issue by FourLeafTec** [volta-cli/volta#1341]
I have created a [Linux arm64 prebuilt binary](https://github.com/MyneTop/volta) with self-hosted runner.

It tracks Volta's Releases weekly and builds  aarch-linux-gnu openssl-1.1 binaries.

**Comment by charlespierce** [comment]
This is awesome @FourLeafTec, thank you! I think with the migration of Volta to use Rustls, we should be able to create our own with less up-front work (and hopefully without a self-hosted runner). But until then, our users will definitely appreciate your pre-built binaries.

**Comment by chriskrycho** [comment]
Closing this as it's informative rather than an issue we should track—but we still deeply appreciate it!
