### ISSUE TITLE
Volta find not tar.gz on windows

### ISSUE THREAD

**Issue by zhfish** [volta-cli/volta#1343]
windows has 7z and zip, hasn't tar.gz
```
PS C:\Users\Administrator> volta install node@16
error: Could not download node@16.17.1
from https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/v16.17.0/node-v16.17.1-win-x64.tar.gz

Please verify your internet connection and ensure the correct version is specified.
```

**Comment by just-Bri** [comment]
Seeing the same issue this morning but only when running via GH Actions.
```bash
Run yarn install && npx playwright install firefox --with-deps
  yarn install && npx playwright install firefox --with-deps
  shell: /usr/bin/bash -e {0}
  env:
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.1.0/x64
Volta error: Could not download node@16.18.0
from https://nodejs.org/dist/v16.18.0/node-v16.18.0-linux-x64.tar.gz

Please verify your internet connection and ensure the correct version is specified.
Volta error: Error cause: HTTP failure (500 Internal Server Error)
Error: Process completed with exit code 1[2](https://github.com/CalthorpeAnalytics/uf-explorer/actions/runs/3275131977/jobs/5389581417#step:5:2)[6](https://github.com/CalthorpeAnalytics/uf-explorer/actions/runs/3275131977/jobs/5389581417#step:5:7).
```

Running `volta install node@16.18.0` locally works fine

**Comment by charlespierce** [comment]
Hi @zhfish, that's very odd! Are you using a custom `hooks.json` file that is setting the `.tar.gz` extension? By default Volta shouldn't be looking for tarballs on Windows, it should be explicitly looking for the `.zip` file.

@just-Bri That looks like a different issue, as Linux _does_ have tarball distributions. It appears that the download failed for some internal reason fetching from `nodejs.org`. Is it possible that failure was a one-off network issue?

**Comment by just-Bri** [comment]
> @just-Bri That looks like a different issue, as Linux _does_ have tarball distributions. It appears that the download failed for some internal reason fetching from `nodejs.org`. Is it possible that failure was a one-off network issue?

I ran it quite a few times, even tried node 16.17.0 and 16.18.0 and was getting the same error.
I've switched back over to actions/setup-node for now, will give it a shot later today or tomorrow.

**Comment by zhfish** [comment]
> 

looks like, it's a config wrong in my custom hooks.json
it setting .tar.gz extension

thanks
