### ISSUE TITLE
install_volta.sh fails to install older versions on linux

### ISSUE THREAD

**Issue by shem-caylent** [volta-cli/volta#1353]
>  Installing Volta version 1.0.8
>   Checking for existing Volta installation
>   Fetching archive for Linux, version 1.0.8
> curl: (22) The requested URL returned error: 404

When running the following on a linux amd64 docker container I get the preceeding error:
```sh
curl https://get.volta.sh | bash -s -- --version 1.0.8
```

It seems that updates to the install script are no longer picking the correct linux release for versions <1.1.0
The release packaging now uses a unified tar package for linux, but prior was split up.

**Comment by charlespierce** [comment]
Hi @shem-caylent, that's correct, Volta 1.1.0 changed the release artifacts, unifying the Linux one. I'll make a PR shortly to update the docs, but to install versions < 1.1.0, you'll need to use the old installer via:

```rust
curl https://raw.githubusercontent.com/volta-cli/volta/8f2074f423c65405dfba9858d9bcf393c38ffb45/dev/unix/volta-install.sh | bash -s -- --version 1.0.8
```

Out of curiosity, is there an issue with Volta 1.1.0 that makes you prefer installing 1.0.8?

**Comment by shem-caylent** [comment]
No, no issue so far, but we've been using 1.0.8 and I wasn't ready to update ci/cd things yet. Wanted to raise the issue so others were aware of it as well. I appreciate the link with the old installer for curl.

Thanks for the quick response!

**Comment by charlespierce** [comment]
Opened https://github.com/volta-cli/website/pull/122 to update the `Installing Old Versions` sections of our docs to be accurate with the change in Volta 1.1.0

**Comment by charlespierce** [comment]
This should be resolved by the updated docs in the PR above.
