### ISSUE TITLE
Volta Installation Fails intermittently with 502

### ISSUE THREAD

**Issue by brunoargolo** [volta-cli/volta#1378]
Running the install command for volta has started failing on the last few days intermittently.

command below is  run from 4 different containers (in parallel) from AWS code build, often one of the containers will fail with a 502:

curl https://get.volta.sh | bash
=================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10930  100 10930    0     0  38431      0 --:--:-- --:--:-- --:--:-- 38485
Installing latest version of Volta (1.1.0)
    Checking for existing Volta installation
    Fetching archive for Linux, version 1.1.0
#=#=#                                                                         
curl: (22) The requested URL returned error: 502
Error: Could not download Volta version '1.1.0'. See https://github.com/volta-cli/volta/releases for a list of available releases
=================================

It seems to fails on the download of the binary on line below of the shell script: 

curl --progress-bar --show-error --location --fail "$archive_url" --output "$download_file" --write-out "$download_file"

If there is any workaround available I'd love to hear it.

**Comment by brunoargolo** [comment]
It seems like this is downloaded from git hub releases and not really within the power of the maintainers to act on.
I guess I'll either keep volta only on workstations and avoid using it on the build server or keep the binary somewhere on my AWS account.

**Comment by brunoargolo** [comment]
as per above.

**Comment by nansouille** [comment]
hello
same issue here :(
Any fix ?
