### ISSUE TITLE
Volta should create a shim for `yarnpkg`

### ISSUE THREAD

**Issue by yume-chan** [volta-cli/volta#1391]
Yarn actually has two bin files:

![image](https://user-images.githubusercontent.com/1330321/204769114-e5abf7df-2bdd-4caa-80d5-2a9c38b8f01a.png)

And some tools are invoking `yarnpkg` instead: https://github.com/expo/expo-cli/issues/1455

So volta should also create a shim for `yarnpkg` to maintain compatibility.

**Comment by charlespierce** [comment]
Thanks for reporting @yume-chan! Interestingly, it looks like that's been the case since 2016 🤯 I don't know how we missed that or never got a report about it until now! Will definitely look to include that shim as well.

**Comment by migs35323** [comment]
whats the difference between the 2 binaries? (yarn vs yarnpkg)
i noticed that volta let me install both

**Comment by migs35323** [comment]
whats the difference between the 2 binaries? (yarn vs yarnpkg)
i noticed that volta let me install both

**Comment by aleqsio** [comment]
I've just now bumped into this issue and can confirm this is quite a problem when using volta together with expo – symlinks don't work with `Volta error: Could not find executable "yarnpkg"`, installing yarnpkg is pointing to a super old package, so the only way that I found is to remove volta entirely.

**Comment by 4lgn** [comment]
+1, installing packages with `npx expo install <package>` is not possible when using volta. Given the popularity of `expo` along with all their documentation using such installation of packages to ensure compatibility, this is quite a pain.

**Comment by alitnk** [comment]
Expo [uses `yarnpkg`](https://github.com/expo/expo/blob/cf6faf4712520cd5260c563c01b73dec3fd68c1e/packages/%40expo/package-manager/src/node/YarnPackageManager.ts#L8C28-L8C28). I'm getting errors as well. The shim would be great!

**Comment by elwayman02** [comment]
It looks like this is now also impacting the browserslist/update-db package, which switched to use `yarnpkg` a month ago: https://github.com/browserslist/update-db/issues/24

See also: https://github.com/browserslist/update-db/issues/27

**Comment by elwayman02** [comment]
@charlespierce any updates on whether we'll be able to get a fix for this in Volta?

**Comment by chriskrycho** [comment]
Should be reasonably straightforward, I think; we just need to finish clearing the deck for a lot of small infrastructural issues that have piled up and from which we are slowly digging our way out at present. (Also, if you wanted to learn some Rust… 😏)
