### ISSUE TITLE
Cannot run Angular's ng in Volta for Windows after installing

### ISSUE THREAD

**Issue by danim-hub** [volta-cli/volta#1392]
I am running Volta but Angular's "ng" command it is not working from the command line
I installed npm 7 and Angular 12 with 

```
npm install -g npm@7
npm install -g @angular/cli@12.0.5

```
I found if I run `volta setup` after that, it starts working, but I think it should start working after npm install -g @angular/cli, and it should not require to run volta commands for it to work.  I like volta very much but I dont want to make my builds dependent on running volta commands, or should I?

This is the output of volta list -c

```
C:\dev\sif\modeler\modeler-app>volta list -c       
⚡️ Currently active tools:

    Node: v14.15.5 (current @ C:\dev\sif\modeler\modeler-app\package.json)
    npm: v7.24.2 (current @ C:\dev\sif\modeler\modeler-app\package.json)
    Tool binaries available:
        ng (current @ C:\dev\sif\modeler\modeler-app\package.json)

See options for more detailed reports by running `volta list --help`.
```

And this is error I get when trying to run ng

```
C:\dev\sif\modeler\modeler-app>ng
'ng' is not recognized as an internal or external command,
operable program or batch file.

```
I don't see the "ng" binary in Program Files:
```
C:\dev\sif\modeler\modeler-app>dir "\Program Files\Volta"
 Volume in drive C has no label.
 Volume Serial Number is D450-9A69

 Directory of C:\Program Files\Volta

12/02/2022  01:25 AM    <DIR>          .
12/02/2022  01:25 AM    <DIR>          ..
09/28/2022  11:17 PM         5,714,944 node.exe
09/28/2022  11:07 PM                28 npm.cmd
09/28/2022  11:17 PM         5,714,944 npm.exe
09/28/2022  11:07 PM                28 npx.cmd
09/28/2022  11:17 PM         5,714,944 npx.exe
09/28/2022  11:17 PM         3,960,320 volta-migrate.exe
09/28/2022  11:17 PM         5,714,944 volta-shim.exe
09/28/2022  11:17 PM         6,586,368 volta.exe
09/28/2022  11:07 PM                28 yarn.cmd
09/28/2022  11:17 PM         5,714,944 yarn.exe

```

**Comment by charlespierce** [comment]
Hi @danim-hub, thanks for the question! I think the core issue here is that Volta on Windows has 2 parts to the installation process:

1. Install the core binaries (volta, node, npm, npx, and yarn) in the `Program Files` directory and set up the system environment variables to make sure that directory is on the `Path`
2. Set up the user environment variables to also include Volta's working directory (by default `%LOCALAPPDATA%\Volta`) on the Path for the current user. This makes sure that any shims that are created by `volta install <package>` (or equivalently `npm i -g <package>`) are also available on the `Path` for the current user.

This second step appears to be what is missing. When you install Volta with the MSI installer, it should take care of that for the current user. However, if there are other users on the machine that want to use Volta, they will need to do that step individually. That's what `volta setup` will do, so it likely needs to be called for each new user on a given machine. It should be a one-and-done command, however, you definitely shouldn't need to call `volta setup` multiple times for the same user.

Does that answer your question? Happy to answer any other questions or help debug a bit if it's still not working as expected.

**Comment by danim-hub** [comment]
Hi Charles, thanks for the prompt reply.

I did both steps with the same user.   What could be affecting is that I
was running the application from vscode. I actually closed and reopened
vscode, but it didn't work until I ran the volta setup command.

Thanks for your help and insights.

**Comment by charlespierce** [comment]
Interesting! When running it from VS Code, were you doing it through the embedded terminal, or through an extension? Also, do you need to run `volta setup` _each_ time you close and reopen VS Code, or was it a one-off that fixed things going forward?

**Comment by danim-hub** [comment]
Good question.
I using the embedded terminal.
I ran volta setup only once and it started working since that

**Comment by charlespierce** [comment]
Ah, that's interesting! It may be the case that VS Code's embedded terminal had a cached version of the `Path` value that didn't update until you ran `volta setup`. I know I've seen issues in the past where the embedded VS Code terminal doesn't immediately pick up the changes made to the system with installing Volta. If we can pin down a reproducible case, we may be able to either actually improve the experience or at least more effectively message the fix.

Good to hear it's working after that fix, however, and sorry that it wasn't as seamless an installation process as it could have been!
