### ISSUE TITLE
Dismiss the use of symlinks on Windows

### ISSUE THREAD

**Issue by rcsilva83** [volta-cli/volta#1397]
I think it would be a huge security enhancement if Volta didn't make use of symlinks on Windows. [Microsoft discourages the use of symlinks](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links#vulnerability), for security reasons, and Developer Mode (which is recommended by Volta) enables much more than just symlinks, many of them are undesirable.

It looks like the main Volta logic is implemented by code and the symlink could be easily replaced by a call to `volta-shim`. Actually, I made a test replacing `rimraf`'s symlink by a renamed copy of `volta-shim` and it worked.

If this issue makes sense for the Volta team, I can start working on a PR with this implementation.

PS: this idea came from #964

**Comment by rcsilva83** [comment]
As discussed on [Discord](https://discord.com/channels/413753499835301908/413753499835301917/1050591393258688563), an alternative to symlink on Windows already used on projects like Scoop, pnpm and fnm are **NTFS juntions**. The main drawback of NTFS junctions is it can only  be used for directory and it would be necessary another solution for files.

**Comment by supuwoerc** [comment]
> I think it would be a huge security enhancement if Volta didn't make use of symlinks on Windows. [Microsoft discourages the use of symlinks](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links#vulnerability), for security reasons, and Developer Mode (which is recommended by Volta) enables much more than just symlinks, many of them are undesirable.
> 
> It looks like the main Volta logic is implemented by code and the symlink could be easily replaced by a call to `volta-shim`. Actually, I made a test replacing `rimraf`'s symlink by a renamed copy of `volta-shim` and it worked.
> 
> If this issue makes sense for the Volta team, I can start working on a PR with this implementation.
> 
> PS: this idea came from #964

A good idea. I also encountered the unavailability of Volta caused by permission problems in the company's machine. I guess it is due to the lack of defects

**Comment by supuwoerc** [comment]
> I think it would be a huge security enhancement if Volta didn't make use of symlinks on Windows. [Microsoft discourages the use of symlinks](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links#vulnerability), for security reasons, and Developer Mode (which is recommended by Volta) enables much more than just symlinks, many of them are undesirable.
> 
> It looks like the main Volta logic is implemented by code and the symlink could be easily replaced by a call to `volta-shim`. Actually, I made a test replacing `rimraf`'s symlink by a renamed copy of `volta-shim` and it worked.
> 
> If this issue makes sense for the Volta team, I can start working on a PR with this implementation.
> 
> PS: this idea came from #964

That's a good idea. I also had a problem with Volta not being available due to permission issues on the company machine. I think it's due to lack of access
