### ISSUE TITLE
Unable to download node through a private cache that uses self-signed certificate

### ISSUE THREAD

**Issue by edvinerikson** [volta-cli/volta#1399]
Due to internal security rules I need to download node through a private cache. However this cache is using a certificate signed by an internal CA.

<details>
<summary>Whenever I try to download through this cache I get this error</summary>  

```
"volta" "install" "node@18"
Volta v1.1.0

Could not download node@18.12.1
from https://somehost/api/npm/npm-registry.npmjs.org/node-linux-x64/-/node-linux-x64-v18.12.1.tgz

Please verify your internet connection and ensure the correct version is specified.

Error cause: Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Error cause: Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```
</details>

However when I run it through curl it works as it should. Is it possible to make volta read the certificates installed on the computer?

**Comment by charlespierce** [comment]
Apologies for the delay on this, but Volta 1.1.1 was just released which should resolve this issue by using the appropriate native certificates.

**Comment by edvinerikson** [comment]
Awesome thank you!

ons 25 jan. 2023 kl. 02:38 skrev Charles Pierce ***@***.***>:
