### ISSUE TITLE
yarn create react-app and yarn start failed

### ISSUE THREAD

**Issue by rjiang9** [volta-cli/volta#1403]
Envs: 
1) Mac M1
2) volta 1.1.0
3) yarn 3.2.1

`which yarn` returns `.~/volta/bin/yarn`

Create an react app:

`yarn create react-app mydemo`

`cd mydemo`

`yarn start`

And got this errro:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/7293118/207109140-dcab3f4b-ae22-4268-a3b3-1f23a1cea716.png">

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///Users/rayjiang/projects/ruby-yarn/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:393:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:839:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:7) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}
t 
Node.js v19.2.0
```

I downgraded `volta pin node@18` (node@16) does NOT help.

But if create the app using `npx create-react-app mydemo`, `npm start` works just fine. 

Thanks in advance for any advice.

**Comment by charlespierce** [comment]
Hi @rjiang9, thanks for the report! It looks like this is actually an issue with that specific Yarn version and its interaction with newer Node releases. See https://github.com/yarnpkg/berry/issues/4778

From that, it looks like upgrading to Yarn 3.2.2 or newer (and potentially deleting / regenerating `.pnp.loader.mjs`) should resolve the issue.

**Comment by rjiang9** [comment]
> Hi @rjiang9, thanks for the report! It looks like this is actually an issue with that specific Yarn version and its interaction with newer Node releases. See [yarnpkg/berry#4778](https://github.com/yarnpkg/berry/issues/4778)
> 
> From that, it looks like upgrading to Yarn 3.2.2 or newer (and potentially deleting / regenerating `.pnp.loader.mjs`) should resolve the issue.

Thank you @charlespierce . Upgrading yarn to v3.2.2 and all good now. 

For anybody who stump on this post: to upgrade `yarn`, just do `yarn set version 3.2.2`
