### ISSUE TITLE
Cannot run in webstrom?

### ISSUE THREAD

**Issue by takegine** [volta-cli/volta#1405]
Cannot find 'node interpreter' and 'package manager' in webstrom
i cant run 'volta -v' or 'node -v' in webstrom, but ok in vscode or power shell.
```bash
volta : 无法将“volta”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1                                                                    
+ volta -v                                                                               
+ ~~~~~                                                                                  
    + CategoryInfo          : ObjectNotFound: (volta:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by charlespierce** [comment]
Hi @takegine, Volta should work just fine from anywhere that obeys the `Path` environment variable. I'm not directly familiar with WebStorm, but I believe they may have made some changes to accommodate Volta and similar tools, so it may be that you need to set some custom settings to get it to work.

Are you running `node` from a shell within WebStorm? Or is it launching it directly?

**Comment by takegine** [comment]
The computer needs to be restarted

**Comment by takegine** [comment]
> Hi @takegine, Volta should work just fine from anywhere that obeys the `Path` environment variable. I'm not directly familiar with WebStorm, but I believe they may have made some changes to accommodate Volta and similar tools, so it may be that you need to set some custom settings to get it to work.
> 
> Are you running `node` from a shell within WebStorm? Or is it launching it directly?

thanks alot. Its working today
