### ISSUE TITLE
Support npm packages starting with version 0

### ISSUE THREAD

**Issue by catlair** [volta-cli/volta#1426]
Sorry, I can't speak English.

The following error occurs when `0.23.123` is installed. The package is actually released as `0.23.0123`.

```
"npm" "install" "@catlair/bilitools@0.23.123" "-g"
Volta v1.0.8

Could not parse package.json manifest for @catlair/bilitools

Please ensure the package includes a valid manifest file.

Error cause: encountered unexpected token: AlphaNumeric("0123") at line 3 column 24

```

Works on npm but does not work on volta npm

**Comment by ljharb** [comment]
`0.23.0123` is not valid semver. The package should publish a fixed version.

**Comment by catlair** [comment]
> `0.23.0123` is not valid semver. The package should publish a fixed version.

I agree with your statement and have already done so. At the same time, I think Volta should be consistent with the behavior of npm.

**Comment by charlespierce** [comment]
@catlair What does npm do in this case? Does it truncate the `0` or is it an issue of a poor error message?

**Comment by catlair** [comment]
> @catlair What does npm do in this case? Does it truncate the `0` or is it an issue of a poor error message?

I'm sorry I didn't see the email until now.

`1.2.011 -> 1.2.11`
