### ISSUE TITLE
Volta 1.1.1 Windows Not Download Node

### ISSUE THREAD

**Issue by D7EGPS** [volta-cli/volta#1435]
![image](https://user-images.githubusercontent.com/88301232/215598242-1b9c43a3-0f5e-4ccd-8c97-c1cc6bef7fa2.png)

I am facing an issue while using the latest version (1.1.1) of the Volta JS app to manage Node versions. I am unable to download Node in this version, while I am able to download other packages such as npm and yarn. The error message I receive is related to network problems or insufficient storage permissions. This issue is not present in version 1.1.0 in Windows.

**Comment by charlespierce** [comment]
Hi @D7EGPS, thanks for reporting! That's concerning for sure. Can you share the contents of the log file mentioned at the bottom of the error message? There may not be much useful information, but it hopefully can point us in the right direction.

The main difference for fetching operations between Volta 1.1.1 and Volta 1.1.0 is that the latest release is updated to use the native store of certificates from the machine, rather than a more compressed in-built one. Is it possible your machine has native certificates that don't work for nodejs.org? That seems unlikely since it would also break a whole bunch of other things, but just out of curiosity.

**Comment by ivanmauricio** [comment]
I'm getting a similar error when trying to run a command that uses `volta` on an app I've deployed with `Fly.io`. This command was working fine a few days ago which makes me think it's do with the new volta version. Here's the full error message

```
Volta v1.1.1

Could not download node@18.10.0
from https://nodejs.org/dist/v18.10.0/node-v18.10.0-linux-x64.tar.gz

Please verify your internet connection and ensure the correct version is specified.

Error cause: Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Error cause: Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

I've also posted [this question on Fly's forum](https://community.fly.io/t/cant-run-npm-command-on-vm-results-in-volta-error-could-not-download-node/10482)

**Comment by D7EGPS** [comment]
@charlespierce It seems to be working now, it was probably an issue with the certificates or something related, as I reinstalled the operating system, Windows 10 (using the same ISO image), and now it's functioning properly. I recall having trouble downloading Node at the time. Thank you!
![image](https://user-images.githubusercontent.com/88301232/216231488-9e88ec2b-3e7f-4de8-a19c-ee775efe46ee.png)

**Comment by faern** [comment]
We just ran into the same issue it seems. Both `node` and `npm` yield this error in the log:

```
"C:\\Program Files\\Volta\\volta.exe" "install" "node"
Volta v1.1.1

Could not download Node version registry
from https://nodejs.org/dist/index.json

Please verify your internet connection.

Error cause: Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

This is on a newly installed Windows Server 2022 virtual machine. For now we downgraded Volta to 1.0.8 and that fixed the issue. We currently don't have the time to reinstall the entire machine just for this, so can't say if that fixes it or not. But seems to be a bug with Volta?
