### ISSUE TITLE
`volta install yarn` installs Yarn 4.x RC instead of Yarn 3

### ISSUE THREAD

**Issue by felipecrs** [volta-cli/volta#1443]
Yarn 4 wasn't yet released to stable. Should not Volta install version 3?

**Comment by charlespierce** [comment]
Hi @felipecrs, great question! Volta fetches Yarn information from the npm registry. For Yarn 3+, we use this package, which was explicitly created by Yarn for distributing the CLI: https://www.npmjs.com/package/@yarnpkg/cli-dist?activeTab=versions

As you can see from that page, the RC version is tagged as `latest`, which is ultimately why Volta picks it up when installing without an explicit version. There isn't a ton of extra information about the versions we could use to pick a more appropriate version, possibly a way forward would be to reach out to the Yarn team and ask them to only update the latest tag for stable versions.

**Comment by felipecrs** [comment]
There we go:

- https://github.com/yarnpkg/berry/issues/5251

**Comment by chriskrycho** [comment]
Going to go ahead and close this since it's an upstream issue – thanks again, @felipecrs!
