### ISSUE TITLE
Can I config disturl in .npmrc to change node download url?

### ISSUE THREAD

**Issue by santong** [volta-cli/volta#1449]
Because of the network problem. Link https://nodejs.org/dist always timeout in my country.

**Comment by Lingtin** [comment]
Nodejs.org is not accessible in my country.I need to change the access.

**Comment by dprevost-LMI** [comment]
Can anyone answer or provide a solution?

**Comment by chriskrycho** [comment]
You can use [Volta hooks](https://docs.volta.sh/advanced/hooks) to manage which registry to use.
