### ISSUE TITLE
How to install @bazel/bazelisk  using volta?

### ISSUE THREAD

**Issue by catherinekennedy** [volta-cli/volta#1456]
When installing @bazel/bazelisk  using volta I got this error .How to solve this error?

![image](https://user-images.githubusercontent.com/67736813/221833357-12366d88-e1bb-49be-8e7f-5641267bbb8a.png)

**Comment by chriskrycho** [comment]
Hi @catherinekennedy – sorry for the long delay in response here. If you're still having this issue, can you include the `.log` file listed when that happens so we can see what the details are?

**Comment by catherinekennedy** [comment]
Solved this issue by switching on the developer mode
