### ISSUE TITLE
Maybe volta is not so good.

### ISSUE THREAD

**Issue by vaynevayne** [volta-cli/volta#1514]
Both volta and nvm bind node to npm, and so do installation and uninstall, but yarn and pnpm just use the same location to store.

so Search yarn global remove in the search engine, you will find a lot of issue, a lot of people encounter these difficult problems

I think it is very simple to reduce these errors: node and npm and yarn pnpm packages, do not do any association, globally specify a unique package 

For example, there is a new tool called uniquo( I expect someone to come up with something like this. ), Uniquo does not do any internal relationship, the only function is to help you switch the yarn version

The simpler the better.

```jsx
uniquo switch node@14
uniquo swicth yarn@14
uniquo swicth pnpm@14
```

```jsx
// my-project
yarn --version // 14.x
uniquo swicth yarn@15
uniquo pin yarn 
package.js {
uniquo:{
yarn: '15.x'
}
}
yarn --version // 15.x
```

switch 命令做的事情很简单

```
yarn --version // 14
yarn global list  // vite@3 , typescript@3, pnpm@3

uniquo swicth yarn@15
// Perform the following actions internally
uniquo record vite@3 , typescript@3, pnpm@3
yarn global remove vite typescript pnpm
uniquo remove yarn
uniquo add yarn@15
yarn global add vite@3  typescript@3 pnpm@3

```

It will be uninstalled and installed every time the version is switched. Although the performance is very slow, it can guarantee that it is correct. For example, if you switch from node14's project to node15, he will uninstall node14 and then install node15. I think the error of changing the installation time for yarn global remove is worth it.

**Comment by mufasa71** [comment]
Was this open by ChatGPT? 😄  If not can you create steps to reproduce the issue?

**Comment by chriskrycho** [comment]
There are lots of alternative designs in the space, and we welcome folks exploring the tradeoffs that go with them! Going to go ahead and close this as not actionable, and good luck with whatever tool you land on!
