### ISSUE TITLE
Volta is not removing old env after uninstalling volta

### ISSUE THREAD

**Issue by elamandeep** [volta-cli/volta#1518]
I uninstalled Volta. Then installed Volta again. Still, i can see my old node env. I even try to uninstall them. But still not working
Also I'm unable to remove yarn .

![image](https://github.com/volta-cli/volta/assets/68345524/f8aa67f3-d436-4aec-94dc-976006e9bd3f)

when i pin old env it's not working.
![image](https://github.com/volta-cli/volta/assets/68345524/b114fbc1-605f-4e4a-94fa-1233980b3fb8)

Need urgent help

**Comment by chriskrycho** [comment]
Hi @elamandeep, sorry about the long delay. It's not clear to me from your write-up exactly what you mean by "env" or what your exact expectations here were that Volta was not accomplishing. Can you add further detail? Did you figure out how to get things worked out? Happy to help if we're able to at this point!

**Comment by elamandeep** [comment]
@chriskrycho But I'm not longer a window user. In linux, i use asdf vm.

**Comment by chriskrycho** [comment]
@elamandeep glad to hear you found something that works for you (even if it's not Volta!). Closing this out accordingly.
