### ISSUE TITLE
Support custom node mirror

### ISSUE THREAD

**Issue by southorange0929** [volta-cli/volta#1522]
Just like `nvm`, it can replace node mirror with `NVM_NODEJS_ORG_MIRROR`
```shell
export NVM_NODEJS_ORG_MIRROR='' 
```
Then nvm will install node with `NVM_NODEJS_ORG_MIRROR`

**Comment by niaodan2b** [comment]
https://github.com/volta-cli/volta/issues/1524#issuecomment-1612358621
