### ISSUE TITLE
How do I set a node mirror source

### ISSUE THREAD

**Issue by xiaoLangtou** [volta-cli/volta#1524]
In my region of China, when using Volta and setting up the Node.js image repository, how can I do it?

**Comment by niaodan2b** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/nodejs-release/   there's guide for volta:

Create  `%LOCALAPPDATA%\Volta\hooks.json`(windows) / `~/.volta/hooks.json`(Linux/MacOS) 
Paste the following content:
```
{
    "node": {
        "index": {
            "template": "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/index.json"
        },
        "distro": {
            "template": "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/v{{version}}/node-v{{version}}-{{os}}-{{arch}}.tar.gz"
        }
    }
}
```
And save the file.
(form your own template if you use other mirrors)

**Comment by southorange0929** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/help/nodejs-release/ there's guide for volta:
> 
> Create `%LOCALAPPDATA%\Volta\hooks.json`(windows) / `~/.volta/hooks.json`(Linux/MacOS) Paste the following content:
> 
> ```
> {
>     "node": {
>         "index": {
>             "template": "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/index.json"
>         },
>         "distro": {
>             "template": "https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/v{{version}}/node-v{{version}}-{{os}}-{{arch}}.tar.gz"
>         }
>     }
> }
> ```
> 
> And save the file. (form your own template if you use other mirrors)

It's useful,but i got another error with M1. It can't fallback x64 arch with older version, for example v14.Any suggestions?

**Comment by xiaoLangtou** [comment]
Thank you very much, you have found the corresponding hook configuration in the documentation

**Comment by delicacyyy** [comment]
![image](https://github.com/volta-cli/volta/assets/11476249/9fd91ca1-89c4-4a6d-970a-f0b3e143dc11)
why it prompts "No custom hooks found"?

**Comment by niaodan2b** [comment]
> why it prompts "No custom hooks found"?

Scoop installed volta in different location.
Try putting hooks.json under same folder as volta.lock, in your case `...\scoop\apps\volta\current\appdata\hooks.json`
