### ISSUE TITLE
have a command that lists the versions of node.js installed on your computer

### ISSUE THREAD

**Issue by Marcelin97** [volta-cli/volta#1535]
a bit like on the principle of nvm or n under linux with a command that displays the versions of node.js installed on his computer. Can change version in its terminal in addition to or in addition to the pin command which adds a node to the package.json.

**Comment by Icaruk** [comment]
`volta ls node` does the job?

**Comment by josealvaradoo** [comment]
```
volta list node
```
although only supports the node images installed into the dir`.volta`

**Comment by chriskrycho** [comment]
Closing this as “answered”; Volta will definitely never try to find and list *all* Node versions, only the ones it answers, but as described above, `volta list node` will do what you want!
