### ISSUE TITLE
Make volta part of nixpkgs

### ISSUE THREAD

**Issue by izelnakri** [volta-cli/volta#1556]
I've been using volta happily for several years at this point. However lately Im moving my entire system to nix/make everything nix-based via home-manager. I noticed this tool is particularly hard to set up because it is not on [nixpkgs](https://github.com/NixOS/nixpkgs). Could you please add it here? I don't want to add the $PATH inclusion in my shell profile(and fetch volta) each time I do `home-manager switch` or install.

Also perhaps eventually we can make this tool integrate better with nix store as well by putting global npm packages in the nix store, make nix a direct dependency of volta instead of all the other dependencies & their linking which had been an issue in the past.

I've already seen this issue but it isnt asking for `nixpkgs` inclusion for easy installation so I'm creating this issue: https://github.com/volta-cli/volta/issues/867

**Comment by nicknovitski** [comment]
Volta is in nixpkgs now.

**Comment by chriskrycho** [comment]
Thanks for the issue, @nicknovitski! Closing this accordingly.
