### ISSUE TITLE
Volta install yarn@4.0.0-rc.53 uses 3.6.4

### ISSUE THREAD

**Issue by jinder** [volta-cli/volta#1557]
New volta installation, with following pinned version in package.json:

    Node: v20.8.1 (default)
    Yarn: v4.0.0-rc.53 (default)
    Tool binaries available: NONE

Running "yarn -v" always returns 3.6.4

Navigating to "~\scoop\apps\volta\current\appdata\tools\image\yarn\4.0.0-rc.53\bin" and running yarn -v returns the correct version.

"yarn" in powershell is pointing to "~\scoop\apps\volta\current\appdata\bin\yarn.exe" which for some reason return 3.6.4

**Comment by jinder** [comment]
If I run "yarn set version 4.0.0-rc.53" then it will switch to the correct version.

**Comment by charlespierce** [comment]
@jinder That was going to be my suggestion / follow-up! Yarn has its own local package version pinning, which takes effect once Yarn itself starts—Volta only manages starting a specific version, so Yarn's delegation will always win.

**Comment by chriskrycho** [comment]
Since that seems to have been the answer, I am closing this accordingly! Very confusing indeed!
