### ISSUE TITLE
Setting Node version based on specific dependency

### ISSUE THREAD

**Issue by TheJaredWilcurt** [volta-cli/volta#1561]
I do a bunch of stuff with NW.js. It's basically a modified chromium browser with Node.js built-in to it. It is used to make desktop apps.

It is a best practice to have your globally installed Node.js version match the version built in to NW.js so that when you `npm install`, it gets the correct files, or builds for the correct Node version. So the dependencies run inside NW.js correctly.

A bare-minimum desktop app for NW.js looks like this:

```js
{
  "name": "my-app",
  "main": "index.html"
  "scripts": {
    "start": "nw ."
  },
  "dependencies": {
    "nw": "0.81.0-sdk"
  },
  "volta": {
    "node": "20.7.0"
  }
}
```

Since NW.js v0.81.0 has Node.js v20.7.0 built in, we need that matching number for Volta.

Currently I have to manually consult the [versions.json](https://nwjs.io/versions.json) file to find the version of NW.js I am using and map that to the version of Node it ships with, and then manually pin it in the `package.json`.

It's not a *huge* deal, but when trying to introduce new people to NW.js, it would be cool if there was some way to link these two together, to have one less step when getting started. One less thing to manually maintain. 

My ideal scenario would be something like:

```js
  "dependencies": {
    "nw": "0.81.0-sdk"
  },
  "volta": {
    "node": "match nw"
  }
```

So as you update the `nw` dependency, Volta just automatically updates the a Node version. But that shifts the burden to Volta to figure out how to map that version. Maybe if that dependency had a `volta` object in its `node_modules/nw/package.json` that could be a more generic way to do this. Then any project could pin Node to be based on a setting in any dependency. Not sure if the volta object is included in the `package.json` that gets published to npm though.

Any other ideas on ways to simplify or automate this?

**Comment by TheJaredWilcurt** [comment]
I created a library to solve this issue for the NW.js community specifically.

* https://github.com/nwutils/base-volta-off-of-nwjs

However, I still think being able to base your Volta version off of another package's volta version would be useful in a general sense.

**Comment by chriskrycho** [comment]
@TheJaredWilcurt I *think* you could repurpose [Volta's support for workspaces](https://docs.volta.sh/advanced/workspaces) this way:

```json
{
  "volta": {
    "extends": "./node_modules/nw/package.json"
  }
}
```

It would, in principle, be possible to make that understand package layout so you could use "absolute" paths, but that does not work for today. Also note that this is very much coupled to the details of `node_modules` layout! So that is not exactly a “supported” path as a *workaround*.
