### ISSUE TITLE
Help text for `volta uninstall --help` incorrectly states `node` versions can be uninstalled

### ISSUE THREAD

**Issue by nifr** [volta-cli/volta#1563]
Steps to reproduce:

```bash
volta uninstall --help
```

Shows the following: ( `node` is the first suggested tool that can be uninstalled )

```
[..]
ARGS:
    <tool>    The tool to uninstall, e.g. `node`, `npm`, `yarn`, or <package>
```

If we try to uninstall a `node` version `volta` shows an error.

```bash
volta uninstall node
```

Output/Error:

```
error: Uninstalling node is not supported yet.
``` 

If we attempt to uninstall a concrete `node` version `volta` shows a different error.

```bash
volta uninstall node@21.0.0
```

Output/Error:

```
warning:  No package 'node@21.0.0' found to uninstall
```

---

**Question**: Is it still planned to implement uninstallation of `node` versions installed by `volta`?
**Question**: Is it possible to uninstall a node version installed with `volta` manually (for now)? If yes - how?

**Comment by mauudev** [comment]
any updates on this? I'm also playing around with this and can't unistall a node version :/

**Comment by chriskrycho** [comment]
It's maintained, but we've all been busy. This one is a case where we thought we would implement that feature and then… have not yet been able to! See #327. A welcome change here would be just updating the help text via the comment [here](https://github.com/volta-cli/volta/blob/86c2818f27edf36df521a2468d2022678d019404/src/command/uninstall.rs#L12) – we can get that merged very quickly. (Or one of us might hopefully also be able to get there, but we're *much* likelier to merge a PR than to open it ourselves at the moment.)

**Comment by MrChocolatine** [comment]
@nifr 
> Question: Is it possible to uninstall a node version installed with volta manually (for now)? If yes - how?

@mauudev 
> any updates on this? I'm also playing around with this and can't unistall a node version :/

To manually uninstall a version you need to delete:
- `$HOME/.volta/tools/image/< TOOL >/< VERSION >`
- `$HOME/.volta/tools/inventory/< TOOL >/< VERSION >`

For instance, say I execute:

```
volta install node@16
```

to uninstall this version I would need to manually delete:
- `$HOME/.volta/tools/image/node/16.20.2`
- `$HOME/.volta/tools/inventory/node/node-v16.20.2-darwin-arm64.tar.gz`
- `$HOME/.volta/tools/inventory/node/node-v16.20.2-npm`

**Comment by pkc918** [comment]
I have the same problem.

If I need to manually delete files, what is the purpose of `uninstall`? 😫
