### ISSUE TITLE
Temporarily Override Volta's Default Behavior to Favor Global Packages Over Local Ones

### ISSUE THREAD

**Issue by weleo** [volta-cli/volta#1566]
I appreciate Volta's auto-use of locally installed packages from the node_modules directory, negating the need for command modifications. 

However, I've encountered a situation where I prefer using a globally installed package over the local version. Is there a way to temporarily override Volta's default behavior of using locally installed packages?

**Comment by chriskrycho** [comment]
Sorry for the delayed reply, @weleo! I believe you should be able to accomplish that using [the `volta run` command](https://docs.volta.sh/reference/run), which was designed for exactly this scenario!
