### ISSUE TITLE
Volta does not switch global packages on directory change

### ISSUE THREAD

**Issue by sixclones** [volta-cli/volta#1592]
So quoting the documentation, it says

> For example, installing the Typescript package will add the compiler executable—tsc— to your toolchain:
> 
> ```bash
> npm install --global typescript
> ```
> 
> Depending on the project you’re in, this executable will switch to the project’s chosen version of TypeScript:
> 
> ```bash
> cd /path/to/project-using-typescript-3.9.4
> tsc --version # 3.9.4
> 
> cd /path/to/project-using-typescript-4.1.5
> tsc --version # 4.1.5
> ```

But if I do that in my codebase, it doesn't work.

```bash
roch•apps/project-1/sanity» npm i -g @sanity/cli@2.35.0 
added 1 package in 2s

roch•apps/project-1/sanity» sanity -v
@sanity/cli version 2.35.0

roch•apps/project-1/sanity» cd ..

roch•~/apps/project-1» sanity -v
@sanity/cli version 2.35.0

roch•~/apps/project-1» cd ..

roch•~/apps» npm i -g @sanity/cli@latest
added 79 packages in 6s

roch•~/apps» sanity -v
@sanity/cli version 3.21.3

roch•~/apps» cd project-1/sanity

roch•apps/project-1/sanity(staging)» sanity -v
@sanity/cli version 3.21.3
```

It seems that I'm missing something but the docs says Volta is normally automatically switching versions based on the directory I am current located at.

> Because Volta’s toolchain always keeps track of where you are, it makes sure the tools you use always respect the settings of the project you’re working on. This means you don’t have to worry about changing the state of your installed software when switching between projects.

## Versions

```
volta 1.1.1
node 20.10.0
npm 10.2.3
```

**Comment by chriskrycho** [comment]
That is not what the docs are trying to say, but I totally understand why you are reading them that way! What the docs are trying to say is: you can install a “global” version of a tool like TypeScript, and any time you are somewhere on your system which does *not* have TypeScript installed, it will use the globally installed version, but when in a project which *does* have TypeScript installed, it will use that project’s version instead. In other words, exactly the behavior you are seeing!

So, to be extra clear:

- There will only ever be a single copy of a given global (or “user default”) installation of a package. When you ran `npm install -g typescript` again with a different version, it *replaced* the previous global installation—just like it would with a normal `npm install -g`, but with Volta’s extra isolation.

- When you have installed both a global and a package-local version of a given tool, Volta will use the package-local version. That way, the version you get in a project is always the version *from the project*. It would be annoying if installing a global version made it so the version in your project did not work!

- Volta does *not* support having a per-directory version of a given package or tool apart from configuring it explicitly with the `volta` key (for Node and package managers) or adding it to your dependencies (for packages) in `package.json`.

Hopefully that clears things up a bit! If you have thoughts on how we could word that bit of our documentation better, we would welcome it—and feel free to open a PR to help fix it, too!

**Comment by sixclones** [comment]
Oh I see, it totally makes sense now, thanks for the detailed answer.

I think that what's you're explaining is in fact contained in this sentence: "Volta respects the configuration of the project you’re in". But I think that adding a precision over what "the configuration of the project" is might greatly help to make docs clearer.
For example, simply adding "the configuration of the project (e.g. the `package.json` file of the current directory)" might easily help.

Also I think that what you explained to me in your comment covers the whole thing so it would be good to put it in the documentation in my opinion 👍
