### ISSUE TITLE
Uninstalling node is not supported yet.

### ISSUE THREAD

**Issue by shangxinbo** [volta-cli/volta#1596]
root@10-60-60-4:/home/ubuntu# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
root@10-60-60-4:/home/ubuntu# volta uninstall node
error: Uninstalling node is not supported yet.
root@10-60-60-4:/home/ubuntu# volta -v
1.1.1
root@10-60-60-4:/home/ubuntu# volta list
⚡️ Currently active tools:

    Node: v20.10.0 (default)
    Tool binaries available: NONE

See options for more detailed reports by running `volta list --help`.

**Comment by chriskrycho** [comment]
Alas, yep, still true! We are tracking this at #327, so I am going to close this as a duplicate. (Thanks for using Volta!)
