### ISSUE TITLE
Upgrade to latest version of Clap

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#1598]
We are currently on Clap v2; Clap has released v3 and v4 (and, just a few weeks ago, v5) over the time since we adopted it, and many of the features we use via third party integration are now nicely integrated into the library itself. Upgrading should be relatively straightforward, following the migration guides:

- [v3](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating-1)
- [v4](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating)

While v5 has some small breaking changes, they should not affect us.

Note that this *will* slightly affect our help output, but should not change the behavior or the program or the things we programmatically emit (e.g. `volta list`).

**Comment by gautamprikshit1** [comment]
May I?

**Comment by chriskrycho** [comment]
By all means! Feel free to ask questions here or (for more responsive feedback) [in Discord](https://discord.gg/hgPTz9A), and ping @charlespierce or myself there! We're all rather in-and-out this week and next for holidays, but will be happy to help as we're able!

**Comment by chriskrycho** [comment]
One other tip, on re-reading my write-up above, @gautamprikshit1 – your best move will be to tackle it by chunking it into much smaller PRs. I would suggest first creating PRs for any deprecations for v2 to v3 (and structopt), then do the v2 to v3 upgrade as a dedicated PR, and then repeat the process for the v3 to v4 upgrade.

**Comment by gautamprikshit1** [comment]
To upgrade to clap v4, MSRV needs to be updated and upgrading to clap v3 is stuck on an error which requires the `string` feature of the library which was introduced in clap v4

**Comment by chriskrycho** [comment]
This should be unblocked now that #1611 is merged!

**Comment by chriskrycho** [comment]
@gautamprikshit1 it looks like @tottoto ended up getting this done in parallel with the efforts you started a couple weeks ago (see #1649). Thanks, though!
