### ISSUE TITLE
Volta throws error on every command

### ISSUE THREAD

**Issue by SleepingForge** [volta-cli/volta#1630]
Hi!

Everytime I ran any npm or volta command I get the same Error. For example for `volta install node@latest` I get:
```powershell
error: Could not parse version ""

Please verify the intended version.
```

In the Error-Logfile:
```powershell
"C:\\Program Files\\Volta\\volta.exe" "install" "node@latest"
Volta v1.1.1

Could not parse version ""

Please verify the intended version.

Error cause: expected more input
```

I'm on Windows 10 - Version 22H2 (Developer Mode is on)
I tried reinstall, deleting all npm/node/... images, deleting everything in `%LOCALAPPDATA%\Volta\bin` after deleting volta and then reinstall, running `volta setup `as admin.

I don't know what happend, a few days ago everything worked fine. Some idea what I can do or why this happens?

**Comment by chriskrycho** [comment]
Weird bug, and sorry to hear that!

What kind of directory are you seeing that command in? That is, does it happen in *every* directory, or does it only happen in a specific directory? If the latter, does it have a `package.json` in it? If so, does that have an `engines` field or a `volta` config in it?

**Comment by SleepingForge** [comment]
Well, today everything works now...
Before I had this Bug in every directory and even after rebooting.

Thank you for your time!

**Comment by chriskrycho** [comment]
How odd! I am glad to hear it worked itself out in any case.
