### ISSUE TITLE
How to find the directory of global npm packages

### ISSUE THREAD

**Issue by popring** [volta-cli/volta#1639]
Normally, I can get the correct directory location with the following code.

```js
const globalDirectories = require('global-dirs')
const dir = path.resolve(globalDirectories.npm.packages)
```

But, the directory obtained after using volat is wrong.

Now after using volta, is there a way to get the location of the correct global npm package?

**Comment by popring** [comment]
> Thanks for the question! By intent, Volta does not have a single directory for globally-installed npm packages. Instead, it sandboxes each package installation. We wrote more about the reasoning and the way it works [in this blog post](https://blog.volta.sh/2019/06/18/global-installs-done-right/). Additionally, while a tool like `global-dirs`/`global-directory` _works_, it is ultimately using a bunch of hard-coded heuristics to try to figure it out, as you can see by [checking the source](https://github.com/sindresorhus/global-directory/blob/df9fdcd383faf601d16e855f281d131270717c33/index.js).
> 
> Depending on what you are actually trying to accomplish by querying the system for globally-installed tools, we might be able to suggest alternative approaches!

Thanks for the answer, I think I know how my problem was solved

**Comment by chriskrycho** [comment]
Glad to hear it! Closing this accordingly!
