### ISSUE TITLE
Issue with getting volta to work

### ISSUE THREAD

**Issue by vikingnope** [volta-cli/volta#1679]
I have an issue where volta is installed, it works fine for a few hours, then all of a sudden after closing VS Code and reopening it, it stops working and it tells me the command is not recognised.

What can be done. Dev Mode is turned on.

**Comment by rwjblue** [comment]
What version of volta? I'm wondering if perhaps VSCode isn't inheriting the right path or something?

**Comment by vikingnope** [comment]
Latest version v1.1.1 I believe, but then its not recognised anywhere, not even on command prompt or powershell. If I run them as admin it works fine, but if I run them normally they don't work.

This is my environment variable:
![image](https://github.com/volta-cli/volta/assets/81376423/c2465e33-2bcd-4151-bc5f-3072d5fc77c2)

**Comment by rytmis** [comment]
Try running PowerShell both with and without admin privileges, and see what this prints out:

```powershell
$env:path.Split(';') -match "volta"
Get-Command "volta"
```

I've got `C:\Program Files\Volta\` in my path, and Get-Command points to `C:\Program Files\Volta\volta.exe`
