### ISSUE TITLE
volta install cocoapods

### ISSUE THREAD

**Issue by vaynevayne** [volta-cli/volta#1734]
<img width="460" alt="image" src="https://github.com/volta-cli/volta/assets/124666577/3a6871a7-d752-44fa-97b0-918dd8c7dbe4">

can't install cocoapods 
How to know which packages can be installed?

If the installation fails, can it give a failure prompt? Instead of 0.0.0

**Comment by charlespierce** [comment]
Hi @vaynevayne, thanks for the question! The packages you can install are ultimately from npm. This isn’t a failed install, it looks like there is a package named `cocoapods` [on npm](https://www.npmjs.com/package/cocoapods), which only has a single version (`0.0.0`).

Unfortunately, Volta doesn’t have a way to know if a package is maintained when it’s installed.

**Comment by hffmnn** [comment]
@vaynevayne I guess the `cocoapods` you are looking for is [this ruby package](https://guides.cocoapods.org/) which can be installed via e.g. `gem`, see https://guides.cocoapods.org/using/getting-started.html
