### ISSUE TITLE
Create `shim` executable

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#176]
Eliminate `launchbin` and `launchscript` and replace with a single `shim` executable:

  - [ ] Remove the `launch{bin, script}` binaries
  - [ ] Create a `shim` binary
  - [ ] Installer should install it to `~/.notion/exe/shim`
  - [ ] use https://crates.io/crates/process_path to figure out the executable name
  - [ ] first try to use the project toolchain (this logic already exists)
  - [ ] next try to read `~/.notion/tools/user/bins/$name/package.toml`
  - [ ] get the tool path from the toml data
  - [ ] launch `~/.notion/tools/user/installed/$package/$toolpath` (use `cmd /c` if this is Windows and it's a legacy batch/cmd script)
  - [ ] finally default to delegating to next thing in `PATH`

Depends on:
  - [ ] #175 Package binary case of `Toolchain::install`

**Comment by charlespierce** [comment]
I think the architecture of the code in Volta has moved beyond the specific details of this issue, and we _do_ now have a `volta-shim` executable that handles the shim behavior.
