### ISSUE TITLE
1.1.2

### ISSUE THREAD

**Issue by michaelr0** [volta-cli/volta#1765]
Hello there,

Really liking Volta for managing node/npm versions.

I'm in the process of making a few docker images and being able to use the pre-built linux amd64 and linux aarch64 releases would be really handy in that endeavour.

Just curious if there are any estimations on when 1.1.2 might be tagged?

Thanks for all the work :)

**Comment by this-is-tobi** [comment]
Hey, I asked this question a few months ago (https://github.com/volta-cli/volta/pull/1696#issuecomment-2004339482) but it went unanswered so I recently ended up moving on to [proto](https://moonrepo.dev/proto).

*However, thanks to the Volta team for all their hard work.*

**Comment by chriskrycho** [comment]
Hey all, sorry for the delay. I am committing to taking a bunch of (personal!) time this week and next and seeing what I can do to get an update pushed out.

**Comment by geekact** [comment]
Is that possible to make pnpm support stable at version 1.1.2?

**Comment by chriskrycho** [comment]
@geekact unlikely, to be honest: that would just delay us further, as there is an annoyingly long tail of work to be done for pnpm there.

**Comment by chriskrycho** [comment]
Going to go ahead and close this while we work on getting the next release (2.0) out – hopefully in the next week or two!
