### ISSUE TITLE
Create a `shell` subdirectory

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#177]
Since we'll need a script with shell functions for each shell we support, we shouldn't clutter the top-level `~/.notion` directory. Create a `shell` subdirectory where those live.

Each script should just be called `~/.notion/shell/$SHELL` where `$SHELL` is the name of the shell.

**Comment by charlespierce** [comment]
As of Volta 0.7.0, we no longer need shell functions for each shell.
