### ISSUE TITLE
Create a `hooks` subdirectory

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#178]
The term "hook" is a bit more conventional for CLI plugin architectures than "plugin". Let's create a `~/.notion/hooks` directory where each hook can be defined, similar to git's layout. This really deserves an RFC for a more stable design (in particular, whether we want a single config file or one file per hook), but we can experiment with something for now.

**Comment by mcarifio** [comment]
Looks like `$VOLTA_HOME/{hook,plugin}` hasn't arrived as of version 0.6.3. It's still a good idea.

You might also want to consider some way for "user hooks" to be discovered without "polluting" $VOLTA_HOME. Perhaps something like `~/.config/volta/hook` if you're into the xdg desktop conventions (which some people don't like).

**Comment by charlespierce** [comment]
Currently the hooks system is specified in a file: `hooks.json`, defined in `VOLTA_HOME` or in an individual project (depending on if you want them to apply to everything on the system or just to a single project). There isn't anything that would necessitate an entire directory, so we haven't created it yet. If we do make changes that would use more than a single file, this will definitely be important, however.

As for XDG, we've talked about it, but as yet haven't found a strong reason to switch to that layout. While the convention is interesting, it's not ubiquitous, and having a single managed directory (as opposed to a number of related ones) has benefits as well.
