### ISSUE TITLE
Issue with pnpm 9 Installed via Volta: Dependencies Not Installed Properly in Monorepo

### ISSUE THREAD

**Issue by verynong** [volta-cli/volta#1805]
#### Problem Description
After installing pnpm 9 using Volta, I encountered an issue with dependency installation when managing a monorepo project. When running `pnpm recursive install` or `pnpm -r i`, dependencies for some packages are not installed correctly. However, if I manually enter each package directory and run `pnpm install`, the dependencies are installed properly.

#### Environment Information
- Volta version: 1.1.1
- pnpm version: 9.6.0
- Node.js version: 20.15.1
- Operating System: macOS 14.5/CentOS Linux release 8.1.1911

#### Steps to Reproduce
1. Install pnpm using Volta: `volta install pnpm@9.6.0`
2. Run `pnpm install` to install dependencies in the monorepo project
3. Notice that dependencies for some packages are not installed correctly
4. Manually enter each package directory and run `pnpm install`, dependencies are installed correctly

#### Expected Behavior
When running `pnpm install`, all package dependencies should be installed correctly.

#### Actual Behavior
When running `pnpm install`, dependencies for some packages are not installed correctly. Manually entering each package directory and running `pnpm install` is required to install dependencies correctly.

#### Attempted Solutions
Using pnpm 8 to install dependencies works as expected without any issues.

#### Structure
![image](https://github.com/user-attachments/assets/1cf86a4e-a14f-4c5d-84cd-a8f14bf2b96d)

**Comment by verynong** [comment]
My mistake, pnpm config list viewed recursive install=false

**Comment by chriskrycho** [comment]
Glad you got it sorted!
