### ISSUE TITLE
How do I switch volta download sources?

### ISSUE THREAD

**Issue by giserman001** [volta-cli/volta#1816]
hi, How do I switch volta download sources?

**Comment by giserman001** [comment]
![image](https://github.com/user-attachments/assets/8f484cb3-b6aa-42ac-a2dc-5fada195ef14)

**Comment by chriskrycho** [comment]
Your best bet is to look at our [hooks](https://docs.volta.sh/advanced/hooks) system! I am closing this as “answered”, but feel free to ask further questions. 👍🏼
