### ISSUE TITLE
Support ARM64 on Linux installing via https://get.volta.sh

### ISSUE THREAD

**Issue by Fydon** [volta-cli/volta#1834]
When using `curl https://get.volta.sh | bash` on a ARM64 Linux host the following is displayed even now that 2.0.0 is released.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10917  100 10917    0     0   108k      0 --:--:-- --:--:-- --:--:--  108k
Error: Sorry! Volta currently only provides pre-built binaries for x86_64 architectures.
```

This might require adjusting [/crates/volta-core/src/tool/node/metadata.rs](https://github.com/volta-cli/volta/blob/cbfff723d2d9eb8126a6a04e8f3e00551058de2e/crates/volta-core/src/tool/node/metadata.rs#L46-L47) so that all the AARCH64 is only allow for Linux, macOS or Windows or that it is allowed for any OS assuming that only Linux, macOS and Windows is being targeted.

**Comment by charlespierce** [comment]
@Fydon I've updated the installer and the Netlify config, so the installer should be working correctly for Linux ARM now! I just tested it with a docker container from an M2 Mac and it worked 🎉

**Comment by Fydon** [comment]
Thank you. Working for me as well on Linux ARM64 server.
