### ISSUE TITLE
Volta doesn't pass certain arguments to the globally installed npm package

### ISSUE THREAD

**Issue by j-murata** [volta-cli/volta#1852]
## Reproduction Steps
1. Create a simple npm package.

    <p><details open>
    <summary><code>package.json</code></summary>

    ```json
    {
      "name": "my-pkg",
      "version": "0.0.1",
      "bin": {
        "my-cmd": "./index.mjs"
      },
      "main": "./index.mjs"
    }
    ```

    </details></p>

    <p><details open>
    <summary><code>index.mjs</code></summary>

    ```js
    #!/usr/bin/env node
    console.log(process.argv);
    ```

    </details></p>

2. Install this package globally with `npm`.

    ```sh
    npm i -g ./my-pkg/
    ```

3. Run `my-cmd` with `-h` or `--help` arguments (e.g. `my-cmd -h`).

    ⇒ Then, Volta outputs the `volta run` help message.

    ```console
    $ my-cmd -h
    Run a command with custom Node, npm, pnpm, and/or Yarn versions
    
    Usage: volta.exe run [OPTIONS] <COMMAND> [ARGS]...
    
    Arguments:
      <COMMAND>  The command to run
      [ARGS]...  Arguments to pass to the command
    
    Options:
          --node <version>    Set the custom Node version
          --npm <version>     Set the custom npm version
          --bundled-npm       Forces npm to be the version bundled with Node
          --pnpm <version>    Set the custon pnpm version
          --no-pnpm           Disables pnpm
          --yarn <version>    Set the custom Yarn version
          --no-yarn           Disables Yarn
          --env <NAME=value>  Set an environment variable (can be used multiple times)
          --verbose           Enables verbose diagnostics
          --very-verbose      Enables trace-level diagnostics
          --quiet             Prevents unnecessary output
      -h, --help              Print help
    ```

    Note that I have confirmed that the behavior is as expected when `my-cmd` is run without any arguments.

## Consideration
The following script exists in `${LOCALAPPDATA}/Volta/bin/my-cmd`.
```bash
#!/bin/bash
volta run "$(basename $0)" "$@"
```
This is my guess, but I suspect that the `"$@"` arguments that should be passed to the package are being interpreted as `volta run` arguments.

In fact, after modifying the script as follows (simply adding `--`), this issue no longer occurs.

```diff
@@ -1,2 +1,2 @@
 #!/bin/bash
-volta run "$(basename $0)" "$@"
+volta run -- "$(basename $0)" "$@"
```
I am not sure if this workaround is universally correct, so I would appreciate your consideration of a safe fix for this issue.

**Comment by charlespierce** [comment]
Hi @j-murata, thanks for the report and for the detailed reproduction steps! This is definitely not expected, so I'll take a look.

I believe it's a regression in how we handle arguments to `volta run`, so hopefully it's something we can fix in the code itself. However, I believe your suggested workaround of adding `--` to the generated script file would also solve it, so at the very least that should be a solution. If I can find a solution quickly then I'll try to get that into a 2.0.1 release I'm aiming to have today / this weekend. If not then it might have to wait for a follow-up (though not nearly as long as it took to get the 2.0.0 one out 😅)

**Comment by j-murata** [comment]
Hi @charlespierce I found Volta v2.0.1 has been shipped on winget.
And after installation, I also confirmed that the `-h` flag is passed to the command correctly.

Thank you for fixing this problem!
