### ISSUE TITLE
云服务器无法 curl https://nodejs.org/dist/index.json 

### ISSUE THREAD

**Issue by MrCays** [volta-cli/volta#1866]
![1724174348353](https://github.com/user-attachments/assets/3589044e-936c-4010-bf70-37f9707757ec)

希望能更新一个自定义 源 的设置  registry 而不是只能从 https://nodejs.org/dist/index.json 来下载nodejs

**Comment by charlespierce** [comment]
Hi @MrCays, if I'm understanding correctly, I believe the solution we have is [Hooks](https://docs.volta.sh/advanced/hooks)

**Comment by witheredAd** [comment]
#1524

**Comment by MrCays** [comment]
OK Thanks

**Comment by chriskrycho** [comment]
Going ahead and closing this, but feel free to reopen if there's a bug or issue not addressed there or elsewhere in the repo!
