### ISSUE TITLE
Running `notion use` creates an empty cache file

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#189]
I already have node 10.6.0 installed. This is what is happening:

```
$ ls -al ~/.notion/cache/node/
total 33032
drwxr-xr-x  5 mistewar  LINKEDIN\eng       160 Nov  1 16:08 .
drwxr-xr-x  4 mistewar  LINKEDIN\eng       128 Nov  1 16:03 ..
-rw-------  1 mistewar  LINKEDIN\eng    126523 Nov  1 16:08 index.json
-rw-------  1 mistewar  LINKEDIN\eng        29 Nov  1 16:08 index.json.expires
-rw-r--r--  1 mistewar  LINKEDIN\eng  16208913 Nov  1 16:08 node-v10.6.0-darwin-x64.tar.gz
```

```
$ notion use node 9.8
Pinned node to version 9.8.0 in package.json
```

```
$ ls -al ~/.notion/cache/node/
total 33032
drwxr-xr-x  6 mistewar  LINKEDIN\eng       192 Nov  5 15:13 .
drwxr-xr-x  4 mistewar  LINKEDIN\eng       128 Nov  1 16:03 ..
-rw-------  1 mistewar  LINKEDIN\eng    126948 Nov  5 15:13 index.json
-rw-------  1 mistewar  LINKEDIN\eng        29 Nov  5 15:13 index.json.expires
-rw-r--r--  1 mistewar  LINKEDIN\eng  16208913 Nov  1 16:08 node-v10.6.0-darwin-x64.tar.gz
-rw-r--r--  1 mistewar  LINKEDIN\eng         0 Nov  5 15:13 node-v9.8.0-darwin-x64.tar.gz
```

**Comment by charlespierce** [comment]
I don't believe this is an issue any more. Downloaded tarballs are no longer kept in `~/.notion/cache/`, instead they are kept in `~/.notion/tools/inventory/`, and running `notion pin node 9.8` causes the full tarball to be downloaded and stored in that location.

**Comment by chriskrycho** [comment]
Have we confirmed that this is no longer an issue? If so, let's close it. (Also `volta use` does not exist anymore; I believe it would be under `pin` or `install`?)

**Comment by charlespierce** [comment]
Confirmed, this isn't an issue. When we run `volta pin` (the equivalent to `notion use`), we fully fetch the cache file, we don't just create an empty one. Also, as of #498, we only write the cache file once the install has been completed, in an atomic `rename` operation.
