### ISSUE TITLE
How can I verify Volta hooks.json is valid?

### ISSUE THREAD

**Issue by ivestszheng** [volta-cli/volta#1918]
Here's my hooks.json in global.

```json
{
	"node": {
		"index": {
			"template": "https://cdn.npmmirror.com/binaries/node/index.json"
		},
		"distro": {
			"template": "https://registry.npmmirror.com/-/binary/node/v{{version}}/{{filename}}"
		}
	},
	"npm": {
		"index": {
			"prefix": "https://registry.npmmirror.com/npm/"
		},
		"latest": {
			"bin": "~/npm-latest"
		},
		"distro": {
			"template": "https://registry.npmmirror.com/npm/npm-{{version}}.tgz"
		}
	},
	"yarn": {
		"index": {
			"template": "https://registry.npmmirror.com/yarn/{{os}}/{{arch}}/yarn-{{version}}.tgz"
		},
		"latest": {
			"prefix": "https://registry.npmmirror.com/yarnpkg/"
		},
		"distro": {
			"bin": "~/yarn-distro"
		}
	}
}
```

When I use `npm config get registry` ，output is still `https://registry.npmjs.org/`. It seems not to work. How can I verify Volta hooks.json is valid?

Is it supposed to output `https://registry.npmmirror.com/` ?

**Comment by ivestszheng** [comment]
Is "npm" only set to download itselt not registry?
It seems when I want to change npm registry I still need to use 'npm config set registry' .

**Comment by rwjblue** [comment]
Yes, the hooks.json is specifically about fetching `node`, `npm`, `yarn`, &c themselves. It does *not* change the behaviors of the individual tools on how to actually fetch individual packages from a customized location. In order to do both things, you would usually use `hooks.json` along with an `.npmrc` or `.yarnrc.yml`. 

For example, you might use the following `.npmrc`:

```
registry=https://custom.registry.com/
//custom.registry.com/:_authToken=YOUR_AUTH_TOKEN
```

Or the following `.yarnrc.yml`:

```yaml
npmRegistryServer: "https://custom.registry.com/"
npmAuthToken: "YOUR_AUTH_TOKEN"
```

The docs for the `hooks.json` [are here](https://docs.volta.sh/advanced/hooks) ([source code here](https://github.com/volta-cli/website/blob/main/subdomains/docs/_advanced/hooks.md)), if you have the time we'd love a PR updating the docs so that it makes things clearer here.

**Comment by lisonge** [comment]
hooks.json is not work, it still download from `nodejs.org` instead of `registry.npmmirror.com`

**Comment by lisonge** [comment]
<img width="2166" height="832" alt="Image" src="https://github.com/user-attachments/assets/6f209869-5e45-4c07-9cf7-7be792397d58" />

and when i broken hooks.json, volta still work ? so how can I know hooks.json is work ?

**Comment by ivestszheng** [comment]
> hooks.json is not work, it still download from `nodejs.org` instead of `registry.npmmirror.com`

hooks.json 只是改变下载 node, npm, yarn 的源。具体从哪个镜像地址下载仓库还是和原来一样的方式，npm config set registry 或者通过 .npmrc 等配置文件。我后面重装系统再使用 volta 的时候没有配置过 hooks.json 了。

**Comment by lisonge** [comment]
我上面的意思有两点

1. 我使用 hooks.json 没有对 volta 从哪里下载 nodejs 产生影响
2. 当我使用错误的 hooks.json 文件语法时，volta 起码应该报错配置文件错误警告，但是并没有

---

你似乎搞混了 volta install 和 npm install 的镜像下载配置

此处讨论的是 volta 如何配置来从镜像下载 node/pnpm/npm/yarn

而不是如何在 npm/pnpm/yarn 中去配置镜像下载 node_modules 库，volta 跟 `.npmrc` 没有任何关系

**Comment by ivestszheng** [comment]
> 我上面的意思有两点
> 
> 1. 我使用 hooks.json 没有对 volta 从哪里下载 nodejs 产生影响
> 2. 当我使用错误的 hooks.json 文件语法时，volta 起码应该报错配置文件错误警告，但是并没有
> 
> 你似乎搞混了 volta install 和 npm install 的镜像下载配置
> 
> 此处讨论的是 volta 如何配置来从镜像下载 node/pnpm/npm/yarn
> 
> 而不是如何在 npm/pnpm/yarn 中去配置镜像下载 node_modules 库，volta 跟 `.npmrc` 没有任何关系

这个 issue 已经关闭一年半了，我觉得你如果提问题首先要看完当时沟通的上下文，搞清楚背景。你的问题和我这个 issue 无关的话你应该自己提一个 issue。

**Comment by lisonge** [comment]
ok

**Comment by lisonge** [comment]
感谢回复，我的问题已自行解决，源于我使用 scoop 在 Windows 下管理安装的 volta

此时环境变量 VOLTA_HOME 被安装脚本设置为 C:\Users\lisonge\scoop\apps\volta\current\appdata

但是 [volta 官方文档](https://docs.volta.sh/advanced/hooks) 中将配置文件硬编码为 
```text
Hooks specified in the Volta directory (~/.volta/hooks.json on Linux/MacOS, %LOCALAPPDATA%\Volta\hooks.json on Windows) will apply across the entire system
```
误导了我，导致配置文件从未被成功设置，实际上此处文档的配置文件应该是 `"$env:VOLTA_HOME/hooks.json"`
