### ISSUE TITLE
Specify minimum Rust version on README

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#192]
This morning, @locks was having trouble because of `dyn Trait` syntax, stabilized as of 1.27. Given this, 1.27 is functionally the minimum support version; but how does the project want to set this policy-wise?

**Comment by rwjblue** [comment]
Just poked at this, the README.md points to the website's [contributing guide](https://docs.notionjs.com/contributing/) which says:

> Notion is intended to compile with Rust 1.31 or newer.

I _think_ we can close this issue now? @chriskrycho - c/d?

**Comment by chriskrycho** [comment]
Seems fair to close to me, since README specifies.
