### ISSUE TITLE
Can Volta support deploying multiple projects with different Node versions on the same server?

### ISSUE THREAD

**Issue by dizuncainiao** [volta-cli/volta#1975]
I have learned that Volta can manage Node and npm versions during project development. So can Volta support deploying multiple projects with different Node versions on the same server?

**Comment by chriskrycho** [comment]
Yep! You would just `volta pin node@<some version>` in one package and `volta pin node@<another version>` in the other! Hopefully the way this would work is fairly clear if you read through [the docs](https://docs.volta.sh/guide/)!
