### ISSUE TITLE
Should `notion current` show all currently-active tools?

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#284]
I expected on running `notion current` to know the current `yarn` version as well, and as we support pinning/installing other tools in the future, I think others users may also expect that report.

**Comment by rwjblue** [comment]
Ya, I tend to agree...

**Comment by charlespierce** [comment]
Moving this out of the release milestone as we really need to put some more thought into our "query" commands, what information we should show and how best to show it.

**Comment by chriskrycho** [comment]
Related to #349.
