### ISSUE TITLE
resolving public node should check OS availability

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#34]
`NodeCatalog::resolve_public` scans for available version of node from the public list, but it doesn't make sure each version it checks is actually available for the current OS. Add this logic to the `skip_while` callback.

**Comment by dherman** [comment]
I'm removing this from the MVP milestone; it's not really a blocker.

**Comment by charlespierce** [comment]
We should also check Architecture availability, especially with Mac moving to ARM architecture in the coming year.

**Comment by charlespierce** [comment]
To add some more details: The `NodeEntry` object has a property `files` which contains the list of OS/Arch pairings. It looks like they don't _quite_ line up with the `NODE_DISTRO_OS` `NODE_DISTRO_ARCH` `NODE_DISTRO_EXTENSION` constants we already have (at least for MacOS and Windows, Linux looks like we can build it easily). Instead, the ones we are looking for are:

```
linux-arm64
linux-x64
linux-armv7l
osx-x64-tar
win-x64-zip
```

**Comment by charlespierce** [comment]
As noted in #847, this is especially relevant to Windows, as older versions of Node didn't always have the zip file available, so implementing this can improve the error case and provide a better error message.
