### ISSUE TITLE
`volta list` command

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#349]
As a user who has installed a bunch of different default tools, I want to know what tools I have installed at what version, e.g:

```sh
$ volta list
Default tools:

    Tool               | Version   | Node Version   | Packager
    ================== | ========= | ============== | ===========
    ember-cli          | 3.9.0     | 11.14.0        | npm 6.7.0
    typescript         | 3.4.3     | 11.14.0        | npm 6.7.0
    ts-node            | 8.0.3     | 11.14.0        | npm 6.7.0
    yarn-deduplicate   | 1.1.1     | 11.14.0        | npm 6.7.0

```

(One can imagine that the <b>Packager</b> and <b>Node Version</b> fields will differ more in the future if packages begin adopting Volta.)

We have all the relevant data in the `tools/user/package` to do this, and we should be able to use something like [prettytable-rs](https://github.com/phsym/prettytable-rs) to do the formatting.

**Comment by rwjblue** [comment]
Definitely seems useful to me, should this be converted to an RFC (or issue on the RFCs repo)?

**Comment by chriskrycho** [comment]
Ah, good point – the RFCs list says we need it when:

> You need an RFC if you intend to make substantial changes to Notion, or the RFC process itself. > What constitutes a "substantial" change is evolving based on community norms, but may including the following:
> 
> - Any change to the command-line interface (including command syntax and behavior).
> - Changes to the configuration formats.
> - Changes to the plugin API.
> - Removing features.

It definitely fits under the first of those. If someone who has permissions on the org can do it, we can move this issue there and I can write up a small RFC to go with the implementation.

**Comment by thoov** [comment]
@chriskrycho I think that there is some overlap between `notion current` and `notion list`. I think for clarity we should drop `notion current` and just make `notion list` the command that should be run to "find out" what is installed and what versions.

cc: @charlespierce @mikrostew @dherman

**Comment by BryanHunt** [comment]
Woo hoo!!
