### ISSUE TITLE
Rebrand!

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#365]
**Update:** After running through a number of alternatives, we've settled on the name Volta!

----

A number of people have raised concerns about the project name causing confusion with the [personal organization tool of the same name](https://www.notion.so/). We definitely don't want to create any confusion for either our users or theirs, so we're rebranding.

Our new name will be **Volta**!

Steps for the rebrand:

- [x] new logo
- [x] volta-cli org
<details><summary>Details</summary>

  - [x] create org
  - [x] use new logo
  - [x] move members

</details>

- [x] volta.sh
<details><summary>Details</summary>

  - [x] reserve domain
  - [x] Jekyll theme
    - [x] fork repo
    - [x] update text for rename
  - [x] www repo
    - [x] fork repo
    - [x] update text for rename
    - [x] deploy in Netlify
    - [x] force https
  - [x] docs repo
    - [x] fork repo
    - [x] update text for rename
    - [x] deploy in Netlify
    - [x] force https
  - [x] blog repo
    - [x] fork repo
    - [x] update text for rename
    - [x] deploy in Netlify
    - [x] force https
  - [x] consolidate into monorepo
    - [x] create new monorepo
    - [x] copy separate repos into monorepo (theme, docs, blog, www)
    - [x] migrate docs subdomain netlify settings to monorepo
    - [x] migrate blog subdomain netlify settings to monorepo
    - [x] migrate apex domain netlify settings to monorepo
    - [x] copy GH issues to monorepo
    - [x] archive the separate repos
  - [x] get repo
    - [x] fork repo
    - [x] update code for rename
    - [x] deploy in Netlify
    - [x] force https

</details>

- [x] credentials
<details><summary>Details</summary>

  - [x] add Netlify link to theme footer
  - [x] create new Netlify team
  - [x] transfer sites to new team
  - [x] add more people to new team

</details>

- [x] code
  - [x] PR to update entire Notion repo
  - [x] update wiki
  - [x] update Netlify admin for impl.volta.sh to point to gh-pages branch of new repo
- [ ] CI
  - [ ] Travis
  - [ ] Azure Pipelines
- [x] Discord
  - [x] rename discord
  - [x] update logo
- [x] go live!
  - [x] build 0.5 release with new name
  - [x] create tag and release
  - [x] transfer repo to volta-cli/volta
  - [x] update repo description
  - [x] transfer rfcs repo to volta-cli/rfcs
  - [x] update repo description
  - [x] update `get` repo to new location

I was initially tempted to reset the versioning to 0.1, but I think (a) that signals less maturity in the project than we're actually at, and (b) I'm hesitant to _delete_ our old pre-releases. I think it's nice to keep them there for historical purposes. It seems reasonable for the first release under the new name to be 0.4.

**Comment by rwjblue** [comment]
Agree RE: 0.4.

**Comment by mikrostew** [comment]
Not sure how granular you want these steps - possibly missing "Move org members to @jetson-cli org"

**Comment by chriskrycho** [comment]
- [ ] update CI settings (and names of orgs as appropriate)
    - [ ] Azure Pipelines
    - [ ] Travis
    - [ ] Appveyor

**Comment by thoov** [comment]
Are we moving the issues over or what should happen on this front?

**Comment by chriskrycho** [comment]
There's a PR waiting (which I will rebase after we land a couple others) for updating the whole codebase, at #370.

**Comment by dherman** [comment]
Basically all done except for CI, which I filed as a followup bug in #431.
