### ISSUE TITLE
Enable automated release with PR tooling (bot?)

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#379]
As a maintainer, I'd like to be able to simply release whenever desired, with automated versioning managed by the Git history.

As a contributor, I'd like to be able to contribute without worrying about the details of how I format my commit messages.

---

Given the above goals, if we want automated release—whether on a cadence, on merge to `master`, or some other strategy—it makes sense for maintainers to manage it via the pull request workflow. We might want to build a small bot that let's us comment with (as a hypothetical and purely spitballed example): "merge as bug fix," "merge as feature", "merge as breaking change" to create merge commits which in turn identify what the next release should be automatically.

(This is a *deep* rabbit hole, so whether it's even worth building is an open question.)

**Comment by charlespierce** [comment]
With automated builds, we hopefully can also add support for additional OS / architecture combinations (we currently only support MacOS, Linux, and Windows on x86_64 architectures with pre-built binaries). See #519

**Comment by neezer** [comment]
I’d love to use Volta on my Pi (ARM, Manjaro). Any idea when I’ll be able to? Thanks for your hard work!

**Comment by charlespierce** [comment]
Automated release (mostly, you still need to provide the release notes and click "Publish") is now done with GH Actions, triggered off of pushing a `v{VERSION}` tag to the default branch.
