### ISSUE TITLE
Windows installer is not signed

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#407]
Presently, Windows users will get a loud scary message saying the installer is not signed during installation. We should incorporate signing into the build-and-distribute process.

**Comment by charlespierce** [comment]
Looks like we'll need to pay for a Code Signing Certificate in order to sign the installer, so we'll likely want to wait until after the rebrand to purchase one, so the organization matches the name of the product.

**Comment by dustinsoftware** [comment]
Now that the rebrand has happened, can this be revisited? 😄

**Comment by charlespierce** [comment]
#715 Has screenshots of the warnings / roadblocks that Windows puts up, and they’re pretty substantial barriers to adoption.

I think we have an angle to getting the code-signing certificate sponsored, so I’ll investigate further and see if we can move this along.

**Comment by charlespierce** [comment]
Fixed in 1.0.0 (though we're still developing reputation to avoid the Windows blocker)

**Comment by dustinsoftware** [comment]
Awesome!! Thanks!
