### ISSUE TITLE
Improve output for installing a package

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#424]
The current process of installing a tool in the default toolchain is noisy—outputting all of npm or yarn's output—and also could be more informative. Suggestions we landed on in our last meeting:

- default to *not* showing npm or yarn's output; instead, only show it if `--verbose` passed, and display a spinner while the process is in progress
- list the installed binaries, e.g. when `volta install ember-cli` finishes say something to the effect of `success: you can now run ember` (preferably with some nice coloring and bolding of the command name or some such)

**Comment by rwjblue** [comment]
FWIW, the proposed solution would have also fixed https://github.com/notion-cli/notion/issues/374 (but I still think the flags in https://github.com/notion-cli/notion/pull/394 are good for us to use).
