### ISSUE TITLE
Support `volta install`ing a tarball

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#427]
There are times (like when you want to test a prebuilt `npm pack` result) that you need to install a global package but not from the registry.

Without `notion` you would do `npm install --global ./path/to/tarball.tgz`, but `notion` intercepts the `--global` invocation errors with:

```
Notion error: Global package installs are not recommended
```

Since we are _ultimately_ using `npm install` to do the heavy lifting here anyways, and `npm` supports:

```
npm install --global package-name@./some/path/to/tarball.tgz
```

We should be able to make something like this work (based on the work in https://github.com/notion-cli/notion/pull/383):

```
notion install ember-cli@./ember-cli-3.10.0.tgz
```

However, at the moment ^ causes the following error:

```
error: Could not parse version "ember-cli-3.10.0.tgz"
```

---

Reported by @turbo87 in discord

**Comment by dherman** [comment]
@DanielRosenwasser reached out to me today with an interest in this. They have a GitHub bot that packs PRs into tarballs on demand ([example](https://github.com/microsoft/TypeScript/pull/38561#issuecomment-641464891)), and they'd love to be able to use that in CI with Volta.

**Comment by charlespierce** [comment]
As of Volta 0.9.0, we now support using the package managers directly to install packages. We don't currently support the specific syntax `volta install /path/to/tarball.tgz`, but we _do_ support `npm i -g /path/to/tarball.tgz` to perform the same task.

**Comment by DanielRosenwasser** [comment]
Perfect, thank you very much!
