### ISSUE TITLE
Toolchains key no longer recognized

### ISSUE THREAD

**Issue by mitsuhiko** [volta-cli/volta#432]
With the upgrade to volta the key `toolchains` key became `volta`. Yet everything in the docs still points to `toolchains` and the volta key is completely undocumented other than in the announcement post.

There is absolutely no upgrade path without having to add both `volta` *and* `toolchains` to the package.json now and since it's now a volta specific key there is not even a point in having it in the package.json any more.

At this point if this is not going to turn into a standardized upon key it would be preferrable to instead have a `.voltarc` file which would also solve some of the docker concerns: #282

**Comment by mitsuhiko** [comment]
It would be preferrable to have a point release of volta to temporarily still accept toolchains to support a reasonable upgrade flow. Also if toolchains is gone for good the docs need updating.

**Comment by chriskrycho** [comment]
Thanks for the feedback. I opened volta-cli/website#19 to fix the docs issue. You may also want to track the progress of volta-cli/rfcs#33 and the implementing issue, #411, which relate to supporting an external file.

For history on the change from `toolchain` to `volta`, please see the discussion in #412 and #413.

As regards the change: this is a breaking change and was noted as such in the [RELEASES.md](https://github.com/volta-cli/volta/blob/master/RELEASES.md) file.

**Comment by mitsuhiko** [comment]
> As regards the change: this is a breaking change and was noted as such in the RELEASES.md file.

It's a breaking change but without any path towards resolving it. This means that for a project using volta one now needs to get the new key into the package.json in master, then have all pending PRs get master merged in and only then people can start moving over. There is no reasonable way this upgrade can be performed from what I can tell. This is really painful. Users can't update to volta until both keys are in the codebase for some period of time.

**Comment by chriskrycho** [comment]
We totally get the frustration there! I'm looking to see if we can provide a good path where we cut a 0.5.1 that supports `toolchain` but warns that it's deprecated; hopefully that will unblock you. :)

**Comment by rwjblue** [comment]
> It's a breaking change but without any path towards resolving it. This means that for a project using volta one now needs to get the new key into the package.json in master, then have all pending PRs get master merged in and only then people can start moving over. There is no reasonable way this upgrade can be performed from what I can tell.

Yes, I think you are right.

> This is really painful. 

I agree, I am sorry that we didn't have a better path laid out here. Thank you for bringing it up.

I think bringing back the support for `toolchain` with a warning as a fallback when `volta` is not present is a good (hopefully small) change to make for a 0.5.1.
