### ISSUE TITLE
Warning message width is "shortened"

### ISSUE THREAD

**Issue by thoov** [volta-cli/volta#449]
Steps to reproduce:
1. Add both `volta` and `toolchain` properties in package.json
2. Run `node -v` and see "shortened" warning

<img width="1792" alt="Screen Shot 2019-05-20 at 10 26 10 PM" src="https://user-images.githubusercontent.com/166909/58070532-48c44a80-7b4e-11e9-936a-c2e8940fa62e.png">

Expected:

Warning message should not "shortened"

**Comment by chriskrycho** [comment]
I'm not sure what you're getting at – the fact that it's wrapped instead of extending to your full terminal width?

**Comment by rwjblue** [comment]
@chriskrycho - Yes, thats what I think is being reported here. How do we determine max width?

**Comment by chriskrycho** [comment]
For general legibility, I set a maximum of whichever is *narrower*: 80 characters or the user's terminal. We can certainly experiment with bumping that up a bit (e.g. to 100 characters), but full-width text can become very hard to read at very wide ranges, so I'd argue against always using the whole width.

**Comment by chriskrycho** [comment]
**Addendum:** the quirkier bit here is that the wrapping isn't behaving as I'd expect on the third line of the warning.

**Comment by rwjblue** [comment]
@chriskrycho - The path as an `-` in it, so its deciding to wrap (since the full value won't fit within the 80 char limit). Ideally, we avoid wrapping on the interpolated content, but I'm not sure if that is possible. 

RE: suggested width, we may need to do something akin to (forgive the JS 😢):

```js
function calculateWidth {
  let userTerminalWidth = 180; /* figure it out somehow */
  let minimumWidth = 45; /* never go smaller than this, regardless of terminal size */
  let preferredWidth = 160; /* arbitrary preference */

  if (userTerminalWidth > preferredWidth) {
    return preferredWidth;
  } else if (userTerminalWidth > minimumWidth) {
    return userTerminalWidth;
  } else {
    return minimumWidth;
  }
}
```

Sorry if there is a more elegant way of writing that...

**Comment by thoov** [comment]
> I'm not sure what you're getting at – the fact that it's wrapped instead of extending to your full terminal width?

@chriskrycho @rwjblue 2 things:

1. That it's getting wrapped.
2. That each line after the first is getting indented.

**Comment by rwjblue** [comment]
The indentation seems "fine" (its attempting to show that this text is part of the "volta warning" prefix), but we could probably get away with a `\t` instead of being indented _all_ the way past the `Volta warning:` text (which seems quite wide).

**Comment by thoov** [comment]
@rwjblue Correct. The issue seems to be the amount of indentation

**Comment by chriskrycho** [comment]
@rwjblue right, fairly similar to that is already implemented. The path wrapping shouldn’t be causing the next line not to fill, though.

@thoov I think it’s fair to suggest/ask that we tweak the style, and I’ll chat with folks and see if we can establish a style guide and preferences around this specific kind of formatting. I will note that I don’t think “not how I would do it” is the same as its being an *issue*. :smile:

**Comment by thoov** [comment]
> I will note that I don’t think “not how I would do it” is the same as its being an _issue_.

Im not sure what you mean by this?

**Comment by chriskrycho** [comment]
Haha, sorry: I just mean _taste varies_. We’re chatting through what tweaks to make, if any, and will follow up with those when we have a handle on them!
