### ISSUE TITLE
Tool does not switch to the project-specific version

### ISSUE THREAD

**Issue by PrsPrsBK** [volta-cli/volta#452]
Hi.  I installed tool by `volta install typescript@x` in two projects with different `x`, and `tsc` was added to my toolchain.
But `tsc` does not 'switch to the project’s chosen version of TypeScript' as the document says ([Using project tools - Understanding Volta | Volta](https://docs.volta.sh/guide/understanding#using-project-tools)).
And not-switching behavior seems natural, because `package.json` does not have any information of project specific version.

What am I missing? Or is `package.json` not relevant? Thanks in advance.

Volta: ver.0.5.2 (installer)
OS: Microsoft Windows [Version 10.0.17763.503]

**Comment by charlespierce** [comment]
Hi @PrsPrsBK I think this is a failure in our documentation / explanation. `volta install typescript@x` will make `tsc` available in your toolchain, as you noted, and it will choose a _default_ version of the `typescript` package to use when there is no other version available. However, Volta is not meant to be a replacement for your package manager. In essence, think of `volta install` as a replacement for _global_ package installs (`npm i -g` or `yarn global add`) that works correctly with local versions, not as a replacement for the local package installs.

To use `typescript` within a project, you can add it to `package.json` for that project in the usual way for your package manager (`npm i --save typescript` or `yarn add typescript`). Once you do that, then running `tsc` inside the project will delegate to the local version defined in `package.json` as described in the document you linked.

**Comment by PrsPrsBK** [comment]
I see. If tool's local version concerns, that should be specified and shared as dependency in package.json. Thanks for your explanation!
