### ISSUE TITLE
Possible to install Volta without passing flags to `curl`?

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#457]
(There was some discussion on Discord a few days ago, and I wanted to document that here to track this in case we want to do it)

## Problem

Our documented install process (from [getting started](https://docs.volta.sh/guide/getting-started)) passes 4 flags to `curl`:

```
curl -sSLf https://get.volta.sh | bash
```

These flags are (from `man curl`):

```
-s, --silent
       Silent or quiet mode. Don't show progress meter or error messages.  Makes Curl mute. It will still output the data you ask for, potentially even to the termi-
       nal/stdout unless you redirect it.

       Use -S, --show-error in addition to this option to disable progress meter but still show error messages.

-S, --show-error
       When used with -s, --silent, it makes curl show an error message if it fails.

-L, --location
       (HTTP)  If  the  server  reports  that  the requested page has moved to a different location (indicated with a Location: header and a 3XX response code), this
       option will make curl redo the request on the new place. If used together with -i, --include or -I, --head, headers from all requested pages  will  be  shown.
       When  authentication is used, curl only sends its credentials to the initial host. If a redirect takes curl to a different host, it won't be able to intercept
       the user+password. See also --location-trusted on how to change this. You can limit the amount of redirects to follow by using the --max-redirs option.

-f, --fail
       (HTTP)  Fail  silently  (no  output  at all) on server errors. This is mostly done to better enable scripts etc to better deal with failed attempts. In normal
       cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This flag  will  pre-
       vent curl from outputting that and return error 22.
```

The only one we _really_ need is `-L` to follow the 302 redirect (configured [here](https://github.com/volta-cli/get/blob/master/netlify.toml), in TOML 😅), because without that the download doesn't work:

```
$ curl http://get.volta.sh
Redirecting to https://raw.githubusercontent.com/volta-cli/volta/master/dev/unix/volta-install.sh
```

## Other projects

There are other projects that don't need `curl` flags, for example https://oya.sh/, because they:
1) have the url be direct, instead of a redirect and
2) provide the right Content-Type header for the response so it's treated as a download instead of raw text

```
curl https://oya.sh/get | bash
```

## Question

So, is it possible for us to change how the http://get.volta.sh site works to avoid the redirect and use `curl` with no flags?

**Comment by charlespierce** [comment]
From looking at the [netlify redirect docs](https://www.netlify.com/docs/redirects/), it looks like we may be able to set `status = 200` in https://github.com/volta-cli/get/blob/master/netlify.toml, and have it work as a proxy instead of a redirect.
