### ISSUE TITLE
Installation docs list only bash as being automatically configured

### ISSUE THREAD

**Issue by bmakuh** [volta-cli/volta#462]
I just tried installing Volta with the curl script, but [the instructions](https://docs.volta.sh/guide/getting-started) say you need to:

- Set the `VOLTA_HOME` variable to `~/.volta`
- Add `$VOLTA_HOME/bin` to the beginning of your `PATH` variable

It seems like that happens automatically, but it might be helpful in the install instructions to say something like,

> For Fish shell, remember to run `source ~/.config/fish/config.fish`

**Comment by chriskrycho** [comment]
Thank you for the report! Our [docs page](https://docs.volta.sh/guide/getting-started) looks like it could use an update to report which shells get set automatically – I *believe* it's any of bash, zsh, and fish.
