### ISSUE TITLE
Support `volta install <package>` from alternative npm registry

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#463]
## Problem: We only support the npm registry

Currently, `volta install <package>` only supports installing from the npm registry (https://registry.npmjs.org). We look for the package tarball in that registry, then fetch & unpack it to disk. After that we use `npm install` or `yarn install` to install the dependencies of the package.

So there is no way to do `volta install internal-company-tool` (or even something like #427).

## Potential Solution: Package hook, and .npmrc

So changing this would require:
* a hook to redirect the package download
* an `.npmrc` for the subsequent `npm install` or `yarn install` of the dependencies

## Potential Solution: Use npm, with .npmrc

Alternatively, we could use npm for the whole process, and only need the `.npmrc` file to be setup. This would require something internally like:
* `mkdir tmp; cd tmp; npm install <package>`

We already use npm for installing dependencies, so this is not a huge change. We would lose some granularity in the errors we provide, and have to depend on whatever errors are produced by npm.

**BUT**, this creates a chicken-and-egg problem: What platform do we use? Currently, after fetching the package, we parse the `package.json` to get the `"engines"` field, which determines which versions of `node` are compatible with the package. Then we use the most recent LTS version that matches "engines" to do the `npm install`. But in this case we already need to choose `npm` from a platform to begin the download and install, before we have access to the `package.json`.

**Comment by plunkettscott** [comment]
NPM also supports the `NPM_CONFIG_REGISTRY` environment variable if that would be easier to manipulate than temporarily using a `.npmrc` file.

**Comment by mikrostew** [comment]
Oh, nice - we could potentially use that env var, and take the registry URL as an argument

**Comment by chriskrycho** [comment]
Also relevant for the new GitHub package repo.

**Comment by plunkettscott** [comment]
It would, however, be nice to be able to forward my local `.npmrc` file temporarily, though. You can set other authentication options within `.npmrc`. However, for unauthenticated internal registries or registries that use machine auth I think a simple `--registry` option makes the most sense.

**Comment by charlespierce** [comment]
Another potential option: We could remove the `package` hooks entirely, and depend only on `.npmrc`. We can use `npm view [package name] dist.tarball` to get the URL to download the tarball from, which in my quick test works even for internal registries.

The only caveat with that is since we're installing a user tool, we probably would need to require a user-level `.npmrc` (i.e. in the user's home directory) as opposed to one that happened to be in the project, so that the subsequent `npm install` command works as we expect it to and can resolve other internal dependencies.

**Comment by plunkettscott** [comment]
If you did that, wouldn't that still cause you to not be able to switch between registries? Thinking internally here, our registry is only accessible over VPN. Frequently changing the registry config sounds tedious for that. Am I misunderstanding your proposed option, @charlespierce ?

**Comment by charlespierce** [comment]
@plunkettscott That would require you to update the registry config if you need to switch registries to install a package. However, that is mitigated by a couple of factors:

1. You can set registries by scope in `.npmrc`, so if your internal packages are all scoped in some way, you can easily switch between the public and private registry for packages.
2. `volta install` is designed to be an infrequent operation, once you have a tool, you shouldn't need to re-install it (unless you are upgrading versions), so it shouldn't require frequent changes.
3. If we architected the install process this way, it would be using the npm config settings to determine where to download the package from. That means if you needed to change the registry for a single command (like upgrading a tool), you could do it with the `NPM_CONFIG_REGISTRY` environment variable you mentioned above, if you didn't want to change `.npmrc` every time.

**Comment by plunkettscott** [comment]
@charlespierce Thanks for the clarification.

This sounds like a viable option to me, then. Especially if the install process can take the NPM_CONFIG_REGISTRY environment variable.

**Comment by mikrostew** [comment]
@charlespierce I'm going to start implementing this, and it looks like your idea of using `npm view` can get us the info we need, from the public registry or an internal one (depending on `.npmrc` or `NPM_CONFIG_REGISTRY`). And as a bonus we can get `"engines"` without parsing the `package.json`.

```
$ npm view --json gulp@latest
{
  "name": "gulp",
  "description": "The streaming build system.",
  "dist-tags": {
    "latest": "4.0.2"
  },
  "version": "4.0.2",
  "engines": {
    "node": ">= 0.10"
  },
  "dist": {
    "shasum": "543651070fd0f6ab0a0650c6a3e6ff5a7cb09caa",
    "tarball": "https://registry.npmjs.org/gulp/-/gulp-4.0.2.tgz",
  },
  (...and lots of other stuff we don't use...)
}
```

One thing I see with this:

To use `volta install <package>`, the user will already need to have Node installed, because we are using `npm`. We should be able to re-use some of the existing messaging about running `volta install node` if the user hasn't installed it yet. I don't think it would be a good idea to auto-install a default Node in this case.

**Comment by charlespierce** [comment]
I agree we shouldn't try to install a latest version or something to make `npm` available, if only because it would be super weird and confusing to see `Fetching node@12.1.0` and then `Fetching node@10.15.0` after that if the latest and the `engines` don't line up correctly. I think it makes sense to require the user have a Node version selected, as that's most likely going to be the common workflow.
