### ISSUE TITLE
Support `volta install <github-name>/<github-repo>`

### ISSUE THREAD

**Issue by rdaniels6813** [volta-cli/volta#472]
When I am trying to test different versions of a tool from github I am unable to install a global package from there with either npm or volta.

**Comment by rdaniels6813** [comment]
My use case would be to pull a specific branch using npm from github using the format `<username>/<repo>#<branch-name>`

**Comment by rwjblue** [comment]
At the moment, I believe we only support installing tools that are in the NPM registry. I think this would be a great feature though.

**Comment by charlespierce** [comment]
As of Volta 0.9.0, we support installing with the package managers directly. At the moment, we still don't support the specific syntax `volta install <github-name>/<github-repo>`, however we _do_ support `npm i -g <github-name>/<github-repo>` to do the same task.
