### ISSUE TITLE
Installer creates directory named ~ in current working directory when run a second time

### ISSUE THREAD

**Issue by glevine** [volta-cli/volta#484]
Assume that Volta isn't installed yet. Change to any directory. Run `curl -sSLf https://get.volta.sh | bash`.

`echo $VOLTA_HOME` should print `~/.volta`.

Run `curl -sSLf https://get.volta.sh | bash` again. `ls` should show a folder named `~`.

The reason is due to how `install_dir` is set. The first time, there is no `VOLTA_HOME` environment variable, so `install_dir="$HOME/.volta"`.

https://github.com/volta-cli/volta/blob/master/dev/unix/volta-install.sh#L564

In `create_tree()` the `install_dir` is created. `mkdir -p "$HOME/.volta"` creates the `.volta` directory under the user's home directory.

https://github.com/volta-cli/volta/blob/master/dev/unix/volta-install.sh#L396

The second time, `VOLTA_HOME` is `~/.volta`. For some reason `$HOME/.volta` does not seem to be treated as equal to `~/.volta` when checking if volta is already installed. Therefore, the installer attempts to install volta a second time.

https://github.com/volta-cli/volta/blob/master/dev/unix/volta-install.sh#L271

Back in `create_tree()`, it turns out that `mkdir -p "~/.volta"` is creating an empty folder named `~` in the current working directory. `mkdir -p` doesn't realize that `~` is a reference to the user's home directory until it is creating the `.volta` folder.

I was able to solve this with `export VOLTA_HOME="$HOME/.volta"` before running the installer again. The installer correctly recognized that volta was already installed.

I think the `VOLTA_HOME` environment variable needs to be `"$HOME/.volta"` so that an existing installation can be detected correctly.

**Comment by glevine** [comment]
I came across this, which might explain why `~` doesn't work like expected.

> If you want to add a \~-based path, selectively leave the \~/ unquoted to ensure that ~ is expanded; e.g.: export PATH=\~/"bin:$PATH". Alternatively, simply use $HOME inside a single, double-quoted string: export PATH="$HOME/bin:$PATH"

https://stackoverflow.com/a/33318886/1771599

**Comment by charlespierce** [comment]
Hi @glevine thanks for reporting this! What strikes me as strange is that we never use the literal character `~` as a stand-in for `$HOME` in our install or load scripts. What OS / Shell are you using, as it seems like it might be doing a reverse expansion of `/home/user/` (or whatever the home directory is) into `~`, which is then being misinterpreted in the way you linked.

**Comment by charlespierce** [comment]
I believe this may have been an issue with our documentation. Previously, the [getting started guide](https://docs.volta.sh/guide/getting-started) has as the first manual step: "Set the `VOLTA_HOME` environment variable to `"~/.volta"`", instead of `"$HOME/.volta"`, which would then cause this issue (and continue to persist through future installs).

We updated that documentation to indicate the correct value, so this shouldn't be a problem unless there is an outstanding setting somewhere using a quoted `~`
