### ISSUE TITLE
Unable to the install latest Volta (0.5.5)

### ISSUE THREAD

**Issue by AwakenedClaymore** [volta-cli/volta#488]
curl: (22) The requested URL returned error: 404 Not Found
Error: Could not download Volta version '0.5.5'. See https://github.com/volta-cli/volta/releases for a list of available releases

**Comment by chriskrycho** [comment]
Thanks for reporting this! We're digging into it now!

**Comment by charlespierce** [comment]
Hi @AwakenedClaymore, thanks for letting us know. It looks like some wires got crossed and the release files weren't available. They've been published now, so it should work if you try again.

Sorry about that!
