### ISSUE TITLE
Convert custom fallible `into_...` implementations to `TryFrom` implementations

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#489]
Rust 1.34.0 [stabilized] the [`TryFrom`] and [`TryInto`] traits. We have a number of conversion methods in our code which have signatures like `fn into_foo(bar: Bar) -> Fallible<Foo>`; all of these could be implemented using `TryFrom` instead, which would simplify call sites, allowing them to use `from` or `into` directly.

[stabilized]: https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html#tryfrom-and-tryinto
[`TryFrom`]: https://doc.rust-lang.org/stable/std/convert/trait.TryFrom.html
[`TryInto`]: https://doc.rust-lang.org/stable/std/convert/trait.TryInto.html

(I'm happy to mentor someone who wants a small first contribution through this one – it should be relatively mechanical, but it'd be a good way to get your feet wet in the codebase and it's valuable to us!)

**Comment by dagadbm** [comment]
hey!
so I am a currently a front end developer (worked with Java/C#/Python in the past).
I have no idea of how rust works but I know I like volta and I just used it on WSL on windows and on my mac to replace the god awful nvm .
I also wanted to get into open source but i have no idea where to start and this seems an "easy" find and replace. what can I do to help on this?

**Comment by chriskrycho** [comment]
Hey @dagadbm – welcome, we're glad to have you and happy to help you spin up a bit!

The gist is that a bunch of implementations that currently look like this:

https://github.com/volta-cli/volta/blob/1c8c9b2257bca69e883a89229715da10fef9469f/crates/volta-core/src/inventory/serial.rs#L128-L146

Will become this:

```rust
use std::convert:TryFrom;

impl TryFrom<NodeIndex> for <super::NodeIndex> {
    pub fn into_index(self) -> Fallible<super::NodeIndex> {
        let mut entries = Vec::new();
        for entry in self.0 {
            if let Some(npm) = entry.npm {
                let data = super::NodeDistroFiles {
                    files: HashSet::from_iter(entry.files.into_iter()),
                };
                entries.push(super::NodeEntry {
                    version: entry.version,
                    npm,
                    files: data,
                    lts: entry.lts,
                });
            }
        }
        Ok(super::NodeIndex { entries })
    }
}
```

I recommend digging in just a *little bit* into Rust docs first is because some of the functions which look like they *might* be amenable to this *aren't*, because they require some additional arguments.

My recommendation here would be to work through some of the pieces of [Rust by Example](https://doc.rust-lang.org/stable/rust-by-example/), specifically the basic language introduction bits and then the section specifically about [`From` and `Into`](https://doc.rust-lang.org/stable/rust-by-example/conversion/from_into.html). Then you'll want to look at the docs on [`TryFrom`](https://doc.rust-lang.org/1.34.1/core/convert/trait.TryFrom.html), which will be a helpful reference as you get going on this.

And of course you'll want to start by [installing Rust](https://rustup.rs)!

**Comment by dagadbm** [comment]
thx!  I already changed that file. Now onto reading stuff! I actually started with this https://learnxinyminutes.com/docs/rust/

**Comment by charlespierce** [comment]
It looks like the only one of these left in the code base that doesn't take additional arguments is in `toolchain/serial.rs`:

```rust
impl Platform {
    pub fn into_platform(self) -> Fallible<Option<PlatformSpec>> {
```

This specific case also appears to be one where it never fails (it returns a `Result`, but it always returns `Ok` and never `Err`), so it should be possible to convert this to a `From` implementation and get rid of the error type.

**Comment by sirreal** [comment]
I've opened https://github.com/volta-cli/volta/pull/907 for part of this and would appreciate feedback. Thanks!

**Comment by charlespierce** [comment]
Thanks for those PRs @sirreal, I think this is complete now! I've got an idea about how to make the to <-> from JSON conversion more explicit while still using `From` and `TryFrom`, but I think that's reasonably different and I'll open it as a separate issue.
