### ISSUE TITLE
Rename `user` to `default` throughout the code base

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#490]
As mentioned in the discussion of #470, we've stabilized on calling the "User" tools the "Default" versions, so we should update the code base to use that same terminology.

**Comment by rwjblue** [comment]
So we use "default" for things like `volta install ember-cli`, right? What do we call it when we fall back to the system version, just "system"?

**Comment by chriskrycho** [comment]
That sounds right to me, yeah.
