### ISSUE TITLE
Support version tags as well as semver in `volta install`

### ISSUE THREAD

**Issue by fortes** [volta-cli/volta#491]
Hi, thanks for making Volta! I've hit a minor issue, I'm trying to use volta to install [`reason-cli`](https://github.com/reasonml/reason-cli) tools globally. But in order to do so, I have to install a specific version for my platform (`latest-linux` in this case). This seems to run afoul of volta's version parsing:

```
error: Could not parse version "latest-linux"
```

Thanks!

**Comment by charlespierce** [comment]
Hi @fortes, thanks for reporting this! We don't currently support using tags for declaring the version when running `volta install`, though we have some work in progress to make it easier to resolve versions like that.

In the interim, you should still be able to use the actual version to install it, looking at the "Versions" tag [here](https://www.npmjs.com/package/reason-cli), it looks like `latest-linux` corresponds to version `3.3.3-linux-1`, so running `volta install reason-cli@3.3.3-linux-1` should work correctly.

**Comment by aknuds1** [comment]
I've run into the same issue as I try to install 'prisma@alpha'.
