### ISSUE TITLE
Couldn't find ~/.profile during install

### ISSUE THREAD

**Issue by elwayman02** [volta-cli/volta#494]
When running `volta-install`, the installation failed to find my user profile, even though I have an existing one at `~/.profile`.

```
  Installing latest version of Volta (0.5.6)
    Checking for existing Volta installation
    Fetching archive for macOS, version 0.5.6
######################################################################## 100.0%
    Creating directory layout
  Extracting Volta binaries and launchers
x volta
x shim
x load.fish
x load.sh
    Creating symlinks and shims
     Editing user profile ()
Error: No user profile found.

Tried $PROFILE (), ~/.bashrc, ~/.bash_profile, ~/.zshrc, ~/.profile, and ~/.config/fish/config.fish.

You can either create one of these and try again or add this to the appropriate file:

export VOLTA_HOME="$HOME/.volta"
[ -s "$VOLTA_HOME/load.sh" ] && . "$VOLTA_HOME/load.sh"

export PATH="$VOLTA_HOME/bin:$PATH"
```

**Comment by chriskrycho** [comment]
Thanks for the report! Can you also share:

- your shell
- your OS and version

We'll see if we can get a consistent reproduction!

**Comment by elwayman02** [comment]
iTerm2 - Build 3.2.9
OSX - 10.14.5

**Comment by MattiAstedrone** [comment]
This same happens to me with the amazonlinux docker which has ~/.profile

After starting the container, this can be reproduced by:
yum install -y openssl tar gzip sh
curl https://get.volta.sh | bash

**Comment by elwayman02** [comment]
@chriskrycho just to confirm, this bug still exists today in v0.6.3 of volta.

**Comment by charlespierce** [comment]
I believe this should be fixed by the improved profile detection logic. Feel free to re-open if that's not the case.
