### ISSUE TITLE
If `volta` command is unavailable, `volta-install` still thinks it's fully installed

### ISSUE THREAD

**Issue by elwayman02** [volta-cli/volta#495]
If you install `volta` but don't have your profile set up correctly to start it, running `volta-install` will see that volta is already installed and do nothing:

```
  Installing latest version of Volta (0.5.6)
    Checking for existing Volta installation
Version 0.5.6 already installed
```

As a user, my expectation would be that it tries to confirm that `volta` is available as a command, and if not, re-runs the portion of the script that attempts to set up your user profile.

**Comment by elwayman02** [comment]
Confirmed this still exists on `0.6.3`

**Comment by rolandin** [comment]
I think this is what's happening to me: 

`Rolandos-MacBook-Pro:~ roland$ curl https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11770    0 11770    0     0  23122      0 --:--:-- --:--:-- --:--:-- 23123
  Installing latest version of Volta (0.7.2)
    **Checking for existing Volta installation
Version 0.7.2 already installed**
Rolandos-MacBook-Pro:~ roland$ **volta install node@10.16.3**
-bash: **volta: command not found**
Rolandos-MacBook-Pro:~ roland$ `

I'm I right ?
What can I do to actually Install it ??

**Comment by rolandin** [comment]
I think this is what is happening to me:

**$ curl https://get.volta.sh | bash**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11770    0 11770    0     0  23122      0 --:--:-- --:--:-- --:--:-- 23123
  **Installing latest version of Volta (0.7.2)**
    **Checking for existing Volta installation**
**Version 0.7.2 already installed**
**$ volta install node@10.16.3
-bash: volta: command not found**
 
It's any way I can actually install Volta ???

**Comment by charlespierce** [comment]
Hi @rolandin! Do you have a `~/.bashrc` or `~/.bash_profile` file? Part of the install process makes changes to those files, but only if it can locate them.

If you do have those files and can see the changes (should be 2 lines that reference `VOLTA_HOME`), then after installing the first time, did you open a new terminal? Since the changes are made in your profile scripts, you need to open a new terminal (or source those files again) to make sure the changes are represented.

**Comment by rolandin** [comment]
@charlespierce  Hey Chalie! thanks for the quick reply!

This seems is my problem, I will go ahead and create the file and edit those variables mentioned in the Documentation, thank you

**Comment by charlespierce** [comment]
I believe this should be fixed now, we added logic to automatically create the appropriate profile script for the current shell, or show a warning when we were unable to create it. So you should get the correct indication if anything else is needed when installing Volta.
