### ISSUE TITLE
Volta ctrl-c exits too early

### ISSUE THREAD

**Issue by thoov** [volta-cli/volta#500]
Issue: When a subprocess does not exit immediately volta does not wait for it.

Steps to reproduce:

1. Create a file called `index.js` with the following contents:

```js
const sleep = seconds => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, seconds * 1000);
  });
};

process.on("SIGINT", function() {
  console.log("Caught interrupt signal");

  sleep(5).then(() => {
    console.log("exit");
    process.exit();
  });
});

sleep(100).then(() => {});
``` 

2. Run `node index.js`
3. Wait a few seconds and `ctrl-c`. You will see that the process immediately exits then 5 seconds later you will see an error.

If you run the above steps with volta deactivated you will see that node "waits" for the script to finish.

**Comment by charlespierce** [comment]
@thoov Thanks for reporting, and for the simple reproduction case! I did some early investigation into the signal handling and thought that it was handling it, but now I wonder if it isn't sending the signal to both processes simultaneously.

**Comment by charlespierce** [comment]
Related to #36
