### ISSUE TITLE
Is it possible to manually set the default node version?

### ISSUE THREAD

**Issue by FreeMasen** [volta-cli/volta#502]
My intention was to have my first `volta install node` be the default moving forward. I then went ahead and installed another version I wanted to use in another project and that became my default. Is there a way to manually set the global default version?

**Comment by charlespierce** [comment]
Hi @FreeMasen, yes, the way to set a global default version of node is using `volta install node[@version]`. That will make sure the specified version is available and set it as your default.

If you want to then set a different version for a specific node project, you can use `volta pin node[@version]`, which will add the `volta` key to that project’s `package.json`

After that, if you run `node` inside the project, it will use the local version defined in the project, and if you run `node` anywhere else, it will use the global default you picked with `volta install`

**Comment by FreeMasen** [comment]
So re-issuing the `volta install` command will reset my global default?

**Comment by charlespierce** [comment]
Yes, precisely.

**Comment by FreeMasen** [comment]
This is kind of confusing, I am curious what the appetite would be for adding something a little more obvious?

**Comment by charlespierce** [comment]
We're definitely always open to suggestions to improve the developer experience, as that's an important value for Volta. What is the main point of confusion, the name of the command itself (e.g. `volta install` doesn't really sound like a command that would change the default)?

**Comment by charlespierce** [comment]
Looking back at the original question, I think one important point is that the idea behind Volta is that you don't have to manually keep track of the node versions that are "installed" and available. If, at any point, Volta determines that it needs to use a version of Node that isn't fetched locally, it will download and install that version for you. So there's no need to "pre-install" versions that you think you'll need, you can just use them when they become necessary.

We can definitely do a better job of documenting that mental model for how the versions are managed.

**Comment by FreeMasen** [comment]
It seems strange to me that install does more than just install things. I can understand on first install setting that version as the default (since no default existed before) but after that first install I would expect install to just install things.

Say I have node version 11 installed and want to use it as my default. One day I am asked to work on an older project that needs node version 6. I would go ahead `volta install node@6` and now my global default has been changed.  I already have node version 11 installed, it doesn't seem obvious to me to re-run the install to revert my previous effort so now I have to pin all of my main working repos to version 11 to ensure that I don't inadvertently change the global default.

**Comment by FreeMasen** [comment]
I'm going to close this issue for now. I will try and write up an RFC about my experience and open up the decision to the community.

Thanks so much for such a prompt response and really impressive tool!!

**Comment by chriskrycho** [comment]
A couple quick notes here:

1. `volta fetch` does the part of just getting a version local to your machine and available (if you have a reason to do that).
2. `volta install` sets a global default.
3. `volta pin` sets a project-specific version.

For what you're doing, pinning is indeed what we recommend. Is there a reason to prefer *not* to use `volta pin` there?

**Comment by chriskrycho** [comment]
(For what it's worth: I totally get where you're coming from, especially from previous experience with other tools where I might have expected `volta install` to do what `volta fetch` does and `volta default` to do what `volta install` does instead—so my question above is definitely not an argument!)

**Comment by henrypalacios** [comment]
Quick question for the `volta pin`, why are you just not using the [standard configuration](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines) of settings for `engines`, like as:  
```javascript 
"engines": {
  "node": "12"
  }, 
````

**Comment by chriskrycho** [comment]
This comes up regularly (maybe we need an FAQ?); the short answer is that engines specify ranges and Volta always uses (and needs!) exact versions to accomplish its goals. For a deeper and longer explanation, see [here](https://github.com/volta-cli/volta/issues/742#issuecomment-631588143).

**Comment by pohl** [comment]
I feel like not having an obvious equivalent to nvm's `use` is short-sighted. There needs to be something in between `install` and `pin`. Imagine a developer who would merely like to use Volta locally before opening the consensus-building conversation to get their entire company to buy into it. Adopting nvm's `use` verb to change tho global default seems like low-hanging usability fruit.

**Comment by avionbg** [comment]
Coming from nvm, volta feels a bit confusing. It would help a lot having a command that could be used to switch the default node version between the installed versions.
It would give us more flexibility, like switching back to some previous node version (lets imagine the current node is breaking some packages). And we wouldn't need to go trough 20 or more projects and pin a specific version for each of them.

While this is possible with PIN, I would still prefer manual defaults (Maybe I'll switch to pin at some point)

And in this case it would be also beneficial to have a cmd switch to list all the currently installed node versions.

**Comment by chriskrycho** [comment]
As we've covered a couple times in this thread now, you can just use `volta install` to set the default, and if that version is already installed it won't bother hitting the network for it. 😄

As a meta comment: one challenge when designing a new tool is deciding how much to go with what you think the best interface is, vs. how much you should follow established norms around the ecosystem—and the more so when your tool does some things significantly differently from those existing tools! But as this thread suggests, even just providing a `volta default` alias for `volta install` might be a win. As we've noted, if someone wanted to write an RFC for that (it should be small) we'd happily iterate on it with you!

**Comment by ballPointPenguin** [comment]
I agree that this is confusing. I switch between node versions frequently outside of the context of a project with a package.json file. I see now that I can use `volta install` to switch global node versions but it is very non-obvious and not really documented. First I read the `--help` outputs in the terminal, then I browsed through the volta docs, I searched for "global" and didn't find what I was looking for. Then I started googling and eventually found this thread. So 10 minutes of hunting around and I have finally learned how to switch between installed node versions globally, akin to `nvm use`. I'm glad to see that I'm not the only one confused by this, but I'd like to see a little more empathy from the volta team beyond just "write an RFC" 🤷 .

**Comment by charlespierce** [comment]
@ballPointPenguin Apologies if the suggestion of an RFC came off as dismissive or not empathetic, that definitely wasn't our goal! We definitely agree there is confusion around the verbs used and would like to switch, I actually have a couple pages of notes that I took on my thoughts. It's more been an issue of time: I have those notes but haven't yet had the time to coalesce them into an RFC suggesting an improvement. I think we definitely will be making improvements to the language to make things more clear. A lot of our understanding and the model of Volta has evolved since its early days and improving the verbs we use for command can go a long way towards conveying that model intuitively.

**Comment by gayanath** [comment]
Very recently found Volta, and I love it! I too got into a similar confusion regarding the global node version. Just want to add my suggestion to the discussion: `What if we follow how npm handles local and global packages?`

```
volta install node # Installs the latest LTS in the current directory, and pins the packages.json
volta install -g node@17.7.1 # Installs version 17.7.1 globally
```

* Basically, `volta install` becomes `volta pin`.
* `-g` flag hints you are dealing with the global version. Can prevent accidentally changing global version.
* `install` for local and `install -g` for global are more familiar to the community due to the usage of `npm`.
* `pin` can stay as an alias to `install` or deprecated later.
* I understand this would be a uncomfortable change to the developers already got used to the install/pin workflow but it may not be much compared to newcomers of the tool having to get used to install/pin.

**Comment by yoni333** [comment]
> Hi @FreeMasen, yes, the way to set a global default version of node is using `volta install node[@version]`. That will make sure the specified version is available and set it as your default.
> 
> If you want to then set a different version for a specific node project, you can use `volta pin node[@version]`, which will add the `volta` key to that project’s `package.json`
> 
> After that, if you run `node` inside the project, it will use the local version defined in the project, and if you run `node` anywhere else, it will use the global default you picked with `volta install`

please just add this information in the docs. it will prevent from a lot of users to google "volta change default node version" .

**Comment by chriskrycho** [comment]
It's already on the very first page of the docs after installation instructions: https://docs.volta.sh/guide/understanding 😅

**Comment by fardarter** [comment]
This is a bad set of decisions

**Comment by rickvian** [comment]
install node version and setting default node should be two independent separate concern
