### ISSUE TITLE
`volta pin ...` removes a newline from the end of package.json

### ISSUE THREAD

**Issue by bmakuh** [volta-cli/volta#503]
I noticed that when I run `volta pin yarn` or `volta pin node`, the newline at the end of my package.json is removed and I have to manually add it back in. It's not a big deal, but I figured I'd report it.

## Current Behavior
it removes a newline from the end of package.json

## Expected Behavior
it does not remove a newline from the end of package.json

**Comment by chriskrycho** [comment]
Looks like this is a function of how serde_json's `PrettyPrinter` is implemented; see [here](https://github.com/serde-rs/json/issues/315). Our simplest solution is probably just checking if the original ends in a newline and adding it if so, given serde_json doesn't want to implement it (which seems reasonable, given that it's *effectively* a file-level parsing/writing issue here).

**Comment by rwjblue** [comment]
>  Our simplest solution is probably just checking if the original ends in a newline and adding it

Ya, definitely agree here.

**Comment by charlespierce** [comment]
Closed via #603
