### ISSUE TITLE
Does not work in Git Bash for Windows

### ISSUE THREAD

**Issue by lolmaus** [volta-cli/volta#504]
Hi!

Trying this:

```bash
lolmaus@WALDECK MINGW64 /c/Program Files
$ volta install peerflix
Package `peerflix` is up-to-date, version 0.39.0 already installed

lolmaus@WALDECK MINGW64 /c/Program Files
$ peerflix --help
'node' is not recognized as an internal or external command,
operable program or batch file.
```

It does work in regular Windows shell.

**Comment by lolmaus** [comment]
I've tried various terminals in [ConEmu](https://conemu.github.io/) and looks like Volta works fine with terminals based on cmd and PowerShell, but fails on terminals based on Bash: Bash, Git Bash and MinGW Bash.

Bash is essential to my dev workflow, reverting to a Windows-style shell is not an option for me. 😔

**Comment by lolmaus** [comment]
Hmm, looks like Volta requires activating a Node version separately!

Keeping this open to discus possible ways of improvement, since this minor thing set me back a great deal.

**Comment by charlespierce** [comment]
Hi @lolmaus thanks for reporting this! Volta shouldn't be requiring you to specify a Node version separate from installing a package. In fact the install process should be downloading a Node to use for the tool, and also using that same Node version for installing the dependencies of the tool you are installing.

What exactly was it that fixed the issue for you? Running `volta install node`?

**Comment by charlespierce** [comment]
For reference, I just tried after clean installing Volta 0.5.7 on a Windows 10 system, with Git Bash:

```bash
$ volta install peerflix
$ peerflix --help
```

I got the expected help output. What version of Git Bash are you using? And which version of Volta are you on?

**Comment by lolmaus** [comment]
Sorry for confusion. I misinterpreted the issue original.

Using latest version of Volta on Windows.

So I've installed Node via Volta using cmd.

Then I popped Git Bash open and was expecting Node to work there.

That was not the case. It only started working after repeating `volta install node@latest` in Git Bash.

**Comment by lolmaus** [comment]
Not sure if it's a bug or a documentation issue.

**Comment by charlespierce** [comment]
Hmm, that's interesting. I don't think I've tried that exact workflow, but it definitely should work across different prompts, so if it isn't then it's a bug! Thanks for reporting, I'll do some investigation and see if I can reproduce that behavior. Just in case it becomes relevant, what version of Git Bash are you using?

**Comment by lolmaus** [comment]
I'm using latest Git for Windows which comes with mintty.

Additionally, you can install either ConEmu or cmder for an easy way to start various prompts in various modes.

**Comment by charlespierce** [comment]
Hi @lolmaus I tried this again with the most recent installer, and I was able to install node on `cmd`, then run it successfully in Git Bash (and Powershell), without having to re-install it in each prompt. I also was able to do the same with `peerflix`, so I'm having some trouble tracking down exactly what is happening in your case.

Is it possible that the Git Bash terminal session was already open when you first ran the Volta installer? The installer makes changes to the PATH environment variables, and it wouldn't be surprising if Git Bash checks those when the terminal is created but then keeps them locally and doesn't update when the environment variables change while the terminal is still active.

**Comment by charlespierce** [comment]
Another possibility: Was this in Git Bash through VS Code? I know that VS Code does some strange caching of the terminal, so even if you open a "new" terminal through VS Code, it often doesn't pick up new environment variables or other System changes. You have to completely close VS Code and re-open it for the terminal to work correctly.

**Comment by lolmaus** [comment]
Works as expected for me now. Thx for your kind help!

**Comment by cfv1984** [comment]
Hi! I'm getting this

> Error: The current operating system (MINGW64_NT-10.0-19041) does not appear to be supported by Volta.

When I try to install volta from my random git bash cli. Works as expected when using the installer, but I'd wager this is a relatively common scenario so I thought I'd bring it over here.

**Comment by charlespierce** [comment]
Hi @cfv1984, thanks for bringing that up! I think we've seen that issue pop up before as well. I think we can probably mitigate it a bit by adding a note to our "Getting Started" page that specifically calls out Git Bash on Windows.
