### ISSUE TITLE
UTF-8 not supported on Windows

### ISSUE THREAD

**Issue by jonathandturner** [volta-cli/volta#507]
When doing an install, it looks like Volta wants to draw a utf-8 symbol, which would be fun except Windows cmd doesn't currently support it.

![image](https://user-images.githubusercontent.com/547158/62073174-4855d780-b294-11e9-8263-443249d0734a.png)

(or maybe the question mark is what is expected? unsure)

**Comment by charlespierce** [comment]
Hi @jonathandturner thanks for reporting this! That is a UTF-8 symbol (or rather a series of UTF-8 symbols as a "loading" animation). We can probably replace that on Windows with ASCII characters (`\` `|` `/` `-`) to achieve the same effect.
