### ISSUE TITLE
Support for non x86-64 architecture

### ISSUE THREAD

**Issue by chancancode** [volta-cli/volta#519]
Currently, if you run the install script on Linux + ARM (on a raspberry pi, for example) it will happily grab the x86-64 builds and fail to run them later:

```
pi@retropie:~ $ uname -m
armv6l
pi@retropie:~ $ volta install node@lts
-bash: /home/pi/.volta/volta: cannot execute binary file: Exec format error
pi@retropie:~ $ file $VOLTA_HOME/volta
/home/pi/.volta/volta: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5d87265dc84e804eb0c1719df31f1af33ac3550c, not stripped
```

I imagine this is probably a problem on 32-bit Linux too. Ideally, Volta would provide binaries for these platforms. At minimum, the install script should not conflate platform with architecture and error much earlier on.

**Comment by charlespierce** [comment]
Hi @chancancode, thanks for reporting this! We can definitely look into providing binaries for other platform + architecture combinations, but as a short-term improvement we can fail fast by detecting the architecture and notifying that we don't currently have pre-built binaries for a given arch.

**Comment by charlespierce** [comment]
Opened #520 to add the fail-fast behavior to the installer. The actual release of binaries for other architectures will likely need to be part of #379, building on different machines. Currently the release process is very manual and we don't have an easy way to create a build for multiple different architectures.

**Comment by chancancode** [comment]
@charlespierce sounds good to me!

**Comment by charlespierce** [comment]
The installer should now fail early on architectures for which we lack pre-built binaries. Added a comment to the automated build issue about including additional OS / architecture combinations, so closing this in favor of #379 as the main tracking for other architectures.
