### ISSUE TITLE
volta self-update

### ISSUE THREAD

**Issue by Stanzilla** [volta-cli/volta#521]
What's the best way to keep Volta itself uptodate? Any plans for a `volta self-update` command?

**Comment by rwjblue** [comment]
Yes, it is absolutely something the team is thinking about and working on. Please check out the RFC over at https://github.com/volta-cli/rfcs/pull/37 for more details. I'm certain that your feedback would be an awesome addition over there.

**Comment by Stanzilla** [comment]
@rwjblue thank you! Want me to close this ticket then or keep it open for tracking?

**Comment by charlespierce** [comment]
@Stanzilla We're actually tracking updates in #269 currently, so you can follow that for updates (as well as the RFC that was already linked).

As for keeping Volta up-to-date in the interim, the installer can actually handle upgrading in-place, so whenever there is an update, re-running the installer should get you the latest version. We currently are on a weekly release cycle, releasing on Mondays. We announce when a new release is available on the [discord](https://discord.gg/hgPTz9A) and on [twitter](https://twitter.com/usevolta) if you want to be notified that there's a new version available.
