### ISSUE TITLE
implement `volta list --format=human`

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#523]
Follow-on work for #461: finish implementing the `volta list --human` printer in line with the design from volta-cli/rfcs#34.

**Comment by seidtgeist** [comment]
Is there a way to set a default, or do I have to enter `volta list node --format=plain` every time I want to list node versions?

**Comment by chriskrycho** [comment]
There is not (though that's an interesting idea we should consider!), but follow-on work to make `list --format=human` (the default in a TTY) work is in progress now, at #697.

**Comment by seidtgeist** [comment]
Thanks for getting back! Yes, defaults rock, especially if there is no alternative. Plain is great, and I’m looking forward to human being implemented!

**Comment by chriskrycho** [comment]
@seidtgeist keep your eyes open for our next release; it'll contain the `--format=human` implementation!

**Comment by seidtgeist** [comment]
So cool, thank you!!

**Comment by olivierlacan** [comment]
Not sure when the next release is but in the meantime, it really feels like `volta list --format=plain`'s output is plenty sufficient. It's very strange to have to add a flag to a list command to get any useable output.

**Comment by DirtyF** [comment]
@olivierlacan latest release provides a list command without any args:

``` 
volta list
⚡️ Currently active tools:

    Node: v12.16.1 (default)
    npm: v6.14.5 (default)
    Yarn: v1.22.4 (default)
    Tool binaries available:
        eleventy (default)
        gridsome (default)
        lhci (default)
        tina (default)
        atomic-algolia (default)
        depcheck (default)
        devmoji (default)
        emoj (default)
        gatsby (default)
        hyperlink (default)
        kmdr (default)
        lerna (default)
        netlify, ntl (default)
        now (default)
        npm-check (default)
        prettier (default)
        regexp-tree (default)
        regexp-tree-cli (default)
        sharp (default)
        speed-test (default)
        surge (default)
        tailwind (default)
        tap-dot, tap-spot (default)
        vitepress (default)
        vuepress (default)
```

**Comment by chriskrycho** [comment]
Yep, 0.8.0 came out last week and has this feature. We just forgot to close this issue! (I’m doing so now, and thanks again to @haochuan for implementing it!)
