### ISSUE TITLE
Detach Volta for project that does not use Volta for node management

### ISSUE THREAD

**Issue by chsi022** [volta-cli/volta#532]
I am currently using `n` on my Mac for node version management and I am trialing out Volta and fairly impressed with its ability to manage node versions.

In my test project I used Volta and pinned a node version, it worked great, however, I found that there is no way for me to detach Volta from my other projects - which I want to keep using `n` for node management until we can confirm that Volta is the way to go.

Please advise if there is a way I can achieve this currently.

**Comment by charlespierce** [comment]
Hi @chsi022, glad to hear that it's working well in your tests so far! To your question, currently Volta will pass through to whatever else is available in the System `PATH` (which should include `n`) if it can't determine a version of Node to use. That would mean that as long as you don't have a default version selected (`volta install node`), then it should fall-back to whatever version `n` is using.

Unfortunately, we don't currently have a command to remove the default version (tracked in #327), however you can achieve that by removing the file `~/.volta/tools/user/platform.json`, which will remove the default version, allowing calls to `node` to fall through to the pre-existing system.

**Comment by chsi022** [comment]
Yeah, I guess my request kind of doesnt make sense to start with - I shouldn't expect to use 2 different tools to manage node versions. But anyways, thank you for clarifying this for me. I'll mark this one as closed.
