### ISSUE TITLE
Volta should install itself into all available shells

### ISSUE THREAD

**Issue by chancancode** [volta-cli/volta#535]
If I install Volta from zsh, Volta seems to only install it into `.zshrc`.

* It should probably prefer `*profile` over `*rc`?
  * Otherwise, it will not work in non-interactive shells, I think
* It should install itself into all available shells (i.e. bash, sh)
  * Otherwise, shell scripts that runs in bash or sh (and did not inherit ENV variables from a parent interactive shell with Volta loaded) won't work

**Comment by mcarifio** [comment]
I ran into this recently while writing a script using volta. Source `load.{sh,fish}` at the beginning of the script, e.g. `source $VOLTA_HOME/load.sh`.

In the case of "non interactive shells", ~/.bashrc stops configuring stuff pretty early, e.g.:
```bash
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```. So you need to source `${VOLTA_HOME}/load.*` before that. I think.
