### ISSUE TITLE
Investigate using local `.npmrc` settings for global installs

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#540]
Currently, if you try to install a package from a local repository which also has dependencies that are only in that local repo, you need a workaround:

```
$ NPM_CONFIG_USERCONFIG="$PWD/.npmrc" volta install some-local-pkg
```

This is because the npm config information is used for the package download, but not for installing its dependencies. Installing the dependencies uses the public npm repo, so anything that is not available there will fail.

We need a way to preserve the npm configuration and use it for the dependency install as well.

**Comment by hugo-marques-m3** [comment]
I'm not sure if this is the same issue as @mikrostew is reporting but I can't seem to be able to install any package from an authenticated private repo. I've tried your the workaround and it doesn't seem to work.

**Comment by charlespierce** [comment]
@hugo-marques-m3 Thanks for adding your experience. To dig in a little deeper, when you say it's an "Authenticated private repo", does that mean that in your non-Volta workflow, when you run `npm i -g <package>` it asks for your credentials and you have to type them in? Or are your credentials set in some way in your `.npmrc` file?

If it's the former, what is the behavior you see from `volta install <package>`, does it hang for a long time, or does it error out immediately?

**Comment by hugo-marques-m3** [comment]
Hi @charlespierce, I have the following in a `.npmrc` where REGISTRY and TOKEN are the right values:
```
//{REGISTRY}/:_authToken="{TOKEN}"
registry=https://{REGISTRY}/
always-auth=true
```
It falls over immediately with a 403 response.

**Comment by fusion2004** [comment]
@charlespierce @hugo-marques-m3 I am seeing the exact same thing. We are attempting to build and globally use a cli tool we have in a gemfury private registry, which requires a token to interact with (in the config format that @hugo-marques-m3 provided).

From what I can tell from looking at the yarn & npm source code, it looks like the registry expects an `Authorization` header sent with `Bearer {TOKEN}` (replacing `{TOKEN}` with the values in our configuration, as per @hugo-marques-m3's example) when downloading the tarballs.

I can see where that download happens in this chain:
https://github.com/volta-cli/volta/blob/b37e0889853f6884ae7e3191576529a06262dcae/crates/volta-core/src/tool/package/fetch.rs#L38
https://github.com/volta-cli/volta/blob/b37e0889853f6884ae7e3191576529a06262dcae/crates/volta-core/src/tool/package/fetch.rs#L84
https://github.com/volta-cli/volta/blob/master/crates/archive/src/tarball.rs#L72

Additionally, npm does not allow you to retrieve these configuration values through the CLI:
```
$ npm config get //npm.fury.io/username/:_authToken
npm ERR! ---sekretz---

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2019-09-17T21_42_04_450Z-debug.log
```

Unfortunately, I don't think I am nearly an experienced enough Rustacean to produce a PR that can find & parse the `.npmrc` file for the correct auth token, and then add the `Authorization` header to the tarball download request.

**Comment by charlespierce** [comment]
Hi @fusion2004, thanks for digging in and investigating this! That makes a lot of sense, as the `reqwest` call is the only one that we don't use `npm` for, so it's the only one that doesn't have `npm`s authentication logic built-in.

I like the suggestion of using `npm pack`, as you note, we already require `npm` to be available for installing packages, and that will let us pull in npm's authentication logic automatically.

I _do_ think, at some point, there may be something to gain from porting pieces of `npm` and `yarn` to Rust in order to use them internally, but at the moment, taking advantage of what has already been written makes the most sense.

**Comment by vjleblanc** [comment]
@charlespierce and @fusion2004 Would it make sense to use `npm pack` instead of `npm view`? It looks like pack would directly resolve the tarball (in the same way view currently does). Moreover, it looks like you could use git urls as well. That would address #472 perhaps?

**Comment by charlespierce** [comment]
The authentication issue described by @fusion2004 and @hugo-marques-m3 should be fixed by #554 (thanks @fusion2004!) That will be released on Monday, October 10, most likely as version `0.6.4`.

There is still some value to this ticket tracking the possibility of propagating the npm configs from a local folder to the pack / install folders, so that this will work if you don't have a global `.npmrc` but run the command from a package that _does_ have one.

**Comment by hugo-marques-m3** [comment]
Thanks all for this. Btw, what happens when there's a new version? Does Volta warn the users? Do we need to run a command?

**Comment by charlespierce** [comment]
@hugo-marques-m3 Currently there is no in-terminal warning or updating behavior. We announce new versions on Discord and Twitter, and we generally try to release once a week on Mondays (though the past month we haven't had any new changes as people have been away). When a new version comes out, the upgrade process is currently running the installer again, which will do any changes needed.

We also currently have an RFC for improving updates to support automatically keeping the user up-to-date: https://github.com/volta-cli/rfcs/pull/37 The implementation for that is actively being developed right now, so we'll have a better experience around updating Volta soon.

**Comment by hugo-marques-m3** [comment]
Thanks @charlespierce! That sounds great 👍
I'll follow on Twitter to keep an eye for new versions coming out.

**Comment by charlespierce** [comment]
With the release of Volta 0.9.0, we now use the package manager directly when installing packages. This means that we will use the semantics that the package managers use (which I _believe_ is to respect the local `.npmrc` even when doing a global install, but is definitely up to the package managers themselves).
