### ISSUE TITLE
killing ember serve doesn't full terminate the process

### ISSUE THREAD

**Issue by willashley23** [volta-cli/volta#543]
When I run my ember server, and kill it with control+c, and immediately afterwards try to re-run it with `yarn && ember serve`, it will say `port 4443 is in use`, and hang. If I kill it again and try once more, it will work, and I run into this issue consistently. This wasn't an issue prior to switching to Volta, so I think it isn't correctly terminating the process on the port.

**Comment by rwjblue** [comment]
Can you share your `volta --version`?

**Comment by willashley23** [comment]
@rwjblue `0.6.0`

**Comment by charlespierce** [comment]
Hi @willashley23, we actually fixed that issue in Volta `0.6.1`, see #513 

If you upgrade to the latest (running the installer again should get the latest version), it should work as expected with Ctrl+C
