### ISSUE TITLE
Show package name on install error

### ISSUE THREAD

**Issue by bbkane** [volta-cli/volta#545]
I'm hoping I can use `volta` to install `elm` tooling. So I installed it, and ran the following:

```bash
λ volta install elm elm-live elm-test elm-fromat @elm-tooling/elm-language-server
success: installed elm@0.19.0-no-deps with executables: elm
success: installed elm-live@4.0.0 with executables: elm-live
success: installed elm-test@0.19.0-rev6 with executables: elm-test
error: Could not download package metadata.

Please verify that the package name is correct, and you have Node installed (using `volta install node`).
```

Looking at it, I can see that I miss-spelled `elm-format`, but that's not evident in the error message. It would be nice if the line was changed to:

```
error (elm-fromat): Could not download package metadata.
```

to make debugging this easier.

**Comment by charlespierce** [comment]
Hi @bbkane, this is a great suggestion, thanks! It should be relatively straightforward to add the package name to the error message.
