### ISSUE TITLE
Need suggestion

### ISSUE THREAD

**Issue by thoov** [volta-cli/volta#546]
Say we have package `foo` and `bar` like so:

```
/foo/package.json
/foo/index.js
/bar/package.json
```

The contents of `foo/index.js` is:

```js
console.log(process.version);
```

Inside of foo, node has been pinned to node@8 and within bar it is pinned to node@12.

Now if you are inside of bar and run:

```
node ../foo/index.js
```

You will get `v12.10.0`. However I would like node to be resolved to the version that is defined in foo (node@8). Is this possible / how can I "unset" or tell volta to not use the currently defined version?

**Comment by thoov** [comment]
Basically I want something like:

```
volta use node@8 && node ../foo/index.js
```

or something like:


```
volta inherent ../foo/ && node ../foo/index.js
```

**Comment by charlespierce** [comment]
This seems like a good use case for a `volta run` type command that we have talked about wanting. It would let you run any command with a node or yarn version specified on the command line.

Something like `volta run --node 8 node ../foo/index.js`

**Comment by thoov** [comment]
@charlespierce Ya I think `run` would be perfect here

**Comment by charlespierce** [comment]
Missed this when landing `volta run`, we now support that command.
