### ISSUE TITLE
Binary installed through volta cannot find another binary installed through volta

### ISSUE THREAD

**Issue by Samsinite** [volta-cli/volta#551]
```
Samuels-MacBook-Pro:chapter-three samueljclopton$ volta install purescript bower pulp
Package purescript@0.13.3 is already installed
Package bower@1.8.8 is already installed
Package pulp@13.0.0 is already installed
Samuels-MacBook-Pro:chapter-three samueljclopton$ pulp init
* ERROR: `purs` executable not found.
```

I can definitely see that the volta shims are in my path:
`Samuels-MacBook-Pro:chapter-three samueljclopton$ echo $PATH`
`/Users/samueljclopton/.volta/bin`:/Users/samueljclopton/.cargo/bin:/Users/samueljclopton/.rbenv/shims:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/samueljclopton/Library/Android/sdk/tools:/Users/samueljclopton/Library/Android/sdk/tools/bin:/Users/samueljclopton/Library/Android/sdk/platform-tools:/Users/samueljclopton/Library/Android/sdk/tools:/Users/samueljclopton/bin:/Applications/Postgres.app/Contents/Versions/10/bin

The contents of `/Users/samueljclopton/.volta/bin` also look ok:
```
Samuels-MacBook-Pro:chapter-three samueljclopton$ ls -la /Users/samueljclopton/.volta/bin
total 0
drwxr-xr-x  10 samueljclopton  staff  320 Sep 18 13:03 .
drwxr-xr-x  11 samueljclopton  staff  352 Sep 18 13:03 ..
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 bower -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 ember -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 node -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 npm -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 npx -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 pulp -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 purs -> /Users/samueljclopton/.volta/shim
lrwxr-xr-x   1 samueljclopton  staff   33 Sep 18 13:03 yarn -> /Users/samueljclopton/.volta/shim
```

But, most interesting, a simple shim of `purs` using bash seems to work fine:
```
#!/bin/bash

/Users/samueljclopton/.volta/tools/image/packages/purescript/0.13.3/purs.bin "$@"
```

So, this seems like an issue with Volta.

**Comment by charlespierce** [comment]
Hi @Samsinite, this definitely is a known issue with Volta. We've talked through this issue a couple of times, and don't yet have a perfect solution. Currently, the proposal is in #492, however there's definitely still an open question as to how we resolve the issue as a whole.

**Comment by Samsinite** [comment]
Sounds good, I'll close this and keep an eye on that issue. Thanks!
