### ISSUE TITLE
[Updates] Remove 'volta activate' and 'volta deactivate'

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#562]
`volta deactivate` (and later `volta activate`) are commands that were added early on as an escape hatch for when Volta wasn't working right and we needed to give a quick escape for our beta users. As Volta has matured and stabilized, they have become less important.

Making these two commands work requires additional setup and for `volta` to be implemented as a shell function wrapper that calls out to the Volta binary. This implementation is major roadblock in supporting #222, as well as resulting in a number of other issues: #216, #165, #104, and #99.

Beyond the issues that result from the function wrappers, they also make it more difficult to install Volta in a "traditional" way by putting the binary directly on the `PATH`. That is an approach we want to take to support [automatic updates](https://github.com/volta-cli/rfcs/pull/37), so we also have pressure from that direction to remove the function wrapper (and as a result, the `activate` and `deactivate` commands).

For all these reasons, the commands `volta activate` and `volta deactivate` should be deprecated and then removed.

**Comment by rwjblue** [comment]
I'd like to see this considered blocked on https://github.com/volta-cli/volta/issues/292. Without a way to `volta pin npm` _or_ `volta deactivate`, I'd have to modify my shell config in order to debug issues with specific `npm` versions (e.g. https://github.com/emberjs/data/issues/6589).
