### ISSUE TITLE
Volta uses incorrect node version for global package

### ISSUE THREAD

**Issue by claydiffrient** [volta-cli/volta#582]
I'm attempting to install the `gatsby-cli` utility and this is how it goes:

```bash
~/PersonalProjects
❯ volta install node@12                                                                                       9:20:49
success: installed and set node@12.13.0 (with npm@6.12.0) as default

~/PersonalProjects
❯ volta install gatsby-cli                                                                                    9:20:55
success: installed gatsby-cli@2.8.5 with executables: gatsby

~/PersonalProjects 8s
❯ volta list --format=plain                                                                                   9:21:11
runtime node@12.13.0 (default)
package-manager yarn@1.17.3 (default)
package gatsby-cli@2.8.5 / gatsby / node@13.0.1 npm@built-in (default)
package gerrit-cli@1.0.0 / gerrit, ger / node@12.10.0 npm@built-in (default)
package hotel@0.8.7 / hotel / node@12.10.0 npm@built-in (default)
```

If you notice `gatsby-cli` ends us getting installed with `node@13.0.1` rather than `node@12.13.0` as I would expect.  I probably normally wouldn't care, but `gatsby-cli` doesn't currently seem to work with `node@13.0.1`.

**Comment by charlespierce** [comment]
Hi @claydiffrient, we've actually got this tracked as #480. Currently what we are doing is using the lastest Node that matches the `engines` field, and if there isn't one (as appears to be the case for `gatsby-cli`), then we default to `node@latest`. The proposed solution is to use the latest _LTS_ version that fits the `engines`, or the most recent LTS if there isn't an engines field at all.

Until we implement that (or `gatsby-cli` updates to support Node 13), we actually don't have a command to edit the version of Node that binaries use. You _can_ however, manually edit 2 files to achieve the same result:

In both `~/.volta/tools/user/bins/gatsby.json` and `~/.volta/tools/user/packages/gatsby-cli.json`:

```diff
  "platform": {
    "node": {
-      "runtime": "13.0.1",
+      "runtime": "12.13.0",
      "npm": null
    }
```

**Comment by claydiffrient** [comment]
@charlespierce Thanks for letting me know.  I thought I'd searched through the issues enough to have found any other issue filed about this.  Thanks for letting me know this workaround.  I'll close this issue.
