### ISSUE TITLE
Could not parse version with letters inside

### ISSUE THREAD

**Issue by probil** [volta-cli/volta#583]
I can't install specific version of the package because volta couldn't parse version number despite it's a valid version for node.

I suppose volta validates version by semver .
```
$ volta install elm@elm0.19.0
error: Could not parse version "elm0.19.0"
```

**Comment by charlespierce** [comment]
Hi @probil, thanks for bringing this up! We actually have this tracked as #491, as the version string `elm0.19.0` is, as far as `npm` is concerned, a tag, not an actual version name. Though we don't currently support this, we actually have made a number of architectural changes recently that should make adding support for tags relatively straightforward.

Until then, however, you can use the suggestion from the linked issue, looking at https://www.npmjs.com/package/elm under "Versions", the tag `elm0.19.0` appears to point at the version `0.19.0-no-deps`, so you can run `volta install elm@0.19.0-no-deps` and get that version installed.

**Comment by probil** [comment]
Oh, I didn't know that there is such a thing as _tags_ in npm. :thinking: 
I'll give it a try. 
Thanks for your response @charlespierce

**Comment by probil** [comment]
Thanks @charlespierce
Your suggestion helped to resolve the issue
I'm closing it in favor of #491
