### ISSUE TITLE
volta.sh is down

### ISSUE THREAD

**Issue by lhorie** [volta-cli/volta#588]
Repro: go to http://volta.sh

Expected: a website
Actual: hangs

get.volta.sh also hangs, preventing it from being downloaded

**Comment by charlespierce** [comment]
Hi @lhorie, thanks for reporting this! It looks like this is an underlying issue with the Netlify CDN that hosts the Volta website. Hopefully this will be resolved soon, but it doesn't look like it's anything we can do from our side at the moment. See https://www.netlifystatus.com/incidents/2hn44zlbyh6h

If it goes on for long, however, we'll need to look into alternative hosting for our website and docs.

**Comment by lhorie** [comment]
I see. Thanks for the quick response!

**Comment by lhorie** [comment]
Seems to be back up
