### ISSUE TITLE
download and cache latest version of yarn

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#59]
Notion should download and cache the latest version of yarn.

A tarball of the latest version of yarn can be found at https://yarnpkg.com/latest.tar.gz

The version for this is located at https://yarnpkg.com/latest-version, which returns a text string (currently `1.6.0`)

From https://yarnpkg.com/en/docs/install#alternatives-stable, this download can be verified like so:

```
wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --import
wget https://yarnpkg.com/latest.tar.gz.asc
gpg --verify latest.tar.gz.asc
# Look for "Good signature from 'Yarn Packaging'" in the output
```

**Comment by alexlafroscia** [comment]
This is probably ready to be closed, right?

**Comment by charlespierce** [comment]
Yeah, I think so. We don't actually cache the latest version, but we use the Yarn-provided API for that, and we cache each version that we actually download.
