### ISSUE TITLE
Installer reports success if profile is not writeable, but fails to modify it

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#591]
This is an issue when installing on a "clean" OSX machine.

Permissions for `.bash_profile` are `root:staff` (instead of `<user>:staff` as expected), so it is not writeable by the user.

When volta tries to install, it indicates that bash_profile cannot be updated, but then reports a successful completion of the installation process:

## Repro

```
$ mv ~/.volta ~/.volta-bak

$ sudo chown root:staff ~/.bash_profile

$ curl https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16821    0 16821    0     0  24994      0 --:--:-- --:--:-- --:--:-- 24956
  Installing latest version of Volta (0.6.5)
    Checking for existing Volta installation
    Fetching archive for macOS, version 0.6.5
######################################################################## 100.0%
    Creating directory layout
  Extracting Volta binaries and launchers
x volta
x shim
x load.bash
x load.fish
x load.sh
    Creating symlinks and shims
     Editing user profile (/Users/mistewar/.bash_profile)
main: line 217: /Users/mistewar/.bash_profile: Permission denied
    Finished installation. Open a new terminal to start using Volta!
```

**Comment by chriskrycho** [comment]
@charlespierce @mikrostew what's the status on this bug? Can we close it?

**Comment by charlespierce** [comment]
@chriskrycho Almost, I think. The fix, as mentioned above, has been merged, but until we release the 0.7.0 version and update the installers, I think we should leave this open.

**Comment by chriskrycho** [comment]
Got it. 👍 Thanks!

**Comment by charlespierce** [comment]
Missed this earlier in the year, but we release Volta 0.7.0 some time ago, which does fix this issue. We also recently improved the support for writing config files, adding a warning if we expected to find a file and weren't able to locate it or create it.
