### ISSUE TITLE
download nightly version of yarn

### ISSUE THREAD

**Issue by mikrostew** [volta-cli/volta#60]
Notion should have an option to download nightly versions of yarn.

Latest nightly version is at https://nightly.yarnpkg.com/latest.tar.gz

There is more info about the various latest builds at https://nightly.yarnpkg.com/latest.json
(js, deb, rpm, js-legacy, tar, msi)

Info for all builds of each type are at https://nightly.yarnpkg.com/TYPE-builds,
where TYPE is one of `js, deb, rpm, js-legacy, tar, msi`

See also https://yarnpkg.com/en/docs/nightly

**Comment by charlespierce** [comment]
Closing as we now download Yarn from the `npm` registry (at least for Yarn 1, Yarn 2 has its own distribution channel and is tracked in #651).
