### ISSUE TITLE
Yarn / NPM installing incorrect binary for gRPC

### ISSUE THREAD

**Issue by scull7** [volta-cli/volta#605]
I'm running into an issue where `npm` seems to be building and installing incorrect versions of binary modules.  Specifically it's the gRPC binary.  I've tried `npm rebuild` but it results in the same error (see below)

OS: macOS Catalina 10.15.1
Volta: 0.6.6
Node: v12.13.0
NPM: 6.12.0
Yarn: 1.19.1

I've ensured that all `yarn`, `node` and `npm` are executing from the proper `.vola` bin link.  I've also attempted to execute them directly with no effect on the outcome.  

Anyone have any ideas? 

```sh
0|dda:crypt:grpc  | Error: Failed to load gRPC binary module because it was not installed for the current system
0|dda:crypt:grpc  | Expected directory: node-v79-darwin-x64-unknown
0|dda:crypt:grpc  | Found: [node-v72-darwin-x64-unknown]
0|dda:crypt:grpc  | This problem can often be fixed by running "npm rebuild" on the current system
0|dda:crypt:grpc  | Original error: Cannot find module '/Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node'
0|dda:crypt:grpc  | Require stack:
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/src/grpc_extension.js
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/src/client_interceptors.js
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/src/client.js
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/index.js
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/mali/lib/app.js
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/src/main.js
0|dda:crypt:grpc  | - /Users/nathansculli/src/cardcorp/dda/containers/crypt/bin/grpc-server.js
0|dda:crypt:grpc  |     at Object.<anonymous> (/Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/src/grpc_extension.js:53:17)
0|dda:crypt:grpc  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|dda:crypt:grpc  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
0|dda:crypt:grpc  |     at Module.load (internal/modules/cjs/loader.js:914:32)
0|dda:crypt:grpc  |     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
0|dda:crypt:grpc  |     at Module.require (internal/modules/cjs/loader.js:956:19)
0|dda:crypt:grpc  |     at Module.Hook._require.Module.require (/Users/nathansculli/.volta/tools/image/packages/pm2/4.1.2/node_modules/require-in-the-middle/index.js:70:39)
0|dda:crypt:grpc  |     at require (internal/modules/cjs/helpers.js:74:18)
0|dda:crypt:grpc  |     at Object.<anonymous> (/Users/nathansculli/src/cardcorp/dda/containers/crypt/node_modules/grpc/src/client_interceptors.js:144:12)
0|dda:crypt:grpc  |     at Module._compile (internal/modules/cjs/loader.js:1063:30) {
0|dda:crypt:grpc  |   code: 'MODULE_NOT_FOUND'
0|dda:crypt:grpc  | }
```

**Comment by charlespierce** [comment]
Hi @scull7, that's a strange one. I'll admit to not having any experience with gRPC, but from that stack trace, it looks like something within gRPC in your package is calling out to a global tool (`pm2`?), which is then failing to find the right binaries.

What command are you running that is causing this error to show? Can you show the output when you run the command with `VOLTA_LOGLEVEL=debug` set as an environment variable? My intuition is that this is a result of the global tools having a sandboxed version of Node, conflicting with the local version, but that output would likely make it more clear.

**Comment by scull7** [comment]
I think you may be correct with your thought that there's 2 node versions, but I haven't found any evidence to support that.

I set `VOLTA_LOGLEVEL=debug` inside the `pm2` configuration but nothing was printed within the `pm2` managed logs.  The log output remains the same as above.

However, I did see some new output from the `yarn start` side of the command. Here's the output of calling `yarn start` with `VOLTA_LOGLEVEL=debug` set:
```sh
yarn start                  
[verbose] Found project manifest in '/Users/nathansculli/src/cardcorp/dda/containers/crypt'
[verbose] Found default configuration at '/Users/nathansculli/.volta/tools/user/platform.json'
[verbose] Using yarn@1.19.1 from default configuration
yarn run v1.19.1
$ yarn stop && yarn start:dev
$ pm2 delete ecosystem.config.js
[verbose] Found project manifest in '/Users/nathansculli/src/cardcorp/dda/containers/crypt'
[verbose] Found default configuration at '/Users/nathansculli/.volta/tools/user/platform.json'
[verbose] Found default pm2 in '/Users/nathansculli/.volta/tools/image/packages/pm2/4.1.2/bin/pm2'
[verbose] Using node@13.1.0 from binary configuration
[PM2] Spawning PM2 daemon with pm2_home=/Users/nathansculli/.pm2
[PM2] PM2 Successfully daemonized
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
[verbose] No custom hooks found
$ pm2 start ecosystem.config.js --watch
[verbose] Found project manifest in '/Users/nathansculli/src/cardcorp/dda/containers/crypt'
[verbose] Found default configuration at '/Users/nathansculli/.volta/tools/user/platform.json'
[verbose] Found default pm2 in '/Users/nathansculli/.volta/tools/image/packages/pm2/4.1.2/bin/pm2'
[verbose] Using node@13.1.0 from binary configuration
[PM2][WARN] Applications dda:crypt:grpc not running, starting...
[PM2] App [dda:crypt:grpc] launched (1 instances)
┌────┬─────────────────────────┬─────────┬─────────┬──────────┬────────┬──────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                    │ version │ mode    │ pid      │ uptime │ ↺    │ status   │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────────────┼─────────┼─────────┼──────────┼────────┼──────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ dda:crypt:grpc          │ 1.0.0   │ fork    │ 83937    │ 0s     │ 0    │ online   │ 0%       │ 14.2mb   │ nat… │ enabled  │
└────┴─────────────────────────┴─────────┴─────────┴──────────┴────────┴──────┴──────────┴──────────┴──────────┴──────────┴──────────┘
[verbose] No custom hooks found

```

**Comment by charlespierce** [comment]
Okay, I think I see what's happening here: Your project's `yarn` scripts are calling `pm2`, but that package isn't defined as a dependency within your project, so it's calling out to the global version, which currently has a different version of Node associated with it than your project does.

The recommended way to resolve this, since your package (within `cardcorp/dda/containers/crypt` depends on the package `pm2`, is to add that as a dependency of your project directly (likely as a `devDependency` if it isn't needed in production). Then the local version will be called instead of the global version, meaning everything will be using the same version of Node.

**Comment by scull7** [comment]
`pm2` is a process manager, we have many different projects which utilize `pm2` in this role.  I installed `pm` using `volta install pm2`. How did it get a different version of node?

**Comment by charlespierce** [comment]
One of the problems we were trying to solve with Volta is that when you have different versions of Node, you often wind up having to re-install every global package for every different version. To avoid that, when you install a package with Volta, it gets its own version of Node, separate from anything else. This ensures that you can continue to use the tool, even if you switch your global node version, without having to reinstall anything.

Unfortunately, that also means that in situations like this, there can be a conflict between the version a tool has globally and a local project. We recommend having any tools you need for a project as dependencies, first because it resolves this issue, but more generally, because it ensures that the project is self-contained. If you rely on a globally installed tool, then when someone new starts working on a project, they have to remember to install that tool globally. Also, if multiple projects rely on that tool, but need different versions, then you get a whole different class of problems. Those situations are what lead us to setting Volta up to work the way it currently does.

**Comment by scull7** [comment]
I understand the reasoning for requiring things to have their own version of node in the common case.  However, with with a process manager, it should run with the current system version of node.  I can see that this may very well be an issue with the `pm2` implementation.  But having multiple versions of your process manager, managing different projects is likely not what you want.

That being said, I'm still not sure how `pm2` received its own version of node which was different than the node version for my project, considering I only executed `volta install node` exactly one time.

**Comment by charlespierce** [comment]
All that said, one problem we currently have is that the Node version we pick for a given package is either:
* The latest version of Node that satisfies the requirements in the `engines` key for that package
* The overall latest version of Node if there isn't an `engines` key in `package.json`

Unfortunately, our default version when you run `volta install node` (and the most commonly used version in our experience) is the latest LTS version of Node. This leads to a common mismatch where the packages are on Node 13, while everything else is on Node 12. I have a PR open right now #604 that improves on that, instead pinning a tool to the latest LTS that matches `engines` (or latest LTS overall), so there's a higher likelyhood of things aligning correctly.

**Comment by charlespierce** [comment]
We've also discussed (but not yet planned) adding options to `volta install`, to allow you to choose a version to use, something like:
```
$ volta install --node 12 pm2
```
Which would give you control over the version that is pinned.

**Comment by scull7** [comment]
> I have a PR open right now #604 that improves on that, instead pinning a tool to the latest LTS that matches engines (or latest LTS overall), so there's a higher likelyhood of things aligning correctly.

Yes, I believe that this would have avoided the issue, because node 13 is module version 79 and 12 (the lts release) is module version 72.  Which is the situation being described in the error message:
```sh
0|dda:crypt:grpc  | Expected directory: node-v79-darwin-x64-unknown
0|dda:crypt:grpc  | Found: [node-v72-darwin-x64-unknown]
```

Node version information: https://nodejs.org/en/download/releases/
