### ISSUE TITLE
DX improvement between default version and user's version

### ISSUE THREAD

**Issue by haochuan** [volta-cli/volta#609]
## Use case 

Let's say I have a `volta` enabled project with `package.json`: 

```
{
  "name": "my-awesome-package",
  "version": "1.0.0",
  "volta": {
    "node": "12.13.0"
  }
}
```

I want to update the `node` version from 12 to 8 in my project. Instead of `volta pin node@8`, I feel like it's happening a lot that people will try to run `volta install node@8`. This will show the message below:

<img width="645" alt="Screen Shot 2019-11-19 at 09 49 26" src="https://user-images.githubusercontent.com/2744803/69172027-ea066c00-0ab1-11ea-8bd2-905c5e733543.png">

When I see the message I always feel like I'm using node@8 in my project now. However, So the default node became @8 and project's node is still @12.

## Suggestion

After you run `volta install node/yarn` inside a volta enabled project, it's better to let people know what's the default version and what's the projects's version, like:

```
success: installed and set node@8.12.0 (with npm@6.4.1) as default
You are using node@12.13.0(with npm@xxx) in the current project.
```

**Comment by locks** [comment]
I just stumbled unto this and the extra messaging would have been nice!
