### ISSUE TITLE
Support for package without an executable

### ISSUE THREAD

**Issue by xg-wang** [volta-cli/volta#624]
https://github.com/sindresorhus/alfred-npms is a package that runs `postInstall`. volta doesn't allow me to install it. My current workaround is to clone it locally and run `npm install`

**Comment by charlespierce** [comment]
Hi @xg-wang, thanks for bringing this use-case up! For the sake of keeping all the information about global install issues, I'm going to roll this into #555, which has a number of other use-cases for global installs / spots where installing a package doesn't work.
