### ISSUE TITLE
Add flag to skip shell configuration in volta setup

### ISSUE THREAD

**Issue by frangio** [volta-cli/volta#632]
The new `volta setup` command changes the shell profile files. I would like the possibility of skipping this so that I can do it manually.

**Comment by charlespierce** [comment]
Hi @frangio! Currently changing the shell profile files is the only unique thing that `volta setup` does, so an option to skip that would mean it was effectively a no-op. What is the use-case where you want / need to call `volta setup` but don't want to modify the profile scripts?

Or is this as part of the installer process where you would want to skip modifying the profile?

**Comment by frangio** [comment]
Oh, I assumed that it also created the `node`, `npm`, etc. symlinks. Are those not necessary anymore?

**Comment by charlespierce** [comment]
@frangio Those are necessary, however with the new migration behavior that was also added along with `volta setup`, any Volta command will generate them if they don't exist. So if you're looking to enable Volta for a new user, and are already managing their profile to include Volta, then you can run any Volta command, including something informational like `volta --version`, and all of the necessary changes to the file system (creating the `~/.volta` directory and the associated shim symlinks) will be made.

**Comment by frangio** [comment]
Thanks for clarifying!
