### ISSUE TITLE
Volta does not detect system installations

### ISSUE THREAD

**Issue by therealparmesh** [volta-cli/volta#633]
It does not seem like Volta can detect system installations of tools. In my case, I already had Node and Yarn installed via Homebrew, and I noticed that Volta does not list them.

**Comment by charlespierce** [comment]
@therealparmesh That's true, Volta is only able to track (and therefore list) the Node / Yarn versions that it manages. Additionally, if you are using Volta to manage the default version of Node, then it should (in most cases) supersede the system installed version.

**Comment by therealparmesh** [comment]
Should it be able to list and switch to the system version? RVM and other likeminded tools do this.

**Comment by charlespierce** [comment]
@therealparmesh It's possible that's a feature we should implement. To investigate, could you describe the use-case a little more in-depth? Specifically why you would want to have a Node version separate from the default and the individual project versions? While we operate in a similar space as tools like RVM, Volta tends to approach problems a little differently, so we may just need to document better how to approach things in the "Volta way".

**Comment by charlespierce** [comment]
Closing as we have the pass-through behavior for when a version isn't known by Volta. If this is still an issue, please feel free to re-open with the use case description!
