### ISSUE TITLE
Improve volta uninstall messaging for non-installed packages

### ISSUE THREAD

**Issue by dustinsoftware** [volta-cli/volta#636]
`0.7.0-beta3`
![image](https://user-images.githubusercontent.com/942358/71836464-09695080-3082-11ea-8366-b451a37def92.png)

**Comment by dustinsoftware** [comment]
It's too early.... I mean to type `ember-cli` 🤦‍♂ 

That said it would be nice if a warning was printed if a locally installed package could not be found.

**Comment by chriskrycho** [comment]
We should definitely message this better – if the package isn't present, we shouldn't say "uninstalled" but something like "no package 'ember' to uninstall".

I'm going to reopen this and rename it to capture that feature request. (And hey, if you or anyone else you know feels like writing a tiny bit of Rust, I'd be happy to shepherd a PR through for this! Should be an easy one!)

**Comment by haochuan** [comment]
@chriskrycho I sent a PR to fix, let me know if I missed or I need to change anything :)

**Comment by chriskrycho** [comment]
Awesome, I'll take a look! Thank you for picking this up!
