### ISSUE TITLE
Path Placement During Install

### ISSUE THREAD

**Issue by jrock2004** [volta-cli/volta#639]
Been playing around with the tool, but noticed during the install that when it edits your path it does the following `export PATH="$VOLTA_HOME/bin:$PATH"`, which opens up a potential security vulnerability. I understand that this is done so you make sure that the tools you install would override if you had same installed on your computer already.

But there lies the security issue. You could install an app that adds to your path shutdown, which will shut your machine down but before that do something bad to your system. 

I think it should put the bin folder at the end of your PATH so things are a little more secure.

**Comment by charlespierce** [comment]
@jrock2004 There definitely is a potential vulnerability through compromised / malicious packages in the npm registry by adding to the beginning of the PATH. However, that vulnerability isn't unique to Volta. As far as I can tell, `npm`, `yarn`, `pnpm`, etc. all do a similar modification of your PATH to make global installs work, and so would be subject to the same vulnerability.

Unilaterally adding to the end of the PATH would solve that, but would open a host of other issues around, as you noted, other package managers overwriting Volta. One solution we could use is to add an option you can pass to the installer that tells it not to modify the profile. Then you could manually make the changes to ensure the bin directory is added to the PATH wherever you like.

**Comment by ljharb** [comment]
fwiw, I'm pretty sure every package manager that modifies the PATH prepends to it, and is vulnerable to the same unlikely but potential risks.

**Comment by chriskrycho** [comment]
@ljharb that matches my understanding and experience with all such version managers (nvm, nodenv, asdf, etc.) as well.
