### ISSUE TITLE
Volta 0.7.0 doesn't install on Ubuntu 18.04

### ISSUE THREAD

**Issue by LawfulHacker** [volta-cli/volta#642]
Using a Ubuntu 18.04 I can't install the latest Volta

Using: `curl https://get.volta.sh | bash` the following error is presented:

```
chmod: cannot operate on dangling symlink '/home/vagrant/.volta/bin/node'
chmod: cannot operate on dangling symlink '/home/vagrant/.volta/bin/npm'
chmod: cannot operate on dangling symlink '/home/vagrant/.volta/bin/npx'
chmod: cannot operate on dangling symlink '/home/vagrant/.volta/bin/yarn'
chmod: cannot access '/home/vagrant/.volta/shim': No such file or directory
```

Here I was using a vagrant vm, but the same error occurs with all boxes I tested.

Using: `curl https://get.volta.sh | bash -s - --version 0.6.8` it install normally.

**Comment by charlespierce** [comment]
Hi @LawfulHacker, that is odd. It looks like you may have an old version of the installer at `https://get.volta.sh` cached somewhere. The current installer doesn't call `chmod` at all. Also the current installer wouldn't work with Volta 0.6.8 correctly, as 0.7.0 involved some changes to the install behavior.

I'm not sure where the caching would happen, but if you want to download the current installer to install 0.7.0, you can find it [here](https://github.com/volta-cli/volta/blob/master/dev/unix/volta-install.sh)

**Comment by LawfulHacker** [comment]
Also strange, because the error occurred in a new deployed machine directly
connected to internet.

It can be cached at a CDN, not sure if is being used. If so, you must
implement some kind of cache invalidation.

Tomorrow will do some test again to check if the cache was expired and let
you know.

Em ter, 14 de jan de 2020 23:38, Charles Pierce <notifications@github.com>
escreveu:

**Comment by LawfulHacker** [comment]
Results from `curl -s https://get.volta.sh | sha1sum` and `curl -s curl -s https://raw.githubusercontent.com/volta-cli/volta/master/dev/unix/volta-install.sh |
sha1sum` from different locations:

```
Location                      get.volta.sh                             raw.githubusercontent.com
AWS us-east-1 (N. Virginia)   3b6f2fa6295057783743d4f9f991c459504f44ee 3b6f2fa6295057783743d4f9f991c459504f44ee
AWS sa-east-2 (São Paulo)     d893695a51b3dab4131db396c40373b82a296eb3 3b6f2fa6295057783743d4f9f991c459504f44ee
AWS eu-west-2 (London)        3b6f2fa6295057783743d4f9f991c459504f44ee 3b6f2fa6295057783743d4f9f991c459504f44ee
VIVO ISP (Curitiba)           d893695a51b3dab4131db396c40373b82a296eb3 3b6f2fa6295057783743d4f9f991c459504f44ee
Claro ISP (Curitiba)          d893695a51b3dab4131db396c40373b82a296eb3 3b6f2fa6295057783743d4f9f991c459504f44ee
```

Apparently the netlify cache for South America (or at least Brazil) was not invalidated.

**Comment by charlespierce** [comment]
Hi @LawfulHacker, thanks for digging into this a little deeper! I believe the Netlify deploy is supposed to automatically invalidate the cache, but I'll take a look at the settings and see if there's an option to force invalidation.

**Comment by charlespierce** [comment]
There don't appear to be any options to retrigger invalidation, but from everything I can see, the rewrite rule we use for `get.volta.sh` should correctly support the ETags that come from GitHub, so the cache should be handled correctly. Is it possible there's another layer of caching / proxying in the Brazilian ISP somewhere? I'm woefully inexperienced with these kinds of networking questions, so just guessing at possible causes.

**Comment by LawfulHacker** [comment]
I think I have figured what is happening, I will try to put all information here to help you fix.

`https://raw.githubusercontent.com` uses fastly as its CDN, each time I request from it, I will have the following headers which help identify the server and cache status which served me:

```
Cache-Control: max-age=300
X-Served-By: cache-gru17148-GRU
X-Cache: MISS
X-Cache-Hits: 0
```

Looking at it I can saw that it was served by a server near Sao Paulo (GRU) and missed the cache which invalidates each 5 minutes.

Those headers are replicated by netlify as it is.

I tried to request the file until I use the same server used by netlify to try to force invalidation, but I still received the same file from netlify.

So I tried to force invalidation on netlify by including a random query string and to my surprise, netlify returned a cache hit form fastly CDN and each time I changed the random query string the cache hit count increased, meaning that netlify is indead requesting a new file from github.

```
X-Served-By: cache-gru17142-GRU
X-Cache: HIT
X-Cache-Hits: 1
```

With that in mind, I checked this [commit](https://github.com/volta-cli/get/commit/03dc45808b6fbf1b987d2538f7686d23c0e0bb45) on get repository and was able to confirm that netlify didn't proper update its configuration, it still points to `https://raw.githubusercontent.com/volta-cli/volta/e0290c2d7b0e80bf64e7c5d403789bc51678d16c/dev/unix/volta-install.sh` confirmed by its SHA-1 hash.

It should be enough information for you to open a ticket with netlify to solve that.

**Comment by charlespierce** [comment]
@LawfulHacker Thanks for all that investigation! I just got a response from Netlify that there was an issue with some of the CDN nodes not using the right redirect. They fixed it, so https://get.volta.sh should point to the correct script for you now.

**Comment by LawfulHacker** [comment]
I confirm that here in Brazil we are getting the right file, so I'm closing this issue.

Thank you for all your help solving this.
