### ISSUE TITLE
Volta should automatically fix incorrect CRLF in shebang lines

### ISSUE THREAD

**Issue by chancancode** [volta-cli/volta#643]
Upon installing [git-mob](https://github.com/findmypast-oss/git-mob) with volta (`volta install git-mob`), I noticed that it didn't work. When I invoke any of the commands (e.g. `git mob`), I get the following error:

```
$ git mob
env: node\r: No such file or directory
```

The reason, it turns out, is that the package was published to NPM incorrectly on a Windows machine, and the shebang line ended up being `#! /usr/bin/env node\r`, so `"node\r"` is passed to `env` and it's complaining about that.

You can inspect the published package using `npm view git-mob latest dist.tarball` and see the issue for yourself (the files are inside `bin/*` of the tarball).

Since this effectively means this tool is broken for everyone on unix (which is, presumably, what that shebang line is for in the first place), I figured someone must have already reported the issue. To my surprise, everyone else seems to be running this tool just fine without issues. I tried following the instructions and install it via `npm install -g` without volta, and surprisingly, it worked.

When I inspected the files installed by `npm`,  I noticed that all the CRLF in the files are still present – except in the shebang line. This leads me to believe that this must be a common-enough problem that npm (and probably yarn) already corrects for (specifically, shebang lines that ends in CRLF in "bin" files). Because I am using volta to install the tool, it is also bypassing the correction that npm/yarn would have performed.

So, I think `volta install` should also do the same fix automatically, even though it is ultimately a mistake by the package maintainer.

**Comment by charlespierce** [comment]
Hi @chancancode, thanks for reporting this, and for investigating the root cause so thoroughly! Agreed that if `npm` (and presumably `yarn` are automatically fixing this, we should as well!

**Comment by charlespierce** [comment]
Taking a quick look at the code, we already have logic for parsing / storing the shebang loaders available, since we need to use it on Windows. Given this issue, I think we can do the same for Unix without significant difficulty, and then make sure we call `trim()` on the argument list before storing it (to make sure we strip off any erroneous `\r` characters).
