### ISSUE TITLE
ts-node peerDependancy not found

### ISSUE THREAD

**Issue by Hammster** [volta-cli/volta#652]
Hi, 

I was in the process of transferring from nvm to volta (Windows & Linux) when I hit a missing feature (?). Apparently even though I installed `typescript` via volta `ts-node` was not able to resolve it.

I also tried to work around by installing a global npm package, which volta rightfully prevented 😅  

I think this is the case because typescript is not a dependency but a peerDependancy of `ts-node`
 
![WindowsTerminal_2020-01-25_02-29-21](https://user-images.githubusercontent.com/1093709/73114428-959cc400-3f1a-11ea-989d-51603b087c5a.png)

**Comment by chriskrycho** [comment]
A related earlier discussion: #350. (That was opened for other reasons, but we discussed this same dynamic there.)

**Comment by chriskrycho** [comment]
Thank you for opening this, @Hammster! It's something we've known about for a while but haven't gotten around to designing a good solution for.

**Comment by charlespierce** [comment]
This should be resolved as of Volta 0.9.0 (In fact, it was one of the cases I used for testing this part of the behavior)
