### ISSUE TITLE
Allow to use different bin directory

### ISSUE THREAD

**Issue by atk** [volta-cli/volta#654]
Currently, volta expects its binaries to reside in $VOLTA_HOME. However, some people like me might want to install the binaries in /usr/bin, /usr/local/bin or somewhere entirely else. This seems currently impossible.

**Comment by atk** [comment]
I am using 0.7.1. If I have `$VOLTA_HOME` set to `$HOME/.volta` and the binaries in `/usr/bin`, I get the error message "volta:12: file or directory not found: $HOME/.volta/volta". The reason is that `load.[ba|fi|]sh` insists calling the volta binary in `$VOLTA_ROOT`, which is derived from `$VOLTA_HOME`.

**Comment by atk** [comment]
Why the path handling anyway? Shouldn't the script just run volta and let the shell resolve the path? If I remove `$VOLTA_ROOT/` from the call, it just works.

**Comment by charlespierce** [comment]
That’s odd, in `0.7.0` and above, the `load.*` files shouldn’t be there at all, the installer should have removed them. They existed in the prior versions to create a function wrapper for Volta, but as of `0.7.0`, we no longer need that functionality.

Did you use the installer, or do you have a custom setup? With `0.7.*`, you need 2 things:

1. The 3 binaries (`volta`, `volta-shim`, and `volta-migrate`) on the `PATH` in the same directory - it sounds like you already have this in `/usr/bin`
2. The shim directory on the `PATH` - your profile startup scripts should be modified to add `$HOME/.volta/bin` to `PATH` as well.

For the second point, you can also run:
```
$ /usr/bin/volta setup
```
To have Volta set up the scripts. It will modify all of the Profile startup scripts it can find, removing the old `load.*` calls and adding a line to modify the `PATH`.

**Comment by atk** [comment]
Thanks for the help.
