### ISSUE TITLE
Need more clarification on how to use volta

### ISSUE THREAD

**Issue by thepreacher** [volta-cli/volta#658]
First of all thanks to all contributors for your hard work I know it is a thankless work that you're doing. Right to my question. I have spent time with the documentation and have to say that I don't quite understand exactly how to use _volta_ for my day to day work? 
I have two main problems with _npm_ and _yarn_. One is the installation of duplicate packages ( the disk space problem ) and the Second is, currently I use _asdf_ as my package manager and every time I upgrade node, I need to reinstall all my packages again. 
I solve the first one with _pnpm_ and I'm hoping to solve the second with _volta_. Say I have installed _volta_ successfully and also installed node via `volta install node@latest`. I then install pnpm via `volta install pnpm`, should I then install my packages (global and local) with `pnpm install [-g] <package>` or `volta install <package>`?
If i'm to use `volta install <package>`, how then can I make _volta_ use `pnpm` as the package installer of choice instead of `npm` or `yarn` for that matter?

I currently have the following list of packages that I install globally on my system: 

- npm install -g pnpm
- pnpm install -g npm-check-updates
- pnpm install -g elm-analyse
- pnpm install -g elm-format
- pnpm install -g elm-live
- pnpm install -g elm-oracle
- pnpm install -g elm-test
- pnpm install -g spoof # Easily spoof your MAC address in macOS, Windows, & Linux!
- pnpm install -g webpack
- pnpm install -g git-open
- pnpm install -g git-recent
- pnpm install -g diff-so-fancy
- pnpm install -g framework7-cli
- pnpm install -g prettier
- pnpm install -g eslint
- pnpm install -g js-beautify
- pnpm install -g typescript-language-server
- pnpm install -g bash-language-server
- pnpm install -g @elm-tooling/elm-language-server
- pnpm install -g vscode-html-languageserver-bin
- pnpm install -g vscode-css-languageserver-bin
- pnpm install -g vscode-json-languageserver

Thanks

**Comment by charlespierce** [comment]
HI @thepreacher, thanks for reaching out and pointing out some areas where the documentation isn't clear! To answer your questions: Volta solves the "reinstall global tools every time I switch Node versions" problem by pinning the Node version for each tool independent of your selected default Node version. So when you upgrade Node, the tools will continue to work using the Node version they were installed with. The general idea is that `volta install` is a replacement for `npm install -g` / `yarn global add`, so you should use `volta install` for your _global_ tools, while continuing to use your package manager of choice for managing project dependencies.

That said, there's a couple of outstanding issues that impact your use case:

1. We don't currently support `pnpm` as a package manager, to the same level that we support `yarn`. It should work as a standard global package (with `volta install pnpm`), but I haven't tested it, so there may be other issues that prevent that from working.
2. We also don't have a way to modify the package manager that is used to install global tools. We always use `npm` internally.

These are both things that we would like to support, however we haven't fully designed how we would go about each of them as yet.
