### ISSUE TITLE
npx.cmd doesn't exist on Windows

### ISSUE THREAD

**Issue by dstaley** [volta-cli/volta#660]
The default installation of node provides a `npx.cmd` command, which tools like React Native rely on existing on Windows installations. Volta, however, doesn't include this, which causes errors when the system attempts to execute `npx.cmd`.

**Comment by charlespierce** [comment]
Hi @dstaley, thanks for reporting this! I’m unfamiliar with the actual workflows, but does React Native rely on the fully-qualified `npx.cmd` existing?

You’re right we don’t currently provide that script, but we do provide `npx.exe`, which works the same in the terminal if you just type `npx`.

If it does rely on the specific file name, we can probably provide shell files for each of the built-in shins that simply redirect to the core executable. It may take a bit of testing to ensure they continue to work, but they should be relatively straightforward to create.

**Comment by dstaley** [comment]
Yeah, unfortunately due to lines like [this one](https://github.com/facebook/react-native/blob/1fb815ed4314c1396999e64354ca0b5d4ed83663/react.gradle) it's expecting `npx.cmd` to exist. I think this is due to some weird restrictions in CMD since replacing `npx.cmd` with just `npx` in that line works in some instances but not others. Gradle does a bunch of weird stuff, so it wouldn't surprise me if it somehow loses the ability to resolve npx to `npx.exe`.

If you need to know exactly why, I'd be happy to dig into it a bit more!

**Comment by charlespierce** [comment]
No worries, I _think_ we can make it work with a `npx.cmd` file that simply calls `npx.exe` and forwards the arguments. I’ll give that a shot and if it works it should be a straightforward change to include in the installer.

Thanks again for reporting and for clarifying!
