### ISSUE TITLE
Need .zshrc Volta $HOME lines. 

### ISSUE THREAD

**Issue by MadSeche** [volta-cli/volta#669]
Hello.
I did a mistake by erasing my ZSH and .zshrc file so i re-installed those.
I have Volta already installed and since i re-installed zsh, the .zshrc file doesn't have the lines of code to handle Volta correctly.

I dont want to remove .volta and re-install it to have those lines because i dont want to re-install all my packages.

Could anyone give me the lines of code i have to add in .zshrc to handle Volta correctly ? 

ps : to be more specific, Volta commands are not working on my machine.

I'm kind of new in this world and far from an expert.

Thanks.

**Comment by charlespierce** [comment]
Hi @MadSeche! There are two options to restore the Volta-specific changes to `.zshrc`:

1. The easiest is you can run `volta setup`, which will modify all of the profile scripts it finds (including `.zshrc`) to ensure that the Volta lines are included.
2. If you'd prefer to modify `.zshrc` yourself, you can add the following lines:
    ```
    export VOLTA_HOME="$HOME/.volta"
    export PATH="$VOLTA_HOME/.bin:$PATH"
    ```

**Comment by MadSeche** [comment]
Hello. 
The problem is volta setup give me a command not found.
I added the lines you have me, i can run node -v or yarn v, everything that was installed with Volta.

But the commands of Volta still don't work.
Any hint ?

**Comment by charlespierce** [comment]
Ahh, sounds like you might be on an older version of Volta (that had a more complicated process for making the `volta` commands available. My first recommendation there would be to update to the latest (using the install script `curl https://get.volta.sh | bash`). That should make sure that everything is set up correctly and all the commands work. Hope that helps!

**Comment by MadSeche** [comment]
Will this command erase all the packages i already have installed with Volta ? ? 
Thx for the help !

**Comment by charlespierce** [comment]
Nope, it should leave everything you've already got installed set up as expected! It will just update the binaries and how they are accessed.

**Comment by MadSeche** [comment]
It worked ! Thanks a lot !

**Comment by charlespierce** [comment]
Excellent, glad to hear it!
