### ISSUE TITLE
Publish `.zip` file for Windows on release.

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#676]
While working on a GitHub Action for Volta ([rwjblue/setup-volta](https://github.com/rwjblue/setup-volta)) it would be really helpful if we published *both* the `.msi` installer (because this is really what _most_ Windows users would want anyways) **and** a `.zip` in the same format as the other platform `.tar.gz` files (which follows the file layout mentioned in the manifest that we also publish).

I'm not sure how much work it is to add this additional publishing target, and I am attempting to work around (by unpacking from the `.msi` directly with `msiexec`). Please feel free to close if it is too much effort.

**Comment by charlespierce** [comment]
This is definitely doable and shouldn't be any trouble at all.
