### ISSUE TITLE
Allow specifying GitHub authentication token for `yarn` version resolution

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#678]
Currently, when running `volta install yarn@1` or `volta install yarn@1.22` volta will attempt to download the list of known releases from `https://api.github.com/repos/yarnpkg/yarn/releases` so that it can resolve the SemVer range accordingly.

https://github.com/volta-cli/volta/blob/83578540a04d6db1a503aea9936c56cec5c407df/crates/volta-core/src/tool/yarn/resolve.rs#L73-L82

Unfortunately, this results in `volta install yarn@1` erroring when the GitHub REST API limit is reached. This can be very problematic when, for example, running `volta install yarn@1` from a network that is using NAT to masquerade many machines behind a single IP address (which is what is happening on most corporate networks, and in many CI systems).

Solving the general case (e.g. corporate networks, with volta running on developer machines) seems quite difficult, but I think when running volta from CI systems we could easily provide a GitHub token to properly authenticate. For example, GitHub Actions provide a [built in read only token](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token). 

---

I'd like to be able to specify a command line flag or environment variable (e.g. `VOLTA_GITHUB_TOKEN`) that would be used to make these requests authenticated to avoid this "random" rate limiting issue.

**Comment by charlespierce** [comment]
I think that this issue and #672 will be fixed when we switch to using the npm registry to resolve / location Yarn. That switch is necessary to support Yarn 2.0, but also has the added benefit of fixing these related issues.
