### ISSUE TITLE
Migrate rwjblue/setup-volta into volta-cli org

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#679]
Now that `rwjblue/setup-volta` is feature complete (v1.3.0 added support for the last main feature: Windows support), I'd like to work on getting it moved into a more official status.

I think the general TODO here is:

- [x] Move the repo into the volta-cli organization
- [ ] Update the volta-cli/website repo to include a new guide on running in CI
- [ ] Write a blog post walking through the why/how of setting it up
- [ ] Profit 💸 

Any other steps that I am missing?

**Comment by charlespierce** [comment]
@dherman Is the owner for the `volta-cli` org, so he'll need to be involved with the actual repo move. The rest we can handle with PRs to the `website` repo (except for the Profit part, let me know when you figure out how to do that 😛)

**Comment by rwjblue** [comment]
Quick update: the repo is moved and published to the GitHub Marketplace:

* https://github.com/volta-cli/action
* https://github.com/marketplace/actions/volta-cli-action
