### ISSUE TITLE
Avoid hard coding home directory path into `.zshrc` in `volta setup`

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#689]
Currently, running `volta setup` will add:

```sh
export VOLTA_HOME="/User/rjackson/.volta"
```

However, this makes a given profile "not portable" (I typically share my dotfiles across both *nix machines and my local Mac).

Instead, I think we should do:

```sh
export VOLTA_HOME="$HOME/.volta"
```

This has the same overall result (`VOLTA_HOME` is setup properly), but the location of the users home directory is not hard coded.

**Comment by charlespierce** [comment]
This makes sense, and should be relatively easy to implement: What we're currently writing is the full path we detect for `VOLTA_HOME` when we run `volta setup`, which in the usual case is `.volta` appended to the home directory. I think we can detect the home directory as a prefix to the path we are writing, and replace it with `$HOME` in the script.
