### ISSUE TITLE
`volta list` does not display defaults when project version is set

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#712]
The design for `volta list` specified that we would output both the default version from the user's toolchain and the version set in a local package:

```sh
$ volta list all --format=plain
runtime node@v12.2.0
runtime node@v11.9.0
runtime node@v10.15.3 (default)
runtime node@v8.16.0 (current @ ~/node-only/package.json)
```

We currently only print the `(current @ ...)` when in a package with one set, however:

```sh
$ volta list all --format=plain
runtime node@v12.2.0
runtime node@v11.9.0
runtime node@v10.15.3
runtime node@v8.16.0 (current @ ~/node-only/package.json)
```

As expected, this affects both "plain" and "human" formats.

**Comment by nickycutesc** [comment]
@chriskrycho I'd like to work on this issue, but I'm having trouble recreating "current" part. For example, here is my current setup:

`$ volta list all --format=plain`
`runtime node@11.9.0`
`runtime node@12.2.0 (default)`
`runtime node@12.16.2`
`runtime node@12.16.3`
`runtime node@13.13.0`
`runtime node@14.0.0`
`package vuepress@1.5.0 / vuepress / node@12.16.3 npm@built-in (default)`

I have even set one of my projects to use `node@12.16.3` in `package.json`, but I'm still not getting the `current` output. I'm not quite sure what I'm missing here. Thank you for your time.

**Comment by nikrowell** [comment]
@charlespierce sorry to bump this thread, but I'm running into this issue (still on `1.0.1`) and can't find how to update volta itself 😆 Thanks for the help!
