### ISSUE TITLE
Install plugin with specific node version!

### ISSUE THREAD

**Issue by collegeimprovements** [volta-cli/volta#736]
Hi, Is it possible to install some plugin globally with specific node version? 
Or Volta will choose node-version each time by itself ?

```
λ › vlist                                                                                                    
runtime node@14.2.0 (default)
package-manager yarn@1.22.4 (default)
λ › volta install neovim@latest        👈🏼 [can we specify node version here as well ?]                                              
  Fetching node@12.16.3  [====>                                   ]  11%
^C
Time: 0h:00m:05s                                                                                                                  
λ ›    
```

**Comment by charlespierce** [comment]
Hi @collegeimprovements, thanks for asking! We actually don't currently have a command to control this, Volta chooses based on the `engines` property in the package you're installing. It's definitely something we'd like to add, however, and we have issue #631 tracking the same question.
