### ISSUE TITLE
is it possible disable pin feature ?

### ISSUE THREAD

**Issue by pigochu** [volta-cli/volta#739]
When I develop , I want the pin feature .
But when I test , I want disable it. maybe use ENV VOLTA_DISABLE_PIN = true
Then I can test multiple version nodejs and many "npm run xxxx"

**Comment by charlespierce** [comment]
Hi @pigochu, thanks for the question! Can you go into a little more detail how you see your workflow going in test? Specifically, when testing, how are you getting the different Node / npm versions to run against?

In the most recent Volta release (0.8.0), we added a new command [`volta run`](https://docs.volta.sh/reference/run), which allows you to specify the Node / Yarn versions on the command-line for a given command. Would that work for your testing, running a bunch of commands like:
```
volta run --node 8 npm test
volta run --node 10 npm test
volta run --node 12 npm test
```
To test against different versions?

Alternatively, if you have something outside of Volta that is handling the different Node versions, you can use the environment variable `VOLTA_BYPASS=1` to turn off Volta's resolution completely. If that is set, Volta will ignore everything it normally does and use whatever is on the system (outside of Volta) to run the commands, essentially acting as if it wasn't there at all.

**Comment by pigochu** [comment]
@charlespierce 

VOLTA_BYPASS=1 that's is
Thank you very much
