### ISSUE TITLE
trouble making cli's globally available via `npm link` 

### ISSUE THREAD

**Issue by serapath** [volta-cli/volta#741]
1. I have a packge called `foobar`
2. In it's `package.json` i defined:
    ```js
    {
        //...
        "bin": { "foobar": "./src/cli.js" } },
        "scripts": { "cli": "foobar --run" },
        //...
    }
    ```
3. I then run `npm link` which tells me:
    * `/home/serapath/.npm-global/bin/foobar`
        * -> `/home/serapath/.npm-globallib/node_modules/foobar/src/cli.js`
    * `/home/serapath/.npm-global/lib/node_modules/foobar`
        * -> `/home/serapath/workspace/repo/foobar`

Now when I try to run it I get:
```bash
serapath@serahost:~/workspace/repo/foobar$ npm run cli

> foobar@0.0.0 cli /home/serapath/workspace/repo/foobar
> foobar

sh: 1: foobar: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! testspec@0.0.0 cli: `testspec`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the testspec@0.0.0 cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
also the following doesn't help
```bash
serapath@serahost:~/workspace/repo/foobar$ foobar --run
foobar: command not found
```
When I print my `$PATH` i get
```bash
serapath@serahost:~/workspace/repo/foobar$ echo $PATH
/home/serapath/.volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

So I can see that at least part of the problem is, that where things got `npm link`ed, isn't part of the `$PATH`, but maybe **volta** should take care of this?

Thanks

**Comment by charlespierce** [comment]
I think both of these issues stem from the same root cause as you described in #657 (and tracked in #56): With Volta's managing of multiple Node versions, the directories that `npm` uses by default aren't generally available so `npm link` doesn't work as expected. We definitely want to support this use-case, however so far we haven't been able to come up with a solution that handles it in a clean way.

**Comment by jakobrosenberg** [comment]
Is there a workaround for this?

**Comment by charlespierce** [comment]
Hi @jakobrosenberg, this should work as of Volta 1.0.0, we added full support for `npm link` making sure that binaries are available on the PATH.

If something isn't working right, would you mind opening a new issue with the details of what you're seeing?
