### ISSUE TITLE
Register in WinGet

### ISSUE THREAD

**Issue by pjking07** [volta-cli/volta#744]
For scripting convenience in Windows, please consider registering volta with WinGet

Registry instructions at https://docs.microsoft.com/en-us/windows/package-manager/package/

Relates to #743 #13

Workaround
--------------

Powershell commands (elevated user)

### Enable Developer Mode
```powershell
reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock /t REG_DWORD /f /v AllowDevelopmentWithoutDevLicense /d 1
```

### Install Most Recent Volta
```powershell
(Invoke-RestMethod "https://api.github.com/repos/volta-cli/volta/releases") |
Sort-Object -Property prerelease, created_at |
Select-Object -Last 1 -ExpandProperty assets |
Where-Object { $_.browser_download_url.EndsWith(".msi") } |
ForEach-Object {
  Invoke-RestMethod $_.url -Headers @{Accept= "application/octet-stream"} -OutFile $env:temp\volta.msi
  Start-Process msiexec -ArgumentList "/i $env:temp\volta.msi /norestart /passive" -Verb RunAs
}
```

**Comment by charlespierce** [comment]
Hi @pjking07, thanks for doing the research on publishing! This is definitely something we should try to do :+1:

**Comment by S64** [comment]
I upvote this one. `winget` has [released v1.0 (stable)](https://github.com/microsoft/winget-cli/releases/tag/v1.0.11451) last month. it [will be preinstalled tool](https://docs.microsoft.com/ja-jp/windows/package-manager/winget/) on windows os in the future.

**Comment by charlespierce** [comment]
@S64 That's good to know, thanks! Definitely makes this a higher priority as having it available in the pre-installed package manager would be a big win.

**Comment by pjking07** [comment]
Note: `Volta.Volta` has popped up on winget's package list. CC @chriskrycho

**Comment by strawberry-choco** [comment]
So… this ticket can be closed then?

**Comment by chriskrycho** [comment]
@strawberry-choco only well over a year later, because I missed this in a too-long list of GH notifications, but… yes! 😂
