### ISSUE TITLE
Suggestion, add way sto auto update

### ISSUE THREAD

**Issue by wellington1993** [volta-cli/volta#747]
Call user sometimes to auto update de volta-cli.
Or add in the crontab if available.

Thanks!

**Comment by charlespierce** [comment]
Hi @wellington1993, that's definitely on our to-do list! We're currently tracking it in #567 (and #568 more generally). A full automatic update is a bit tricky, that will still take some work to figure out how to manage it cross-platform, but having a notifier is also on the list of partial enhancements we plan to implement.
