### ISSUE TITLE
Errors when using Node 6 🤔

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#750]
Steps to reproduce:

```sh
mkdir foo
cd foo
npm init --yes
volta pin node@6
node --version
```

Error output:

> There was an error launching Node: Your environment appears to be misconfigured. Please open a new terminal and try again.

**Comment by charlespierce** [comment]
This appears to be an unrelated system issue, not a Volta error at all. Volta errors are always formatted with an `error: ` prefix when calling Volta directly, or a `Volta error: ` prefix when calling tools through Volta.

**Comment by rwjblue** [comment]
Gotcha, thanks @charlespierce. Sorry for the noise here.

For anyone else that might run into similar issues, the problem I had was with conflicting volta versions on `$PATH`.
