### ISSUE TITLE
Command not Found

### ISSUE THREAD

**Issue by jrock2004** [volta-cli/volta#767]
Running Ubuntu 20.04 LTS and when running the following command I am getting command not found. Not sure what the issue is

```
curl https://get.volta.sh | bash -s -- --skip-setup
```

<img width="588" alt="image" src="https://user-images.githubusercontent.com/655716/84694847-dd4ad900-af17-11ea-970f-cd6c6f2fa8ee.png">

Curl version:
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by charlespierce** [comment]
@jrock2004 Apologies about that, I was making some changes to the organization of the repos and missed one. The setting is updated and deployed, so try it again and it should work!

**Comment by jrock2004** [comment]
Works, now. Thank you
