### ISSUE TITLE
Support ARM builds for macOS

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#775]
At WWDC 2020, Apple announced upcoming Macs will ship with ARM processors. We'll want to add support for those as soon as makes good sense:

- when Rust *itself* supports the target architecture
- once someone has a dev kit we can use for testing (this *may* end up being me, since I have interest for side projects)

This is currently *blocked*:

- Rust support should come quickly, since Apple's ARM 64 targets are already in the general support matrix—but are currently Tier 2 targets per [the Forge](https://forge.rust-lang.org/release/platform-support.html), and Rust will need to do some work to bump that up to a Tier 1 support category. (Presumably the existing `aarch64-apple-ios` is the *same* architecture, which could make an interesting situation name-wise. 😂)
- Getting a dev kit is a matter of applying for one and being approved. I'll investigate on that front since it's potentially of interest to me *anyway*.

**Comment by charlespierce** [comment]
Another blocker to be aware of: Currently there are no ARM builds of Node for MacOS. There are _Linux_ ARM64 builds, which I believe Volta supports (though it needs to be manually compiled since we don't create pre-packaged binaries for it), but as of right now there aren't any pre-built Node binaries to download for `darwin-arm64`

**Comment by chriskrycho** [comment]
Indeed! I actually just mentioned as much in my application for a dev kit. 🤞

**Comment by jrock2004** [comment]
I just tried install Volta on linux and its not supported. So maybe it makes sense to get linux working first?

**Comment by chriskrycho** [comment]
@jrock2004 can you elaborate? We definitely have a bunch of users on Linux, so are you meaning Linux with ARM specifically?

**Comment by jrock2004** [comment]
@chriskrycho This is what I get

<img width="896" alt="image" src="https://user-images.githubusercontent.com/655716/85484694-593ac600-b595-11ea-898d-381e5a202acb.png">

**Comment by chriskrycho** [comment]
Thanks for the report! Which OS and what architecture are you running?

**Comment by jrock2004** [comment]
Ubuntu server for raspberry pi 4 on ARM

**Comment by chriskrycho** [comment]
Thanks! That's helpful, and it is a great suggestion as a starting point here!

**Comment by charlespierce** [comment]
@jrock2004 That's true, as I noted above, we don't currently create pre-built binaries that work with our installer for Linux in ARM. I do believe that Volta itself supports that architecture, but it would require building from source, which may or may not be feasible for your use-case.

It unfortunately looks like GitHub actions doesn't currently support architectures other than `x86_64`, so that could be a blocker for both creating a Linux + ARM build and for this issue. My first test would be to try with `cargo cross` and see if we can make a cross-architecture build, but I don't know much about that.

**Comment by rwjblue** [comment]
Could we use [Docker for ARM on Linux](https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/)?

**Comment by charlespierce** [comment]
One other thing to consider, we should implement #34 as well as checking the architecture when trying to download Node, so we know if the version is available for the Mac + ARM combination.

**Comment by chriskrycho** [comment]
Note: the relevant architecture is now a Tier 2 supported target; I will see if I can give this a go on my DTK next week. (And hey, maybe not too long after than, on regular hardware!)

**Comment by jasonsilberman** [comment]
Just wanted to check in on this, how are things going?

**Comment by chriskrycho** [comment]
Haven't had a chance to poke at it yet, but my discussions with the Rust folks working on it indicated (a) it should be pretty straightforward to build, including automated builds once GitHub Actions supports it, and (b) the Rosetta version should work just fine in the meantime.

**Comment by charlespierce** [comment]
A couple of notes that we'll probably need to fix even once things compile:

- The installer showing an error for ARM architecture, if we detect MacOS + ARM we should treat that the same as x64 (at least until we support M1 natively, then we should handle it correctly)
- Once we have M1 support, we'll need to have a plan for Node versions: Newer versions will start to include native builds, but older versions we'll need to fall back to the x64 and rely on Rosetta. We should also include that in the documentation so users know that about older versions.

**Comment by charlespierce** [comment]
Done in the 1.0.1 release! Also added #919 to track supporting M1 native Node builds once they become available.
