### ISSUE TITLE
os error 1314, required privilege is not held

### ISSUE THREAD

**Issue by 3nigm4** [volta-cli/volta#780]
```
"C:\\Program Files\\Volta\\volta.exe" "install" "vue-cli"
Volta v0.8.3

Could not create shim for "vue"

Please ensure you have correct permissions to the Volta directory.

Error cause: A required privilege is not held by the client. (os error 1314)
```
I am on windows 10.

I turned on Developer Mode before install.
I tried running volta in admin terminal.

I was able to install node without issues.

**Comment by charlespierce** [comment]
@3nigm4 That's very odd, especially if it didn't even work in an admin terminal, which should have full permissions to everything on the system. The only thing that comes to mind is that the symlink can't be created at all and the error is misleading. Is your `%LOCALAPPDATA%` (usually `\Users\<username>\AppData\Local`) directory on a different drive than `Program Files`?

**Comment by 3nigm4** [comment]
Hey thanks for your replay. No they are both on my c drive. Antivirus?

**Comment by charlespierce** [comment]
Hmm, that is very strange indeed, as it doesn't appear like there should be any reason you can't create the symlink. I'll do a bit more investigation to see if there is some other requirement to create symlinks or a common error.

**Comment by 3nigm4** [comment]
it also does not work on WSL2:

```
 volta install @vue/cli
⠁ Querying metadata for @vue/cli@latest
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:179:21
⠁ Fetching public registry: https://nodejs.org/dist/index.json
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
⠁ Installing dependencies for @vue/cli@4.4.6
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:179:21
```

**Comment by rwjblue** [comment]
@charlespierce - We could also handle the error and just copy the file I think... (though we should still root cause this to see if we can figure it out)

**Comment by charlespierce** [comment]
@rwjblue True, that's an option. And I actually have an issue #579 to investigate other ways of not using symlinks on Windows. We'd want to be deliberate in the approach, however, to make sure that we clean anything up in situations like upgrades (where we don't want the old binaries to stick around because they were copied).

@3nigm4 That WSL error looks different, and I've actually never seen anything like that before. Which distro are you using within WSL? I know I've tested Volta within a WSL environment before, but it's been a while. If there's a distro we aren't supporting we should definitely fix that if possible. Once concern I have is that appears to be a panic within the Rust standard library itself, so it may be an upstream issue that we need to figure out.

**Comment by 3nigm4** [comment]
I am using WSL2 and ubuntu 20.04.

**Comment by ltomes** [comment]
@charlespierce  I'm in the same boat as @3nigm4, also on 20.04

**Comment by charlespierce** [comment]
@3nigm4 @ltomes Are you both sure you're actually using WSL2? It looks like the issue you're seeing is the same as this one: https://github.com/rust-lang/rustup/issues/2293, which is actually on WSL1 with newer `glibc` versions (like that provided by Ubunto 20.04). From the comments there, it looks like to use WSL2, you would need to manually opt in (and upgrade your ubuntu installation) to use WSL2, by default it still uses WSL1.

If it is that issue, then it's unfortunately not something we can fix from Volta, as it's deeper in the Rust `glibc` linking. The suggested fixes are to upgrade WSL manually using the commands in [this comment](https://github.com/rust-lang/rustup/issues/2293#issuecomment-643204545) or to stick with Ubuntu 18.04 LTS instead of using 20.04.

**Comment by ltomes** [comment]
You're correct for some reason its running wsl 1.
```
wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
```
This is a brand new install in fast ring. It's baffling that it defaulted to WSL, I didn't even consider it might have done that.

I'll convert and see how my behavior changes

**Comment by 3nigm4** [comment]
Same for me, but I still got trouble with global executable installs (now definitely on WSL2)

`vue ui --dev
🚀  Starting GUI...
 ERROR  Error: Cannot find module '@vue/cli/lib/util/rcPath'
Require stack:
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/db.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/context.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/configurations.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/schema/configuration.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/type-defs.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/graphql-server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/lib/ui.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/bin/vue.js
Error: Cannot find module '@vue/cli/lib/util/rcPath'
Require stack:
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/db.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/context.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/configurations.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/schema/configuration.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/type-defs.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/graphql-server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/lib/ui.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/bin/vue.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)`

**Comment by 3nigm4** [comment]
... but this is off topic, sorry ... will create different issue for this.

**Comment by ltomes** [comment]
When you open that issue I will be following it as well: :)

```
npm install -g @vue/cli-service-global
Volta error: Global package installs are not supported.

Use `volta install @vue/cli-service-global` to add a package to your toolchain (see `volta help install` for more info).
volta install @vue/cli-service-global
error: Package has no executables to install.
```
