### ISSUE TITLE
Volta stops installing global package when the node version in the package's package.json is not defined correctly

### ISSUE THREAD

**Issue by haochuan** [volta-cli/volta#790]
### How to reproduce

1. Let's say we have a package `foo`, and its `package.json` looks like:

```
{
    ...
    "bin": "index.js",
    "engines": {
        "node": "abc"
    }
    ...
}
```

2. `volta install foo`

3. We get error:

```
error: Could not parse version "abc"
```

### Expected Result

Instead of throwing an error and stop the installation, it's better to assume there is no `node` version specified when we hit a version parsing issue, and let the installation continue.

**Comment by charlespierce** [comment]
Closed in #791
