### ISSUE TITLE
"curl https://get.volta.sh | zsh" does not work

### ISSUE THREAD

**Issue by detj** [volta-cli/volta#794]
Okay. Maybe it is not supposed to work. I don't know. The official command obviously [uses `bash`](https://docs.volta.sh/guide/getting-started).

But should it work?

It's not like I was installing volta. I already had volta, I was trying to upgrade it. And out of curiosity, replaced `bash` with `zsh`. That's all.

**Comment by detj** [comment]
Running `curl https://get.volta.sh | bash` upgraded volta as expected.

**Comment by charlespierce** [comment]
@detj I believe the script we use for that uses some Bash-specific syntax, which is why our command currently uses `bash`. That said, despite the fact that it's running through `bash`, it should still correctly install / upgrade for all shells that you use.
