### ISSUE TITLE
platfom support

### ISSUE THREAD

**Issue by thevan96** [volta-cli/volta#797]
Volta support python, ruby ??

**Comment by charlespierce** [comment]
Hi @thevan96, great question! Volta is currently built specifically for the NodeJS ecosystem and is focused on that use-case. It's possible that we could extend it to support other languages / ecosystems in the future, it's a growth area we've definitely discussed a bit.

At the moment, however, we don't have the bandwidth to really work on other ecosystems. We'd definitely be open to contributions / discussion around that work, as the shim approach has been very effective for Node tools.
