### ISSUE TITLE
release tag question

### ISSUE THREAD

**Issue by chenrui333** [volta-cli/volta#803]
👋  looks like right now the pre-release tag usage for the project is blocking homebrew to ship the latest version of the formula.

With that being said, I want to clarify two things:
- Can we use the `latest release` instead of `pre-release` tag? In this way, it sounds more semantically correct?
- Besides the tag usage, do you folks consider the most recent pre-release is a stable release? 

Thanks!!

cc @SMillerDev @dtrodrigues

relates to https://github.com/Homebrew/homebrew-core/pull/60168

**Comment by charlespierce** [comment]
Hi @chenrui333, thanks for the question! Our general philosophy has been to mark it as a `pre-release` until we reach 1.0, for reasons of both stability and feature readiness. That said, at this point we definitely consider Volta stable, so the outstanding concern is having all of the features we consider necessary for 1.0.

However, given that version 1.0 itself serves as a marker for that feature-completeness and that we are stable and committed to a smooth upgrade process for new versions, I think it's reasonable to drop the `pre-release` label. Our next release will most likely be 0.9.0, which will include the last of the significant changes needed before 1.0, so at that point I think dropping the `pre-release` tag makes sense.

**Comment by chenrui333** [comment]
@charlespierce wonderful, I will wait for the soon-release 0.9.0 then. Thanks!!

**Comment by chenrui333** [comment]
Yeah, I will seek keeping the formula up to date later after v0.9.0

**Comment by chenrui333** [comment]
@charlespierce 👋 just checking, looks like the latest release 0.9.0 is still pre-release? Thanks!

**Comment by charlespierce** [comment]
Hi @chenrui333, thanks for checking! I knew there was something with the homebrew formula I was missing. Let me remove the tag (and update the CI script to not add it any more).

**Comment by charlespierce** [comment]
Updated the release to not be pre-release any more :+1:

**Comment by chenrui333** [comment]
> Hi @chenrui333, thanks for checking! I knew there was something with the homebrew formula I was missing. Let me remove the tag (and update the CI script to not add it any more).

😄  thanks!! Appreciate it.
