### ISSUE TITLE
Unable to install packages? Could not parse version

### ISSUE THREAD

**Issue by stephencweiss** [volta-cli/volta#805]
Hi! 

I'm quite confused about what the issue is here, but I'm trying to use `volta` to manage my toolchain and one tool I'd like is the [netlify-cli](https://www.npmjs.com/package/netlify-cli). 

When I try to install it however, I'm getting a `Could not parse version` error (which seems to have been a problem with #491 but then closed in #604. 

Maybe I'm misunderstanding the point here though? Should I be installing `netlify-cli` at a "global" level? or should it be a dev dependency (which seems less intuitive to me) for my project?

```
stephen@MacBook-Pro blog % volta --version
0.8.5
stephen@MacBook-Pro blog % volta which node
/Users/stephen/.volta/tools/image/node/12.18.3/bin/node
stephen@MacBook-Pro blog % yarn global add netlify-cli
Volta error: Global package installs are not supported.

Use `volta install netlify-cli` to add a package to your toolchain (see `volta help install` for more info).
stephen@MacBook-Pro blog % volta install netlify-cli
error: Could not parse version ">=v8.17.0"

Please verify the intended version.
Error details written to /Users/stephen/.volta/log/volta-error-2020-08-29_19_20_31.814.log

stephen@MacBook-Pro blog % npm i -g netlify-cli
Volta error: Global package installs are not supported.

Use `volta install netlify-cli` to add a package to your toolchain (see `volta help install` for more info).
```

Full log:
```
"volta" "install" "netlify-cli"
Volta v0.8.5

Could not parse version ">=v8.17.0"

Please verify the intended version.

Error cause: the given version requirement is invalid
```

I'm not clear on what version it's referring to as `volta`. is v0.8.5, yarn is 1.x and node is 12.x.

Help is very much appreciated!

**Comment by charlespierce** [comment]
Hi @stephencweiss, it looks like this is an issue with parsing the `engines` field in `netlify-cli`, which incorrectly has a `v` in it. It appears to have been fixed in this PR: https://github.com/netlify/cli/pull/1153

I’m not sure if that change has been released yet, but if not you may need to install an older version of `netlify-cli` that doesn’t have that erroneous `v`

**Comment by stephencweiss** [comment]
Thanks @charlespierce! Looks like another volta user found / submitted a fix too - love seeing the community grow!

**Comment by charlespierce** [comment]
Definitely exciting to see it fixed by another Volta user!
