### ISSUE TITLE
https://nodejs.org down, volta cannot install global npm packages

### ISSUE THREAD

**Issue by izelnakri** [volta-cli/volta#806]
```
volta install helman
```

```
⠠ Fetching public registry: https://nodejs.org/dist/index.json
error: Could not download Node version registry
from https://nodejs.org/dist/index.json

Please verify your internet connection.
Error details written to /home/izelnakri/.volta/log/volta-error-2020-08-30_13_21_16.019.log
```

This is happening because https://nodejs.org/ is currently down, rare situation but it happened today :) Global install of npm packages shouldnt depend on a nodejs.org network call.

**Comment by charlespierce** [comment]
Hi @izelnakri, thanks for reporting this! To give some background, the reason we fetch from `nodejs.org` when installing packages is we try to pin the most recent LTS version of Node that matches the `engines` requirement of the package. However, we’re currently working on changing that process (see the RFC: https://github.com/volta-cli/rfcs/pull/45). Once those changes are complete, we should no longer need to fetch Node while installing a package (assuming you already have some node version locally)

**Comment by charlespierce** [comment]
As of Volta 0.9.0, this should no longer be an issue. You will need access to `nodejs.org` to install a new Node version (naturally), but if you have a Node version installed as your default then installing a package shouldn't need to access the node index.
