### ISSUE TITLE
Document how to uninstall volta

### ISSUE THREAD

**Issue by mehulkar** [volta-cli/volta#810]
The page where it shows how to install volta with `curl | bash`, should also show how to uninstall volta. I can't find any documentation about this.

https://docs.volta.sh/guide/getting-started

**Comment by charlespierce** [comment]
Hi @mehulkar, thanks for raising this! We actually have an issue for this already: #531

Short-term, there's a comment on that issue with the general process, unfortunately we don't have a script for it at the moment.
