### ISSUE TITLE
When using yarn 2, unable to find installed tools

### ISSUE THREAD

**Issue by NullVoxPopuli** [volta-cli/volta#812]
Related issue: https://github.com/volta-cli/volta/issues/651

```
 volta --version
0.8.7
```

```
$ ember --version
Volta error: Could not locate executable `ember` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
$ volta install ember-cli
Package ember-cli@3.21.0 is already installed

$ volta which ember
/home/lprestonsegoiii/.volta/tools/image/packages/ember-cli/3.21.0/bin/ember
$ ember --version
Volta error: Could not locate executable `ember` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
```

System Info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

$ node --version
v12.18.3
```

Aside from the error, I'm not sure what `Volta error: Could not locate executable `ember` in your project.` means exactly -- it suggests that it's looking for a local-to-my-project-maybe-in-node_modules version of `ember`, but why would it do that? shouldn't it use the global tool? (but also I don't have a node_modules, cause yarn 2)

**Comment by chriskrycho** [comment]
Thanks for the write up. This is a known issue: see #651. Yarn 2 uses a sufficiently different resolution algorithm that we’ll need to revise our strategy for handling that. It likely will also be useful for pnpm support. Closing this in favor of continuing discussion on #651.
