### ISSUE TITLE
Don't rely on exists() for filesystem operations

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#823]
As noted in this discussion: https://github.com/volta-cli/volta/pull/815#discussion_r487098657 For filesystem operations, we shouldn't do an `exists()` check first, followed by a File open. Instead we should directly open the file and then handle the "File not found" error case separately (as needed).

This prevents race conditions where the file is deleted _after_ the `exists()` check but before it is opened. It also reduces the complexity of the happy path slightly, not requiring an extra filesystem check before opening the target file.

**Comment by BProg** [comment]
Hi, I can try to work on this

**Comment by charlespierce** [comment]
@BProg Great, we'd be happy to have a contribution! Let me know if I can help.

**Comment by BProg** [comment]
@charlespierce I think this can be closed
