### ISSUE TITLE
Cannot install Volta on Windows with MSYS present

### ISSUE THREAD

**Issue by Domiii** [volta-cli/volta#830]
The Volta system/platform check seems erroneous, unable to interpret the (admittedly super annoying) msys-modified platform identifier.

## Error Message

I get this when running `curl https://get.volta.sh | bash` in cmd:

>   Installing latest version of Volta (0.8.7)
>     Checking for existing Volta installation
> Error: The current operating system (MSYS_NT-6.1-7601) does not appear to be supported by Volta.
> Error: Could not download Volta version '0.8.7'. See https://github.com/volta-cli/volta/releases for a list of available releases

## Possible Solution

Conan had the same issue [here](https://github.com/conan-io/conan/issues/2638).

They fixed it simply with some extra `if`s [here](https://github.com/conan-io/conan/pull/2798/files).

**Comment by charlespierce** [comment]
Hi @Domiii, the bash script actually doesn’t support Windows at all (MSYS or not), it only looks for the Linux / MacOS binaries. The Windows installer is provided as a `.msi` file in our releases (also linked in the Windows section of our [Getting Started guide](https://docs.volta.sh/guide/getting-started). That installer should work for both CMD / Powershell and emulated terminals like Git Bash.

If the installer doesn’t work for your terminal, that’s a big and we’ll need to fix Volta to work in the different shell. Depending on the terminal, you may need to close and re-open it after running the installer.

**Comment by Domiii** [comment]
Thanks for the extremely fast reply!

Would love for Windows to also have the cli installer work, but for now, I used the msi and it works - Thanks again :)

**Comment by GeorgeWL** [comment]
you really should state that on the main page of the website?
