### ISSUE TITLE
Automatically install correct version from previously pinned version in package.json

### ISSUE THREAD

**Issue by bestickley** [volta-cli/volta#843]
If I have a new team member who just installed Volta and they're going to start developing in a project that has a package.json with a nodejs version pinned, does the project member need to look in the package.json to see what version of Node.js to install via Volta? Or is their an automatic command to install that version?

**Comment by charlespierce** [comment]
Hi @bestickley, good question! The answer really is neither! With Volta, when a package has a pinned version of Node (or npm / Yarn), there’s no need to install it manually at all.

Whenever you run a Node command, Volta will determine the version it should be using by looking at the `package.json`. If it finds a version that hasn’t been used on this machine before, it will automatically download it and set it up.

So, ultimately, if you have a version pinned and the team member has Volta installed, then all they shouldn’t need to do anything special, just run the normal commands they would during development and the correct versions should be used.

**Comment by bestickley** [comment]
Excellent. Thank you!
