### ISSUE TITLE
Support `npm update -g` and `yarn global upgrade` commands

### ISSUE THREAD

**Issue by igolskyi** [volta-cli/volta#850]
How about update packages command  installed `volta install` similar as https://docs.npmjs.com/cli-commands/update.html

**Comment by charlespierce** [comment]
Hi @igolskyi, we don't currently have a way to do that for all packages at once. However, if you run `volta install package@<version>` again, it will re-resolve the version and update to the latest that matches `<version>` (which can be a range / caret / tilde specifier as well).

That said, we are in the process of revamping our support for packages to allow directly installing with `npm i -g`, and this brings up an important point that we missed in the RFC: We need to support `npm update -g` / `yarn global upgrade` as well!
