### ISSUE TITLE
Unclear how to remove Node.js version

### ISSUE THREAD

**Issue by ai** [volta-cli/volta#855]
`volta help uninstall` does not show an example of how to remove a specific Node.js version.

All obvious ways do not help:

```
➜ volta list node
⚡️ Node runtimes in your toolchain:

    v10.22.1
    v12.19.0
    v14.14.0 (default)
    v15.0.0

➜ volta list uninstall node@10.22.1
error: Found argument 'node@10.22.1' which wasn't expected, or isn't valid in this context

USAGE:
    volta list [FLAGS] [OPTIONS] [tool]

For more information try --help

➜ volta list uninstall node 10.22.1
error: Found argument 'node' which wasn't expected, or isn't valid in this context

USAGE:
    volta list [FLAGS] [OPTIONS] [tool]

For more information try --help

➜ volta list uninstall node v10.22.1
error: Found argument 'node' which wasn't expected, or isn't valid in this context

USAGE:
    volta list [FLAGS] [OPTIONS] [tool]

For more information try --help
```

**Comment by charlespierce** [comment]
Hi @ai, thanks for asking! We don't currently have a method to prune out the cached versions of tools, though we have an existing issue tracking that #330. Can you expand a bit on your use-case? Are you primarily looking to clean up the disk space used by different versions? Or is there another motivating factor in wanting to remove older versions?

**Comment by ai** [comment]
Yeap, the main use case is just for keeping my desktop system clean

**Comment by charlespierce** [comment]
Okay, in that case I think tracking #330 or #327 which is related but not _quite_ the same would be your best bet. Short-term, you can safely delete any of the (version-numbered) directories within `~/.volta/tools/image/node/` (`%LOCALAPPDATA%\Volta\tools\image\node\` on Windows) to remove that version of Node from your system. If Volta comes across a package that uses that version in the future, it will be re-installed, so there shouldn't be any danger in deleting them.
