### ISSUE TITLE
Move public repository URLs to config file

### ISSUE THREAD

**Issue by monshi** [volta-cli/volta#86]
I think adding repositories as a config can be good flexibility for the users, instead of hard-coded URLs in notion code. It'll be especially useful for companies behind a corp proxy. We can add a new config under ~/.notion

```
/// URL of the index of available Node versions on the public Node server.
const PUBLIC_NODE_VERSION_INDEX: &'static str = "https://nodejs.org/dist/index.json";
/// URL of the index of available Yarn versions on the public git repository.
const PUBLIC_YARN_VERSION_INDEX: &'static str = "https://github.com/notion-cli/yarn-releases/raw/master/index.json";
```

**Comment by charlespierce** [comment]
Closing as this was implemented with the `hooks.json` to allow users to redirect the repository lookups.
