### ISSUE TITLE
Command-line parsing bug, prevents use of TypeORM CLI

### ISSUE THREAD

**Issue by constb** [volta-cli/volta#863]
Hi,

I have TypeORM installed in node_modules via pnpm into package.json (`pnpm install typeorm ts-node tsconfig-paths typescript`). I also have a script in package.json to run it more conveniently: `"typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js"`.

This was working when I had `node` and `pnpm` installed via homebrew. Now when I switched to volta, the following happens:

```
$ pnpm run typeorm -- migration:create -n PageAddType
Volta error: Could not start migration process to upgrade your Volta directory.

Please ensure you have 'volta-migrate' on your PATH and run it directly.
Error details written to /Users/constb/.volta/log/volta-error-2020-10-29_14_02_51.781.log
```

Okay, let's see that /Users/constb/.volta/log/volta-error-2020-10-29_14_02_51.781.log:

```
"pnpm" "run" "typeorm" "--" "migration:create" "-n" "PageAddType"
Volta v0.9.1

Could not start migration process to upgrade your Volta directory.

Please ensure you have 'volta-migrate' on your PATH and run it directly.

Error cause: No such file or directory (os error 2)
```

Also, pnpm is installed via `volta install pnpm` so it's a shim:

```
$ type pnpm
pnpm is hashed (/Users/constb/.volta/bin/pnpm)
```

I don't know what causes this, must be some bug in command line parsing in volta, but otherwise this makes zero sense to me… :(

**Comment by constb** [comment]
As it appears, all tools installed by volta were broken, apparently caused by volta upgrade from 0.8.x to 0.9.1. Volta is installed from homebrew, to I guess it's a homebrew formula issue. After reinstalling all packages via `volta install`, everything went back to normal.

Do I close the issue?

**Comment by charlespierce** [comment]
Hi @constb thanks for reporting and checking into it. That's very odd about the homebrew formula, nothing should have changed about how Volta is delivered, but it apparently was having trouble locating the `volta-migrate` binary. We can close this, but I'll take a look and see if anything stands out as being clearly incorrect with the formula

**Comment by constb** [comment]
@charlespierce 
Thank you, Charles. It may be important that homebrew uses version in the path for actual installed files, and `/usr/local/bin/volta-shim` is only a symlink:

```
$ ls -la ~/.volta/bin/node
lrwxr-xr-x  1 constb  staff  25 Oct 29 14:18 /Users/constb/.volta/bin/node -> /usr/local/bin/volta-shim
$ ls -la /usr/local/bin/volta-shim
lrwxr-xr-x  1 constb  admin  36 Oct 28 22:11 /usr/local/bin/volta-shim -> ../Cellar/volta/0.9.1/bin/volta-shim
```

**Comment by charlespierce** [comment]
@constb Thanks again for raising this issue! It ultimately led to finding a subtle bug in how we detect the location of the Volta binaries, which I ultimately think is what was causing this problem #864
