### ISSUE TITLE
Download release fails if OpenSSL 3.0.0 installed

### ISSUE THREAD

**Issue by shakeel** [volta-cli/volta#881]
The `curl https://get.volta.sh | bash` command fails with 404 Not Found error message if OpenSSL 3.0.0 is installed on Ubuntu.

I uninstalled OpenSSL 3.0.0 and the Volta installation succeeded.

The error message from the failed install was strange, it should be caught in https://github.com/volta-cli/volta/blob/main/dev/unix/volta-install.sh#L353 when you parse the openssl_version or in the parse_os_info method.

The fetching archive for Ubuntu shows release 0.9.2 the current release of Volta. So it took some time for me to figure out why the install failed.

**Comment by charlespierce** [comment]
Hi @shakeel, thanks for reporting this! We don't currently have pre-built binaries linked against OpenSSL 3.0, as it appears that there hasn't been an official release of that version yet. That said, you're right that we should do a better job of detecting that case and showing a helpful error message.

**Comment by charlespierce** [comment]
Volta 1.0.7 was just published, which includes support for OpenSSL 3.0, so this should be resolved!
