### ISSUE TITLE
Upgrade Volta itself

### ISSUE THREAD

**Issue by fnick851** [volta-cli/volta#882]
Is there a command like `volta upgrade` to update Volta itself?
What is the recommended aproach to keep Volta up to date?
Thanks.

**Comment by charlespierce** [comment]
Hi @fnick851, thanks for the question! We don’t have any commands at the moment to upgrade Volta, though that’s tracked in #269 

For now, the recommended way to update is to re-run the installer, that will make sure things are updated.

**Comment by fnick851** [comment]
@charlespierce Thank you!
