### ISSUE TITLE
Installed verdaccio via volta -- where are the packages I published? 

### ISSUE THREAD

**Issue by tearingItUp786** [volta-cli/volta#899]
Hey all,

Love the project and appreciate all the hard work! 

I recently did a `volta install verdaccio` and verdaccio should be publishing to `~/.local/share/verdaccio/storage` but I can't seem to find this directory. The packages I published locally are indeed published (I can see them in the web UI for verdaccio). 

Thanks!

PS: [reference to verdaccio discussion](https://github.com/verdaccio/verdaccio/discussions/2024#discussioncomment-196265)

**Comment by charlespierce** [comment]
Hi @tearingItUp786, thanks for reaching out! I'm unfamiliar with how `verdaccio` works internally, however I can say that once a tool starts, Volta is hands-off (it doesn't change anything about the internals of tools).

That said, if Verdaccio is storing the published packages somewhere relative to itself, when installed with Volta, the root of the installation should be: `~/.volta/tools/image/packages/verdaccio` So my first guess would be to check in that directory (and the subdirectories, specifically `lib/node_modules/verdaccio` to see if it's storing the packages relative to itself.

**Comment by charlespierce** [comment]
Closing this due to no response. Please feel free to re-open if it's still a problem or there are still outstanding questions.
