### ISSUE TITLE
Question: Should i only use package.json -> volta or also npm's engine-strict?

### ISSUE THREAD

**Issue by FunctionDJ** [volta-cli/volta#914]
I've tried out `nvm` a few months ago, but until now i haven't really done any node version tracking per project, which i would like to start with in order to make development environments more easily reproducible.
I came across this package, but also read about the `.npmrc` file or rather the `engine-strict` npm config.
How should one go about this when colleagues might not have or want to use Volta? Should i set both of those values? Does Volta only make sense when the entire dev team agrees to using it?

**Comment by charlespierce** [comment]
Hi @FunctionDJ, great question! `engine-strict` is actually a boolean setting that tells `npm` to fail when trying to install dependencies whose `engines` don't line up with the running Node version, so it's not really comparable to the Volta settings.

`engines` itself is a range and represents something slightly different, as outlined in this comment: https://github.com/volta-cli/volta/issues/742#issuecomment-631588143

As for what to do when your colleagues have not yet switched, the `volta` configuration in `package.json` shouldn't cause any issues for non-Volta users, their setups will simply ignore that setting. You may need to coordinate with them on whether it is worthwhile to even have it set, but that's more of a question of internal decision-making than technical concerns.

**Comment by FunctionDJ** [comment]
Thanks a lot for the explanation!
