### ISSUE TITLE
Fetch M1 Native Node builds where possible

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#919]
Currently, the M1 Native version of Volta fetches the `x64` version of Node, which then runs through Rosetta 2. Once Node begins to ship prebuilt M1 Native binaries, we should fetch those where possible. If there isn't a native build available, we should still fall back to fetching the `x64` Node.

Currently blocked as Node is not yet publishing M1 Native builds and we don't yet know what the `files` identifier will be in https://nodejs.org/dist/index.json

**Comment by muuvmuuv** [comment]
Would be great if the user gets a notification whenever a non-native binary is picked, so he can schedule an update later to download the native binaries.

**Comment by charlespierce** [comment]
@muuvmuuv That's a great suggestion! I suspect we'll want to figure out a way to limit it, since there will likely be a lot of older versions that won't ever get a native binary, and we'd like to avoid spamming the user when they're forced to use a version that doesn't include native binaries.

**Comment by rwjblue** [comment]
Still a bit WIP / TBD but I think https://github.com/nodejs/build/issues/2474 is a good issue to watch for updates on this.

From a quick read, the last update suggested Node is targeting 16.x released to use fat binaries.

**Comment by charlespierce** [comment]
Interesting, if they're going to release Fat binaries then we might not have to change anything (unless they change the `index.json` identifier for MacOS), as those will work natively on both systems from a single download.

**Comment by shadowspawn** [comment]
FYI: `files` addition to index is in flight:

https://github.com/nodejs/nodejs-dist-indexer/pull/15/files

**Comment by charlespierce** [comment]
Awesome, it looks like we'll be able to pick this back up now that we now what the `files` specifier is for the native builds.

**Comment by arjan-kitchenstories** [comment]
Hello there, first of all thank you for creating Volta - it's a great idea & tool, started using it and don't want to miss it anymore.

You probably noticed the Node 16 release today. I immediately tried pinning v16.0.0 in one of my projects to see if Volta installs the `darwin-ARM64` version, which unfortunately does not seem to be the case. 

https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70

Is there a way let Volta know which version to choose? If not, looking forward to M1 support in the future.

**Comment by charlespierce** [comment]
Hi @arjan-kitchenstories, thanks for the question! At the moment, no there isn't a way to change which version Volta fetches, it will currently always use the x64 / Rosetta version. This issue is about updating that logic for the M1 build to use the native build if available, otherwise fall back to the x64 version. Now that Node is shipping the native binaries and we know what the `index.json` will look like for those, we'll implement this and then release a new version of Volta that supports that behavior.
