### ISSUE TITLE
Any plan to consider Volta Python?

### ISSUE THREAD

**Issue by linux-china** [volta-cli/volta#923]
I know somebody has raised this problem on #797    Reasons as following:  

*  JS/TS and Node.js are very popular, but Python is popular too, and both are on Top 5 popular languages
* Version management for Node.js & Python: nvm and pyenv
* Packages install with the version
* Lots of command line apps

Lots of things are same for Volta to support Node.js & Python.   

I use Volta everyday, and I really expect Volta to have Python support.   Please open sponsor for Volta project :)  and I can donate a coffee for the team.

**Comment by domino2** [comment]
It would be great to support other tools like gradle/groovy for example. It would be harder, but some kind of generic approah would be great. The tech stack of some product may be really heterogenous.

**Comment by charlespierce** [comment]
Hi @linux-china & @domino2. There aren't any immediate plans to expand Volta beyond the JS ecosystem. It's definitely something we've talked about in the past, as we really like the ergonomics that Volta brings to development toolchains. We'd absolutely be willing to accept—and help with—contributions to help define that path, whether RFCs, PRs, design discussions, etc. However, at the moment the current team is focused on the JS experience and making sure that is as seamless as possible.

As for the generous offer to sponsor a coffee, thank you, that's greatly appreciated! At the moment, all of the main contributors are being paid to work on Volta as part of their jobs, so there's no need for individual sponsors. As the community grows, we'll definitely re-evaluate that, however.

**Comment by ming-codes** [comment]
I would argue that python is part of the js ecosystem since node-gyp uses python for many compilation needs. I recently had an issue with dart sass not compiling due to MacOS system Python is on 3.11. Would be nice to be able to pin a Python version

**Comment by dominikj111** [comment]
I would to also say that to switch node only is too narrow perspective. For example this project is used quite widely to change node environment https://github.com/nvm-sh/nvm
I understand that you trying to do it better, but by covering wider niche you may motivate more audience to use the Volta.

**Comment by dominikj111** [comment]
By the way, is the development still active? According to [release log](https://github.com/volta-cli/volta/blob/main/RELEASES.md) I would guess that the Volta is in maintenance mode only.

Is there any perspective? I don't see even newish blog posts
https://blog.volta.sh/

**Comment by maximveksler** [comment]
> By the way, is the development still active? According to [release log](https://github.com/volta-cli/volta/blob/main/RELEASES.md) I would guess that the Volta is in maintenance mode only.
> 
> Is there any perspective? I don't see even newish blog posts https://blog.volta.sh/

Commits have also stopped on main https://github.com/volta-cli/volta/commits/main

**Comment by charlespierce** [comment]
Hey all! Development is still active, though slow 😅 All of the maintainers have other responsibilities at our day jobs and so haven't had a ton of time to dedicate to Volta lately. I know I personally have been transitioning into a new role and so have spent a lot of time with that and haven't been able to put as much focus on Volta as I would like.

On the main topic, as mentioned in my comment from a couple years ago, expanding to other ecosystems is definitely something we've thought about. The biggest hurdle is that it would take a pretty significant refactor of the approach, to separate out the node-specific code from the larger ecosystem-agnostic parts. I have a few ideas there, but nothing that I've been able to coalesce into an RFC as yet.

**Comment by dominikj111** [comment]
Is there any roadmap?

**Comment by linux-china** [comment]
Guys, and I think https://github.com/mitsuhiko/rye  is almost like Volta Python now.
