### ISSUE TITLE
volta pin with multiple pins, doesn't pin them all

### ISSUE THREAD

**Issue by maraisr** [volta-cli/volta#930]
Running `volta pin node@latest yarn@latest` isn't pinning yarn in the package.json, but only node. Despite installing/pulling both.

**Comment by charlespierce** [comment]
Hi @maraisr, thanks for reporting! I can't seem to reproduce this on my side, can you provide a bit more info?

- What version of Volta are you using?
- What OS is this happening under?
- What are the contents of `package.json` both before and after the `volta pin` command (Specifically the `"volta"` section)?
- What is the terminal output of running `volta pin node@latest yarn@latest`?

**Comment by maraisr** [comment]
Hi @charlespierce, thanks for the prompt response.

Version: 1.0.1
OS: macOS Big Sur 11.1
Before:
```json
	"volta": {
		"node": "14.0.0",
		"yarn": "1.20.0"
	}
```
> Will note; is valid json.
After:

_ran_:

```
$ volta pin node@latest yarn@latest
success: pinned node@15.7.0 (with npm@7.4.3) in package.json
success: pinned yarn@1.22.10 in package.json

```

```json
       "volta": {
		"node": "15.7.0",
		"yarn": "1.22.10"
	}
```

Which looks like issue has been fixed. 
---

To be honest the line "What version of Volta are you using?" was the resolution for this one. I was on 0.6. Sorry for wasting your time with this one.
