### ISSUE TITLE
engines fields support in package.json

### ISSUE THREAD

**Issue by linux-china** [volta-cli/volta#933]
Now volta supports  "volta"  field to switch node & npm, and plan to support standard "engines" field?

```
"engines": {
    "node": "15.8.0",
    "npm": "7.5.2"
  },
```

**Comment by ljharb** [comment]
The engines field is always a range, and volta supports a single version only, so it might not make sense.

**Comment by chriskrycho** [comment]
Yeah, unfortunately while the `engines` field looks like it might work for this at first blush, @ljharb  is exactly right. See [this comment](https://github.com/volta-cli/volta/issues/742#issuecomment-631588143) for a detailed description of why.
