### ISSUE TITLE
The current operating system (MINGW64_NT-10.0-19041) does not appear to be supported by Volta

### ISSUE THREAD

**Issue by VINCENGUYEN-JS** [volta-cli/volta#936]
I run curl https://get.volta.sh | bash on  git-bash (Window-Home-10) , and the errors pop up , any idea ?

Error: The current operating system (MINGW64_NT-10.0-19041) does not appear to be supported by Volta.

Error: Could not download Volta version '1.0.1'. See https://github.com/volta-cli/volta/releases for a list of available releases

**Comment by charlespierce** [comment]
Hi @VINCENGUYEN-JS, thanks for reaching out! Though Git Bash does emulation of a unix-like environment, ultimately it is still on Windows. As such, to install Volta for Windows you'll need to use the `.msi` installer found in [the latest release](https://github.com/volta-cli/volta/releases/latest) to install Volta. After running the installer, you likely will need to re-launch Git Bash, but then it should work as expected (Git Bash is one of the terminals we use Volta on regularly, so if there's something that isn't working correctly that's definitely a bug).

**Comment by charlespierce** [comment]
Closing this as there's been no response, but feel free to re-open if there are still outstanding questions!
