### ISSUE TITLE
Volta not installing `git-node` from `node-core-utils` correctly

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#937]
See https://github.com/volta-cli/volta/issues/761#issuecomment-778383491, it appears that globally installing `node-core-utils` results in the tool `git-node` being installed, but in a strange way that doesn't interact cleanly with how Volta sets up its internal directory structure.

@bmeck, can you provide the error message / terminal output of what happens when it goes wrong?

**Comment by bmeck** [comment]
No error message, the bin isn't in `~/.volta/bin` at all so you cannot use `git-node`, but `volta which git-node` gives `/Users/bfarias/.volta/tools/image/node/14.15.5/bin/git-node`. Direct invocation of the full path of `/Users/bfarias/.volta/tools/image/node/14.15.5/bin/git-node` does appear to work.

**Comment by charlespierce** [comment]
Ohh, that's interesting. Out of curiosity, which version of Volta are you using (`volta --version`)? That appears to be installing something into the `node` directory, which it shouldn't be doing on 0.9.0 or above. On lower versions it should show an error, but there's an environment variable (`VOLTA_UNSAFE_GLOBAL`) that allows you to work around that issue.

**Comment by bmeck** [comment]
```console
> volta --version
1.0.1
```

**Comment by charlespierce** [comment]
That's very strange, when I install `node-core-utils` using `npm i -g node-core-utils` with both npm 6 and 7 it seems to work correctly, creating the appropriate shims in `~/.volta/bin`. You said you had issues when you were working with the node source, were you in the root of the Node tree when you ran it, or somewhere else?

**Comment by bmeck** [comment]
i was in node's source tree, root of it `~/Documents/oss/node` locally, a clone of https://github.com/nodejs/node

**Comment by charlespierce** [comment]
Hmm, I still can't reproduce, even within the node source on my machine. If you haven't already, can you try running `npm i -g node-core-utils` again, to see if it picks up the bins correctly on a second attempt?

**Comment by bmeck** [comment]
```console
$ pwd
/Users/bfarias/Documents/oss/node
$ which volta
/Users/bfarias/.volta/bin/volta
$ which npm
/Users/bfarias/.volta/bin/npm
$ which node
/Users/bfarias/.volta/bin/node
$ volta list
⚡️ Currently active tools:

    Node: v14.15.5 (default)
    Tool binaries available: NONE

See options for more detailed reports by running `volta list --help`.
$ npm install -g node-core-utils
...
/Users/bfarias/.volta/tools/image/node/14.15.5/bin/ncu-config -> /Users/bfarias/.volta/tools/image/node/14.15.5/lib/node_modules/node-core-utils/bin/ncu-config
/Users/bfarias/.volta/tools/image/node/14.15.5/bin/get-metadata -> /Users/bfarias/.volta/tools/image/node/14.15.5/lib/node_modules/node-core-utils/bin/get-metadata
/Users/bfarias/.volta/tools/image/node/14.15.5/bin/ncu-team -> /Users/bfarias/.volta/tools/image/node/14.15.5/lib/node_modules/node-core-utils/bin/ncu-team
/Users/bfarias/.volta/tools/image/node/14.15.5/bin/git-node -> /Users/bfarias/.volta/tools/image/node/14.15.5/lib/node_modules/node-core-utils/bin/git-node
/Users/bfarias/.volta/tools/image/node/14.15.5/bin/ncu-ci -> /Users/bfarias/.volta/tools/image/node/14.15.5/lib/node_modules/node-core-utils/bin/ncu-ci
+ node-core-utils@1.26.0
updated 1 package in 8.434s
```

I managed to get the node version picked up by instead of using `volta install node@15` to instead install w/o a version and got a 14.

**Comment by charlespierce** [comment]
That just gets stranger and stranger. It looks like your shell is somehow running the bundled `npm` version _directly_, instead of through the shim, even though `which` clearly shows that `npm` is coming from the shim. If the interception was working correctly, you would see `.../.volta/tmp/.../git-node -> ...` instead in the output, because it installs into a temp directory. The only thing other thing I can think is that the terminal has an npm version cached from some other resolution, so even though `which` shows the right one, it's actually running the wrong one.

Which shell are you using? If it's `zsh` or `bash`, can you run `hash | grep npm`

**Comment by bmeck** [comment]
```
$ help
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
```

```
$ hash | grep npm
   2	/Users/bfarias/.volta/bin/npm
   1	/Users/bfarias/bin/pubnpm # this is an alias with --registry set
```

**Comment by charlespierce** [comment]
That is beyond confusing 😕 , but I appreciate you taking the time to do this back-and-forth debugging. I'm also happy to move to discord if you'd prefer a more synchronous debugging session.

I'm guessing that `type npm` also shows `~/.volta/bin/npm`, and that opening a new terminal doesn't help? Maybe the symlinks are messed up? What does `ls -l ~/.volta/bin` output?

**Comment by bmeck** [comment]
```console
$ type npm
npm is hashed (/Users/bfarias/.volta/bin/npm)
$ ls -l ~/.volta/bin
total 34144
lrwxr-xr-x  1 bfarias  staff       36 Feb 12 12:34 node -> /Users/bfarias/.volta/bin/volta-shim
lrwxr-xr-x  1 bfarias  staff       36 Feb 12 12:34 npm -> /Users/bfarias/.volta/bin/volta-shim
lrwxr-xr-x  1 bfarias  staff       36 Feb 12 12:34 npx -> /Users/bfarias/.volta/bin/volta-shim
-rwxr-xr-x  1 bfarias  staff  7079520 Jan 15 13:43 volta
-rwxr-xr-x  1 bfarias  staff  4313832 Jan 15 13:43 volta-migrate
-rwxr-xr-x  1 bfarias  staff  6079056 Jan 15 13:43 volta-shim
lrwxr-xr-x  1 bfarias  staff       36 Feb 12 12:34 yarn -> /Users/bfarias/.volta/bin/volta-shim
```

New terminal has no effect to my knowledge.

**Comment by charlespierce** [comment]
That all looks correct. Next I guess would be to see if we can get some more diagnostic information when it runs the installation:

```
VOLTA_LOGLEVEL=debug npm i -g node-core-utils
```

That should output some messages with `[verbose]` about what Volta is doing. Unfortunately, I think it might be limited around the actual installation process (we'll have to beef that up in the future).

**Comment by charlespierce** [comment]
Closing as we're not able to reproduce. If this is still an issue and you're available to investigate further, please feel free to re-open (or reach out on Discord).
