### ISSUE TITLE
Blocked by Microsoft Defender SmartScreen 

### ISSUE THREAD

**Issue by jakub-g** [volta-cli/volta#942]
Hello folks,

not sure how actionable is this on your side, but just FYI, I got this on Windows after downloading volta 1.0.1 `volta-1.0.1-windows-x86_64.msi` from https://github.com/volta-cli/volta/releases/download/v1.0.1/volta-1.0.1-windows-x86_64.msi on my corporate machine:

![image](https://user-images.githubusercontent.com/1437027/108369206-a0985580-71fb-11eb-85ad-eec6e3510466.png)
(upon clicking "more info", the 2nd screen shows up with `Run anyway` button)

(In my private machine I didn't get this warning though).

I'm wondering if this is linked to the not-full activation of developer mode for some reason (maybe an antivirus or some corp config is preventing the installation):

![image](https://user-images.githubusercontent.com/1437027/108370953-8b242b00-71fd-11eb-9e46-59ab769d2003.png)

**Comment by charlespierce** [comment]
Hi @jakub-g, unfortunately that's the standard Microsoft SmartScreen warning. We have a code-signing certificate and the installers are signed with it, however the certificate doesn't yet have enough reputation to bypass that screen. When enough people have installed it that the algorithm is convinced it isn't malicious, then that should go away. AFAIK, the "Run anyway" button should work to run the installer, they just add some friction to the process to make sure users aren't installing malware.

**Comment by jakub-g** [comment]
Ok I see. Thanks for quick response!
