### ISSUE TITLE
Home to setup volta with volta-1.0.1-windows.zip version on Windows?

### ISSUE THREAD

**Issue by Miroxyz** [volta-cli/volta#944]
I have installed node with the command `volta install node`.
But I got `node: command not found` when typing `node -v`.

![Snipaste_2021-02-20_08-10-38](https://user-images.githubusercontent.com/69784329/108574909-896c7b80-7353-11eb-80cc-988ad53833e8.png)

**Comment by charlespierce** [comment]
Hi @Miroxyz! If you're using the `.zip` file, which only contains the binaries, you'll also need to perform the steps that the installer does, described under "Custom Installers" in [the advanced docs](https://docs.volta.sh/advanced/installers).

Given the issue you're seeing, most likely the only other piece you need to do is to add the Volta shim directory (defaulted to `%LOCALAPPDATA%\Volta\bin` to your PATH environment variable.

**Comment by charlespierce** [comment]
Closing as I believe the question was answered. That said, please feel free to re-open if there are still issues or if you have additional questions.
