### ISSUE TITLE
The $HOME directory location - windows 10

### ISSUE THREAD

**Issue by nemanjamilosavljevic-newtron** [volta-cli/volta#949]
First of all, great tool! I believe it is currently the best node and dependencies manager out there!

This is my first time using it on Win 10 (without WSL) and the reason I'm writing is because the $HOME folders are being generated within the project/folder that the commands are being executed from.

For example, I would call `volta install node ` from the `/app` folder, it would generate $HOME in that one, and then if I went to the `/app/src` folder for some reason and called `yarn add some-dep`, the parent $HOME folder is not recognized and the folder is generated there as well:

```ts
/app
  $HOME
    .volta
  /src
    $HOME
      .volta
    /lib
  ...
```

**Comment by nemanjamilosavljevic-newtron** [comment]
Is it expected on windows to have the $HOME folder(s) in the application folder structure?

**Comment by charlespierce** [comment]
Hi @nemanjamilosavljevic-newtron, that's very odd! No, it's not expected to have `$HOME` (or anything Volta-related) in the application structure. The `$HOME` is a Unix-style reference to an environment variable, which doesn't have any special meaning in Windows.

Based on the fact that it is creating that subdirectory in every directory that you run a command, it appears that Volta believes it should be installing tools in `$HOME/.volta`, which makes sense on Unix, but isn't correct for Windows and is being interpreted as a literal relative path, instead of an absolute path. Do you have the `VOLTA_HOME` environment variable set on Windows?

Can you share what shell you are using and how you installed Volta?

**Comment by nemanjamilosavljevic-newtron** [comment]
Hi @charlespierce, thanks for jumping on this issue of mine so quickly ;)
I've used Volta on mac where it worked correctly, but there I didn't have to configure anything specifically for it to work.
On Windows, however, I've struggled to set the correct Path and system variables, which is where, I believe, the error lies.
I was using the Shim directory section of this document to configure my environmental variables https://docs.volta.sh/advanced/installers
It was not quite clear to me how to implement it.

I'm using Cmder and IntelliJ Idea's terminal.

I've installed it via .msi installer as an admin user and I'm using it as a regular user.

**Comment by charlespierce** [comment]
Got it! Looks like we have an opportunity to make that section a little more clear :+1: For Volta installed as an admin user but used as a regular user, the only thing you should need to do is update the `Path` for your user account to include the path to the shim directory. I'm not at my Windows computer right now to give 100% accurate instructions, but roughly speaking, if you open up Windows settings and search for "Environment variables", one of the options is "Edit Environment Variables for the current user" or something similar.

Within that, there should already be a `Path` variable that you can modify. What you want to add is (assuming a basic Windows install and not multiple drives): `C:\Users\{your username}\AppData\Local\Volta\bin` That's where Volta will install the shims (`%LOCALAPPDATA%\Volta\bin`). You also want to find where `VOLTA_HOME` is set and remove it (or any references to `$HOME/.volta`).

**Comment by nemanjamilosavljevic-newtron** [comment]
Okay. I have removed everything from User and System variables regarding the Volta.
Now, this is the only thing:

User variables:
`C:\Users\<user>\AppData\Local\Volta\bin`

I have restarted the computer and tried `volta` in PowerShell:
```ts
volta : The term 'volta' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ volta
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (volta:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
There seems to be something missing.

**Comment by charlespierce** [comment]
Ahh, once again I wasn't as precise as I could have been, apologies! While the changes to the User environment variables were good, the System `Path` should have had a reference to Volta that needed to stay there. Specifically, it should have an entry `C:\Program Files\Volta\`. The difference between the two is:

* On install, the core Volta binaries (including the root `volta` command) are installed into `Program Files` and an entry is added to the system `Path` to point there. That makes `volta` (and also `node`, `npm`, etc.) work out of the box.
* On install, the _user_ `Path` is updated to include the `AppData` path, and that is where any 3rd party shims are created (e.g. if you do `npm install --global typescript`, we install the shims to `tsc` and `tsserver` there, to allow for the project delegation behavior).

So for Windows, there is one Path entry that applies to all users, which is in the System environment variables, and another that applies to a single user, which is in the user environment variables. I hope that makes it more clear.

**Comment by charlespierce** [comment]
Oh, and actually one thing we should absolutely have in the documentation: If you install as a different user, all you should need to do up-front (assuming no manual changes have been made to the system) is to run `volta setup`. That will make the necessary modifications to the user environment variables to get things set up correctly. It's a little late for that now, because it wasn't clearly documented, but that was the intent of that command.

**Comment by nemanjamilosavljevic-newtron** [comment]
Hey @charlespierce, 
Thanks so much for your assistance!

Yes, that makes sense. It works now!

As for the current state of the documentation goes, all is forgiven. You've built such a great tool that helps all that are aware of this solution and makes our daily routine much better! Thank you for that!

As for the future versions of the documentation, if you don't mind, I'd like to chip in and review your next version of the docs, at least from my perspective, to try and make sure all is clear and the number of this kind of iterations is reduced to the minimum ;)

As for different users, I'm not 100% sure, but I believe that when I have logged in as a regular user, I haven't had access to volta, so in that case, I wouldn't be able to run `volta setup`.

**Comment by charlespierce** [comment]
@nemanjamilosavljevic-newtron Super glad to hear you're enjoying the tool, despite the hiccup with getting it working! I'll definitely look to tag you in the PR when we make some tweaks to the installer docs :+1:
