### ISSUE TITLE
Support `install --registry xxxxx`

### ISSUE THREAD

**Issue by lengthmin** [volta-cli/volta#954]
Some package may only available on private registry.

## Usage

```sh
volta install --registry http://xxx.xxx/ package@version
```

**Comment by charlespierce** [comment]
Hi @lengthmin! When installing a package, `volta install` uses `npm` under the hood, so we actually recommend you use `npm install --global <package>` or `yarn global add <package>` in general. In that case, you can pass `--registry` directly.

Additionally, if you want persistent settings, you can use `~/.npmrc` to change the registry on a repeatable basis.

**Comment by lengthmin** [comment]
Got it. Thanks for the info.
