### ISSUE TITLE
Is there a way to pin a version other than package.json?

### ISSUE THREAD

**Issue by yanoryuichi** [volta-cli/volta#955]
Hi. Is there a way to pin a version other than package.json? It's like .node-version file in nodenv. If it's possible, I can set the version file ignored in Git. Thanks.

**Comment by charlespierce** [comment]
Hi @yanoryuichi, currently there isn't any support for a separate file, however that's one of the use-cases that's been suggested. Follow #282 for more (it still needs some design work to determine the appropriate precedence and behavior).
