### ISSUE TITLE
Some form of preset installation

### ISSUE THREAD

**Issue by mukkuzzz** [volta-cli/volta#960]
# What?
For context like if you enter something like this:-
``` volta preset install "discord-bot"```
it would install all the things required for an discord bot.
and this would be pre-configured by the user 
```volta configure discord ="discord.js = "123.123",blah = "1.23.3""```
# How?
I don't know because i am bad(i do not write in rust ) at rust

**Comment by charlespierce** [comment]
Hi @mukkuzzz, thanks for the suggestion! I'm not sure it fits into Volta, however. Volta is responsible for managing your Node and package manager versions (e.g. npm or Yarn). It doesn't (and currently can't) manage creating projects or installing dependencies.

It sounds like what you're looking for is a tool for bootstrapping a project from a blueprint, something akin to [`yarn create`](https://classic.yarnpkg.com/en/docs/cli/create/) or [`npm init <name>`](https://docs.npmjs.com/cli/v7/commands/npm-init). I would recommend you look into those commands (and the associated `create-*` packages that power them.

**Comment by mukkuzzz** [comment]
@charlespierce thanks for the instant reply. if it didn't feel suitable then no problem. Very thank you for your assistance 😄
