### ISSUE TITLE
[Feature Request] Ability to specify node/npm major or minor version in package.json

### ISSUE THREAD

**Issue by Fyko** [volta-cli/volta#961]
With volta's current package.json support, you must specify the full version of the node or npm installment you wish to use.
It would be useful if you could specify either a major or minor version like you can with `volta install` (`volta install node@15`).
Examples:
```json
{
    "node": "15",
    "npm": "7"
}
```
```json
{
    "node": "15.x.x",
    "npm": "7.x.x"
}
```
```json
{
    "node": "15.11.x",
    "npm": "7.6.x"
}
```

**Comment by charlespierce** [comment]
Hi @Fyko, see #925, which I believe covers this use-case. There's also a discussion there about some of the design goals of Volta and why it doesn't currently support that.
