### ISSUE TITLE
Volta can't find binaries installed by the new methedology of yarn@berry

### ISSUE THREAD

**Issue by ms2052001** [volta-cli/volta#965]
I have tried to run a CLI command of a package install by yarn@berry, but this is what I got:

```bash
~/myp/arabi/arabi رئيسي* ⇡
❯ syncpack
Volta error: Could not locate executable `syncpack` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
```

But it's already installed, here is where yarn stowed them:

```bash
~/myp/arabi/arabi رئيسي* ⇡
❯ yarn bin syncpack
/home/ms/myp/arabi/arabi/.yarn/cache/syncpack-npm-5.7.11-757e0f9799-4edc4533c7.zip/node_modules/syncpack/dist/bin.js

~/myp/arabi/arabi رئيسي* ⇡
❯ yarn bin 
➤ YN0000: eslint
➤ YN0000: lint-staged
➤ YN0000: nodemon
➤ YN0000: prettier
➤ YN0000: rimraf
➤ YN0000: scripty
➤ YN0000: simple-git-hooks
➤ YN0000: syncpack
➤ YN0000: syncpack-fix-mismatches
➤ YN0000: syncpack-format
➤ YN0000: syncpack-list
➤ YN0000: syncpack-list-mismatches
➤ YN0000: syncpack-set-semver-ranges
➤ YN0000: webpack-bundle-analyzer
➤ YN0000: babel
➤ YN0000: babel-external-helpers
➤ YN0000: webpack-cli
➤ YN0000: webpack-dev-server
➤ YN0000: webpack
➤ YN0000: Done in 0s 99ms
```
 
I hope I can get the new methodology of yarn working with volta soon.

**Comment by charlespierce** [comment]
Hi @ms2052001, that's a known issue with Yarn 2's Plug'n'Play behavior: https://github.com/volta-cli/volta/issues/158 We're also tracking Yarn 2.0 in general under: https://github.com/volta-cli/volta/issues/651

In the short term, you can use Yarn's suggested approach of running `yarn <binary>` (which is very likely what Volta will eventually wind up using), though you then lose the ergonomic benefits of Volta's shims.
