### ISSUE TITLE
Support bottles for M1 on homebrew

### ISSUE THREAD

**Issue by domoritz** [volta-cli/volta#977]
`brew install volta` results in an error `Error: volta: no bottle available!`. It would be great if there were bottles for M1.

**Comment by domoritz** [comment]
`brew install --build-from-source volta` results in

```
==> Cloning https://github.com/volta-cli/volta.git
Updating /Users/dominik/Library/Caches/Homebrew/volta--git
==> Checking out tag v1.0.4
HEAD is now at e4ab360 Merge pull request #975 from charlespierce/v1.0.4
HEAD is now at e4ab360 Merge pull request #975 from charlespierce/v1.0.4
==> cargo install
Last 15 lines from /Users/dominik/Library/Logs/Homebrew/volta/01.cargo:


warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to compile `volta v1.0.4 (/private/tmp/volta-20210424-56474-1ry5z44)`, intermediate artifacts can be found at `/private/tmp/volta-20210424-56474-1ry5z44/target`

Caused by:
  build failed

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by cprecioso** [comment]
AFAICT, brew is not building bottles because of https://github.com/Homebrew/homebrew-core/issues/68301. However, I did build from source and it worked just fine, so maybe the issue does not apply anymore to volta?

**Comment by domoritz** [comment]
Yep, Volta works great on M1 but I also had to install from source. I think the formula just needs to be fixed in some way.

**Comment by cprecioso** [comment]
Tested `brew install volta --build-bottle` and `brew bottle` on a M1, and no errors received. I think this is now a matter of homebrew enabling bottles for `volta`.

**Comment by cprecioso** [comment]
Volta just got a brand new bottle!
https://github.com/Homebrew/homebrew-core/commit/11e6a368c1f9fb260c7152996ce0cb154d92c495

@domoritz this is issue can now probably be closed

**Comment by chriskrycho** [comment]
@cprecioso thank so much for getting that squared away on that side, and @domoritz thanks for reporting!

**Comment by domoritz** [comment]
Awesome. Works for me as well.
