### ISSUE TITLE
[Suggestion] Allow installing/pinning global dependencies

### ISSUE THREAD

**Issue by DerekZiemba** [volta-cli/volta#985]
Can a feature be added to allow Volta to pin global dependencies in addition to node, npm, and yarn?  

The package entry would look something like:
```json
  "volta": {
    "node": "16.1.0",
    "npm": "7.11.2",
    "typescript": "~4.2.4",
    "eslint": "^7.25.0",
    "prettier": "^2.2.1",
    "cross-env": "^7.0.3",
    "npm-run-all": "^4.1.5"
  }
```

## Why?:
1. For some reason or another I often have to nuke my projects node_modules folder to get things working. It often requires exiting out of vscode, deleting the folder in file explorer and waiting minutes for Windows to delete 10's of thousands of files, followed by additional time to run `npm install` afterwards. 
2. To reduce file duplication and disk space.  If 2 projects use the same global dependencies and environment, they could share.

**Comment by charlespierce** [comment]
Hi @DerekZiemba, we talked about this early on in the project and ultimately decided against it. The main reason was that we didn't want to try to take over responsibilities / replace the existing package managers. Those tools can already be pinned using `dependencies` / `devDependencies` and the existing tools (like npm and Yarn) for managing dependencies.

The Volta global shims are smart—they will detect if you have a dependency on one of those tools and automatically use the local version—but we stopped short of handling the complicated dependency graph work that is already the main focus of the package managers.
