### ISSUE TITLE
Security contact?

### ISSUE THREAD

**Issue by nightwatchcyber** [volta-cli/volta#995]
What's the best security contact for this project? Thanks

**Comment by chriskrycho** [comment]
Hey @nightwatchcyber – thanks for pinging. We'll set up a formal disclosure process, but in the meantime please email me and @charlespierce, cc'ing the following emails:

- hello@chriskrycho.com
- ckrycho@linkedin.com
- cpierce@linkedin.com

**Comment by nightwatchcyber** [comment]
Will do, thanks
