### ISSUE TITLE
How to setup volta for all users?

### ISSUE THREAD

**Issue by artalar** [volta-cli/volta#999]
Hi there! I have some scripts which run by the guest user or some others.
For example, scripts from [this extension](https://marketplace.visualstudio.com/items?itemName=lukaserat.npm-scripts) fails with `command not found: npm`.

So, is there any way to setup volta for all users in the system?

**Comment by ShynRou** [comment]
Having the same issue with my gitlab-runner user, which does not and should not have access to /root.

**Comment by ShynRou** [comment]
@charlespierce Ah thanks for the pointer, I'll test it out later.
